---
title: "Cervical Rib (Thoracic Outlet Syndrome)"
---

## **Look**

1.  **Scar over clavicle or supra-clavicular fossa:**
    -   Check for surgical scars or other abnormalities.
2.  **Mass in the supra-clavicular region:**
    -   Note any swelling or palpable masses.
3.  **Asymmetry in size of limbs:**
    -   Compare the size of the affected limb with the unaffected one.
4.  **Venous distension of chest wall:**
    -   Observe for prominent veins on the chest wall.

### **Hands**

1.  **Wasting of small muscles in the hand:**
    -   Check for atrophy of the thenar and hypothenar muscles.
2.  **Trophic changes in fingers:**
    -   Look for changes in skin texture, sweating, nail appearance, or color.

### **Feel**

1.  **Temperature difference in hands:**
    -   Assess for temperature differences between the affected and unaffected hand.
2.  **Sensation:**
    -   Evaluate dermatomes and peripheral nerves, focusing on the medial forearm and arm to differentiate from the ulnar nerve.
    -   Test sensation in the hands, especially around the brachial plexus.

## **Move**

1.  **Roo’s Test (Neurologic):**
    -   Ask the patient to brace their shoulders back and fully flex elbows.
    -   Have them rapidly flex and extend fingers.
    -   Positive result if neurologic symptoms (numbness, tingling, weakness) are reproduced.
2.  **Adson’s Test (Vascular):**
    -   Extend the head and rotate it to the affected side (similar to Spurlings test).
    -   Abduct the arm to 30 degrees with the elbow straight.
    -   Feel for the radial pulse on the same side.
    -   Take a deep breath in.
    -   Positive if there is an alteration in the quality of the pulse (e.g., disappearance or weakening of the pulse).
