project:
  type: website
  output-dir: docs
  resources:
    - ads.txt 

website:
  search: 
    location: sidebar
    type: textbox
  title: "knotes"
  site-url: https://www.knotes.co.in
  description: "Kishore Puthezhath's digital garden"
  site-path: '/'
  favicon: /image/logo.png
  #announcement: 
   #icon: info-circle
   #dismissable: true
   #content: "**Save the date** - 11th Basic Orthopaedic Pathology Course **31 Jan** to **9 Feb 2025**  [click here](https://www.knotes.co.in/education%20technology/basicc)"
   #type: light
   #position: below-navbar
  navbar:
    background: "#f9fbfd"
    foreground: dark
    search: false
    tools:
     - icon: linkedin
       text: linkedin
       href: https://www.linkedin.com/in/kishore-puthezhath-frcs-48482747/
     - icon: github
       text: github
       href: https://github.com/drkmenon
    logo: /image/knotes.png
    title: false
    left:
      - href: index.qmd
        text: Home
      - href: Revision notes/Basic science/Bone.qmd
        text: Orthopaedics
      - href: Research Methodology/Science.qmd
        text: Research
      - text: My blog
        href: posts.qmd
      - icon: rss
        href: posts.xml
    right:
      - text: "More"
        menu:
          - author.qmd
          - articles.qmd
          - tenet.qmd
  sidebar:
     style: "floating"
     contents: 
      - section: Orthopaedics
        contents: Revision notes
      - text: "---"
      - section: Undergraduate
        contents: Orthopaedics
      - text: "---"
      - section: Medical Education
        contents: Education technology
      - text: "---"  
      - section: Research
        contents: Research Methodology
      - text: "---"
      - section: Practical Catallactics
        contents: Catallactics
      - text: "---"
      - section: Blog
        contents: posts
      - text: "---"
      - section: Musing
        contents: News
      - text: "---"
      - section: For patients
        contents: Patient education
      - text: "---"
    
     
      
     
  page-navigation: true
  back-to-top-navigation: true
  page-footer:
    right: "Copyright 2025 @ Kishore Puthezhath"
    left: "Opinions are for informational purposes"
    background: white
  reader-mode: false
  cookie-consent:
    type: implied
    style: simple
    palette: light
  google-analytics:
    tracking-id: "G-7GYDLCJCZE"
    anonymize-ip: true
  margin-header: subscribe.html
  twitter-card: true  
  open-graph: true
  
  
  
    
format:
  html:
    theme:
      light: [cosmo, theme.scss]
    mainfont: inter
    code-copy: true
    code-overflow: wrap
    fontsize: 1.2rem
    linestretch: 1.5
    fontcolor: "#1c1c1c"
    linkcolor: "#0072bb"
    backgroundcolor: "white"
    css: styles.css
    toc: true
    responsive: true
    freeze: true
    include-in-header: _metadata.html
    grid:
      sidebar-width: 250px
      body-width: 900px
      margin-width: 300px

editor: visual
bibliography: references.bib
comments: 
  hypothesis: true


 
