project:
  type: website
  output-dir: docs

website:
  title: "knotes"
  favicon: /image/logo.png
  navbar:
    left:
      - href: index.qmd
        text: Home
  sidebar:
    contents: auto
  page-navigation: true
  back-to-top-navigation: true
  page-footer: 
   "Copyright 2024 @ Kishore Puthezhath, Opinions are for informational purposes only and not personalized advice"
  reader-mode: true
  cookie-consent:
    type: implied
    style: simple
    palette: light
  google-analytics:
    tracking-id: "G-7GYDLCJCZE"
    anonymize-ip: true
  margin-header: 
    "Kishore's official website"
  open-graph: true
  
    
format:
  html:
    theme:
     journal
    css: styles.css
    toc: true

editor: visual
bibliography: references.bib

 
