project:
  type: website
  output-dir: docs

website:
  title: "knotes"
  navbar:
    left:
      - href: index.qmd
        text: Home
  sidebar:
    contents: auto
  page-navigation: true
  back-to-top-navigation: true
  page-footer: "Copyright 2024, Kishore Puthezhath" 
  reader-mode: true
    
format:
  html:
    theme:
     light: flatly
     dark: darkly
    css: styles.css
    toc: true

editor: visual

 
