---
title: "Welcome new readers"
backgroundcolor: white
tag: [Digital garden]
---

```{=html}
<div style="background-color: #ffffff; padding: 10px 0; text-align: center;">
    <h1> </h1>
    <p> Please select the content you wish to read from the sidebar or click below  </p>
    <a href= https://www.knotes.co.in/revision%20notes/basic%20science/bone style="display: inline-block; margin: 10px; padding: 10px 20px; background-color: #00609b; color: white; text-decoration: none; border-radius: 5px;">Orthopaedics</a>
    <a href=https://www.knotes.co.in/biomedical/research%20methodology/science style="display: inline-block; margin: 10px; padding: 10px 20px; background-color: #006200; color: white; text-decoration: none; border-radius: 5px;">Research</a>
</div>
```

Contents are best viewed on a screen 10 inches or larger.

**About These Notes 🌱** 🌿 **🌳 🌸**

Hi! Welcome to Knotes, my collection of digital notes. They might seem a bit unconventional, so here’s some context to help you navigate.

These notes are like a growing garden—starting as seeds of thought (borrowed, taken or imagined 🌱), maturing into seedlings (🌿), and eventually blossoming into fully formed ideas (🌳, 🌸). They’re primarily written for myself, serving as a single point for my quick reference ([My collected notes in Orthopaedics](Revision notes/Basic science/Bone.qmd) 🌳). Some, I’ve decided to share publicly out of curiosity 🤟([My baby steps in research](Research Methodology/science.qmd))

If something feels unclear or under explained, it’s likely because these notes weren’t originally intended for an external audience. That’s part of the original idea 🌻 (`Write notes for yourself first, without prioritizing external readers`).

There is an organized index and navigation system for the notes to bring in some sanity. You’ll need to start by following a link to an entry point to the garden. If you’re not sure where to begin, you might want to check out §

[Research](https://www.knotes.co.in/biomedical/research%20methodology/science)

[Orthopaedics](https://www.knotes.co.in/revision%20notes/basic%20science/bone)

[Medical Education](https://www.knotes.co.in/education%20technology/zotero)

[Catallactics](https://www.knotes.co.in/catallactics/personal/conifers)

------------------------------------------------------------------------

**PPS**: Some of the [Orthopaedics](https://www.knotes.co.in/revision%20notes/basic%20science/bone) content is a compilation of already available materials rather than original works. These are included for quick revision purposes. If you notice any copyright infringement, please inform me via email.

## 👋 Contact me {#sec-contact-me}

I teach at a medical school, Amala Institute of Medical Sciences and my office address is below:

Kishore Puthezhath\
Department of Orthopaedics\
AIMS, Kerala, Thrissur, KL 680555

You can reach me by email at [drkmenon\@gmail.com](mailto:drkmenon@gmail.com){.email}. I do try to answer.

If you send me an email and you don't hear back, Send it again!

## Keep updated

To subscribe for regular updates whenever a new blog post is published, please provide your email address in the field below and hit subscribe:

```{=html}
<!-- Begin Mailchimp Signup Form -->
<div id="mc_embed_shell">
      <link href="//cdn-images.mailchimp.com/embedcode/classic-061523.css" rel="stylesheet" type="text/css">
  <style type="text/css">
        #mc_embed_signup{background:#fff; false;clear:left; font:14px Helvetica,Arial,sans-serif; width: px;}
        /* Add your own Mailchimp form style overrides in your site stylesheet or in this style block.
           We recommend moving this block and the preceding CSS link to the HEAD of your HTML file. */
</style>
<div id="mc_embed_signup">
    <form action="https://knotes.us17.list-manage.com/subscribe/post?u=cbd11e712b45e98cdaab2dd4d&amp;id=aeaca1e768&amp;f_id=00dbc2e1f0" method="post" id="mc-embedded-subscribe-form" name="mc-embedded-subscribe-form" class="validate" target="_blank">
        <div id="mc_embed_signup_scroll"><h2>Subscribe</h2>
            <div class="indicates-required"><span class="asterisk">*</span> indicates required</div>
            <div class="mc-field-group"><label for="mce-EMAIL">Email Address <span class="asterisk">*</span></label><input type="email" name="EMAIL" class="required email" id="mce-EMAIL" required="" value=""></div>
        <div id="mce-responses" class="clear foot">
            <div class="response" id="mce-error-response" style="display: none;"></div>
            <div class="response" id="mce-success-response" style="display: none;"></div>
        </div>
    <div aria-hidden="true" style="position: absolute; left: -5000px;">
        /* real people should not fill this in and expect good things - do not remove this or risk form bot signups */
        <input type="text" name="b_cbd11e712b45e98cdaab2dd4d_aeaca1e768" tabindex="-1" value="">
    </div>
        <div class="optionalParent">
            <div class="clear foot">
                <input type="submit" name="subscribe" id="mc-embedded-subscribe" class="button" value="Subscribe">
                
            </div>
        </div>
    </div>
</form>
</div>
<script type="text/javascript" src="//s3.amazonaws.com/downloads.mailchimp.com/js/mc-validate.js"></script><script type="text/javascript">(function($) {window.fnames = new Array(); window.ftypes = new Array();fnames[0]='EMAIL';ftypes[0]='email';fnames[1]='FNAME';ftypes[1]='text';fnames[2]='LNAME';ftypes[2]='text';fnames[3]='ADDRESS';ftypes[3]='address';fnames[4]='PHONE';ftypes[4]='phone';fnames[5]='BIRTHDAY';ftypes[5]='birthday';}(jQuery));var $mcj = jQuery.noConflict(true);</script></div>
<!-- End Mailchimp Signup Form -->
```

By submitting your email address and clicking "Subscribe", you consent to receive updates whenever a new blog post is published. This will help us improve the meaning and content of our blog by keeping you informed about our latest articles and updates. Thank you for subscribing!
