---
title: "PBL methodology"
order: 8
---

## Problem based learning

Go to [PBL](https://www.knotes.co.in/orthopaedics/pbl%20modules/scfr)[Module](https://www.knotes.co.in/revision%20notes/pbl%20modules/scfr)

What is PBL?

:   `In problem based learning (PBL) students use “triggers” from the problem case or scenario to define their own learning objectives.`

    Subsequently they do independent, self directed study before returning to the group to discuss and refine their acquired knowledge.

    Thus, PBL is not about problem solving per se, but rather it uses appropriate problems to increase knowledge and understanding [@wood2003a].

## How to create effective PBL scenarios [^1]

[^1]: *Adapted from Dolmans et al. Med Teacher 1997;19:185-9*

-   Learning objectives likely to be defined by the students after studying the scenario should be consistent with the faculty learning objectives

<!-- -->

-   Problems should be appropriate to the stage of the curriculum and the level of the students’ understanding

-   Scenarios should have sufficient intrinsic interest for the students or relevance to future practice

-   Basic science should be presented in the context of a clinical scenario to encourage integration of knowledge

-   Scenarios should contain cues to stimulate discussion and encourage students to seek explanations for the issues presented

-   The problem should be sufficiently open, so that discussion is not curtailed too early in the process

-   Scenarios should promote participation by the students in seeking information from various learning resources

## Requirements

```{mermaid}
flowchart TD
  A[Participants] --> B[Scribe]
  A[Participants] --> C[tutor]
  A[Participants] --> D[chair]
  A[Participants] --> E[members]
```

::: callout-note
## PBL tutorial process

Step 1—Identify and clarify unfamiliar terms presented in the scenario; scribe lists those that remain unexplained after discussion

Step 2—Define the problem or problems to be discussed; students may have different views on the issues, but all should be considered; scribe records a list of agreed problems

Step 3—“Brainstorming” session to discuss the problem(s), suggesting possible explanations on basis of prior knowledge; students draw on each other’s knowledge and identify areas of incomplete knowledge; scribe records all discussion

Step 4—Review steps 2 and 3 and arrange explanations into tentative solutions; scribe organises the explanations and restructures if necessary

Step 5—Formulate learning objectives; group reaches consensus on the learning objectives; tutor ensures learning objectives are focused, achievable, comprehensive, and appropriate

Step 6—Private study (all students gather information related to each learning objective)

Step 7—Group shares results of private study (students identify their learning resources and share their results); tutor checks learning and may assess the group
:::
