---
title: "Complex procedures"
order: 6
---

Acquisition of procedural skills is a critical element in medical education.

Traditionally, procedural skills are taught using a ‘‘see one - do one’’ approach, based on the Halsted’s teaching model (1904). Recently, two new teaching methods for the acquisition of procedural skills have been described:

#### George and Doto’s 5-Step Method:

1.  **Overview**: Explains why and how the skill is important.
2.  **Demonstration**: The preceptor performs the procedure.
3.  **Students Talk Through the Skill**: The learner verbalizes the steps involved in the procedure.
4.  **Performance**: The learner performs the procedure under supervision.
5.  **Assessment of Performance**: Identifies issues affecting learner’s performance, such as inherent ability, inappropriate task description, previous incorrect techniques, and affective factors. Corrective actions can be initiated based on the identified issues.

*This method is based on Simpson’s taxonomy of the psychomotor domain, focusing on physical skills development. It was initially developed as an educational technique to support the American College of Surgeons’ Advanced Trauma Life Support course in 2001*​

#### Peyton’s 4-Step Method:

1.  **Demonstration**: The preceptor demonstrates the skill.
2.  **Deconstruction**: The procedure is broken down into parts.
3.  **Comprehension**: The learner understands the steps and rationale behind the procedure.
4.  **Performance**: The learner performs the procedure under supervision.

*Peyton’s method differs by combining the demonstration and deconstruction steps, emphasizing the learner’s comprehension and ability to perform the procedure independently*​

**Video showing Mr. J.W. Rodney Peyton FRCS discussing his concepts**: {{< video https://www.youtube.com/embed/iXe1btHlgLQ >}}
