---
title: "How to Begin?"
format: html
editor: visual
order: 4
---

In an ideal situation, if one acquires knowledge that translates to skills useful for society as a whole, the funds needed for her contentment should follow. Hence, the focus should be on knowledge and skill development rather than on money matters.

At this point, she should avoid some common money mistakes:

-   **Big purchases of depreciating assets with debt/EMI**: For example, cars, expensive bikes, etc.\
-   **Tying oneself down with debt obligations**: Be ready to switch jobs that hinder your development. Do not rush into a home loan; take your time.\
-   **Frequent purchases of shiny new electronics, expensive leisure, and luxury items**: This is often called FOMO or the Apple effect. Every year there is at least one "greatest yet" smartphone, and people rush to buy.

Thus, the focus should be on avoiding big expenses and frequent impulsive moderate expenses. Concentrate on independent skill development. Saving at this stage may take a back seat.

Her first encounter with a financial institution will be the bank where she starts her salary/income account. Before that, she should create a PAN, get it linked to her AADHAR number, and make sure that both are identical. This last point is crucial.

Most people in South India have initials as their last name, and PAN accepts only the expanded last name. For example, if someone's name is Raghu R, PAN will require him to provide the expansion, Raghu Ram. If in AADHAR the name is Raghu R, this can cause a lot of trouble in the future, through no fault of the individual. Make sure the name is consistent as Raghu Ram in both AADHAR and PAN before opening a salary account.

If you already have an AADHAR with the name as Raghu R, take some effort to update it to Raghu Ram before applying for PAN.

Hope that one day PAN will allow any name, but until then, be careful.

## PAN Application

If you have an AADHAR, applying for PAN is easy, and getting one is almost instantaneous. Visit the ePAN link on the official Income Tax website and follow the steps.

PAN is the **Permanent Account Number**, a document necessary for your financial journey throughout life.

## Advice for Future Parents in South India

Make sure you give the **full expanded name** in your child’s birth certificate and insist the school uses the same in all school records. Be consistent with your child’s name everywhere else, and insist that a single name is used in all records.

## Agents

It is said that money attracts people just like sugar attracts ants. Agents of all sorts—insurance, investment, loans—will start chasing you.

Now is the time to learn so that you can deal with them favorably and ensure they do not take advantage of your ignorance. In general, understand that agents are **not financial advisers**. If they behave like one, they are impostors. In India, anyone giving financial planning services or financial advice must be registered with SEBI, and their registration must be renewed every 3 years.

## Learn These Seven Financial Concepts

-   Emergency fund\
-   Insurance\
-   Budgeting\
-   Investment\
-   Retirement funding\
-   Leverage and credit\
-   Risk management

### Emergency Fund

This is easy and short. We are most vulnerable when we are sick or unable to apply ourselves. Illness can come unannounced. Smartness lies in expecting the unexpected and being prepared.

Take a part of whatever money is left over after expenses and create an emergency fund. Ideally, open another bank account and designate it as your **emergency account**. Start building it. The aim is to have **12 months of expenses stored in that account without touching it**. This is the foundation of your financial journey. The emergency account will be the **second of the four bank accounts** you will ever have in your life.[^1]

[^1]: At a certain point, this emergency fund can take a more sophisticated form. Your credit card and arbitrage fund can replace the emergency account to prevent money from losing value due to inflation. But at this stage, before rushing to get a credit card and start investments, make sure your emergency account is fully funded.

## 
