---
title: "Getting started with money"
format: html
title-block-banner: false
editor: visual
date: October 2, 2025
order: 1
---

Are we going to discuss about something that is evil? **Is money the root cause of all problems?** By the way, what is money? Why is there so much taboo surrounding money matters and money itself?

Technically money is something that stores value and acts as medium of exchange. For all practical purposes money is just a promise that is trusted by everyone or aleast a sizable group of people. Comodities like gold, fiat currencies like Indian Rupees, digital assets in some countries all can serve the purpose of money.

But in simple terms, **money is what money does**. It amplifies who you are. If you are a criminal, it will make you a bigger criminal. If you are a saint, it will make you an even greater one. Money is neutral—it is neither good nor bad. Power projected onto others, crimes, and deeds that harm people are more visible and capture public imagination. Because of this, most people trace money as the root cause of such problems.

People generally don’t like to talk about money in public. This is especially true in civilisational countries like India. The reason could be philosophical, behavioral and partly paternalistic. **Civilisations have long concluded that desire is the root cause of all misery.** Those who openly talk about money are therefore often looked down upon. They tended to say that **love for money** is the root cause of all miscery (quite rightly!) but people understood that money is the root cause. Baby-boomers everywhere tend to cling to whatever money and assets—and the power that money brings—by all possible means. This holds true from the level of families to that of entire nations. They spread the idea that talking or thinking about money is not everyone’s business, using different techniques to achieve this, including demeaning money itself.

A third, but more profound, reason is behavioral in nature. Those who have money fear that someone may take it away or harm them in some way if they openly talk about money matters. **Unlike knowledge and skills, money attracts envy and criticism rather than admiration and respect.** On the other hand, those who have no money tend to hide this from others rather than learn from them. At best, they only want to know how to make quick money and look at other's money with suspicion.

Yet, beyond all this, the fact remains that money is a very important factor in our lives, and it is essential for many of our wants and needs.

## What are the functions of money?

Money can:

-   Buy things

-   Buy experiences

-   Buy time

-   Buy security

-   Generate more money

-   Create things

-   Create experiences

-   Be given to others\
