---
title: "Safety First"
format: html
order: 5
editor: visual
---

Before starting a car journey, fastening the seat belt is the first and foremost priority. The same applies to your financial journey. In the beginning, you and your knowledge are the only asset you have. Protect it!

What if you suddenly fall sick and are unable to work for some time? An emergency fund can help you manage the temporary loss of income. However, having health insurance that covers major hospital expenses can prevent financial ruin.

If you are young, with a family and dependent parents, consider what would happen to them if you were suddenly gone. They may eventually recover emotionally, but the immediate financial impact can be devastating. A simple term insurance policy, with a small premium, can protect your loved ones from such hardship. Once you have accumulated sufficient assets in the future, you can choose to discontinue this coverage.

Whether it is medical or life insurance, the goal is to protect against rare but catastrophic events — those that might occur once in ten or twenty years, yet have life-altering consequences. It’s not meant for minor, more frequent issues. For instance, a health insurance policy covering only ₹50,000 or ₹2 lakh may not be sufficient to handle a major illness that could cost tens of lakhs.

As you build assets, they too should be protected. When you purchase a house or flat, it is essential to get home insurance. Similarly, protect your financial assets by hedging, which we will discuss later.

Typical types of insurance:

-   Health insurance\
-   Term life insurance\
-   Home insurance\
-   Portfolio hedging\
-   Professional indemnity insurance\
-   Accident and critical illness insurance

Ideally, insurance and investment should not be combined in a single product, as they serve entirely different purposes.
