---
title: Market risk is not the only risk in market
comments: 
  hypothesis: true
date: 13 October 2024
---

The Nifty index came into existence around 29 years ago in April 1996. If you had invested ₹100 on that date, you would have received a compounded annual growth rate (CAGR) of 12.03%, with the initial corpus growing to ₹2296. We all know that in the future, the return may be lower, higher, or even the same. We are blind to the future return of the index, say, after another 29 years; this is what we may call **market risk**.

This average return cleverly hides other important risks: **volatility risk, inaction risk** and **sequence of return risk**. They require a little explanation to understand their true impact on us.

**Sequence of return risk** originates from the fact that, unlike an index, we have a life cycle, and we invest to meet life cycle events without having to beg for help. These events include non-discretionary and discretionary spending after retirement (forced or voluntary), child education, marriage expenses, medical expenses, etc., to mention a few. Hence, whether we like it or not, we have to involuntarily time the market—namely, the starting point of the investment journey, in-between investments (regular or irregular SIPs), and the endpoint when we start withdrawing money as a lump sum or as regular or irregular SWPs.

Essentially, unlike an index, for us, the sequence in which the return is generated matters as much as the rate of return. We may try to understand this from the following example.

Mr. Mony, 65, painstakingly accumulated a corpus of ₹1 crore for his retirement. He retired in 2006 and plans to withdraw ₹4 lakhs every year. He has all his retirement corpus in a Nifty ETF. He did so thinking that in the long term, say, the next 30 years, the CAGR would beat inflation, unlike debt instruments like G-secs or bonds.

Let us analyze his next 5 years. His realized returns are shown below:

| Year | Return |
|------|--------|
| 2007 | +54%   |
| 2008 | -52%   |
| 2009 | +76%   |
| 2010 | +18%   |
| 2011 | -25%   |

Mr. Mony's portfolio calculation for the 5 years is as follows:

((10000000 \* 1.54) - 400000) \* 0.48 - 400000) \* 1.76 - 400000) \* 1.18 - 400000) \* 0.75 - 400000) = ₹9,537,680

He ended up poorer by ₹462,320 in 2011.

This need not be the only sequence that may play out in the future. In fact, there are 5! (5 factorial) ways by which the sequence can play out, i.e., 120 different paths, of which he will experience only one. If all the returns play out in descending order of magnitude, what will be the total portfolio value (TPV) of the retirement fund after 5 years?

Returns:

| Return |
|--------|
| +76%   |
| +54%   |
| +18%   |
| -25%   |
| -52%   |

TPV = (10000000 \* 1.76) - 400000) \* 1.54 - 400000) \* 1.18 - 400000) \* 0.75 - 400000) \* 0.48 - 400000) = ₹10,492,313.60

He would have been richer by ₹492,313.60 in 2011.

What would be the TPV if the returns were sequenced in reverse, in ascending order of magnitude?

| Return |
|--------|
| -52%   |
| -25%   |
| +18%   |
| +54%   |
| +76%   |

TPV = (10000000 \* 0.48) - 400000) \* 0.75 - 400000) \* 1.18 - 400000) \* 1.54 - 400000) \* 1.76 - 400000) = ₹7,086,828.80

He would have lost around 30% of his corpus after 5 years, sitting on a loss of ₹2,913,171.20.

If he had never retired, he would not have faced this problem of sequence of return risk.

**TPV (Buy and hold)**:

-   With returns in ascending order: (10000000 \* 0.48) \* 0.75 \* 1.18 \* 1.54 \* 1.76 = ₹11,513,779.20
-   With returns in descending order: (10000000 \* 1.76) \* 1.54 \* 1.18 \* 0.75 \* 0.48 = ₹11,513,779.20

In summary, if we are buying and holding a volatile asset like an equity index, the sequence in which the return is received every year/month/day never matters. This is because CAGR is calculated by multiplying the periodic returns. If there are no additions or subtractions in between, the order in which we multiply never affects the final value.

::: callout-tip
Sequence of return risk not only affects the TPV when we withdraw but also equally affects TPV when we are periodically adding money through SIPs.
:::

What if we withdraw or add a fixed percentage instead of a fixed amount? When exactly in your life cycle does sequence of return risk bites you most? These and the other risks can be discussed in upcoming articles.
