---
title: "Pay-off formula"
---

## Insurance pay-off

Before buying an insurance product, we should know the cost. That cost can be calculated based on the pay-off formula.

N= 1/p~e~

N is the gross pay-off in percentage

p~e~ is the probability of event. It takes value between 1 and 0, and never 0.

If the probability of more than 15% draw-down of an asset class is 9% (calculated from historical data or Monte Carlo simulation), then p~e~ = 0.09

now,

N=1/0.09, approximately 11 or 1100% of premium

n= N-100% of premium

n is the net pay-off

n here is 10 or 1000%

Assume that the market value M of the asset insured is 22500. We want to insure against \>15% draw-down, i.e,

$$(0.85)X 22500=19125$$

So our target price, T is 19125

## Insurance premium

$$P=(M-T)/(1+n)$$

P here

P = (22500-19125)/1+10)

i.e, P=306.8

306.8 is the maximum amount we should be paying for 1 year premium. If we want to renew the policy every 2 month, the amount should be roughly 50.

`NB: This premium should be between 2-4% of the M, never more than 4%`

For the current M, it should be less than 900 for an Year and less than 150 for bi-monthly insurance.

## When to exercise the insurance

Once the pay-off reaches 1000% of yearly spent for insurance, we should exercise the option to use the insurance.For the given case, 306.8 X 10, `3068` should be the cut-off for exercising the option.
