---
title: "തേയ്മാനം തടയാം"
format: html
editor: visual
order: 1
---

കാൽമുട്ട് തേയ്മാനം നമ്മുടെ നാട്ടിലെ ഒരു സർവസ്സാധാരണമായ രോഗമാണ്. യൂറോപ്യൻ രാജ്യങ്ങളിൽ പക്ഷേ ഇടുപ്പ് തേയ്മാനം ആണ് കൂടുതൽ. ഇതിന് ജീവിത ശൈലി ഒരു കാരണം ആയി കണക്കാക്കി വരുന്നു. ഇന്ത്യക്കാർ, പ്രത്യേകിച്ച് പഴയ തലമുറയിലെ മലയാളികൾ നിലത്ത് ചമ്രപടി ഇട്ട് ഇരുന്ന് ശീലിച്ചവർ ആണ്. കൂടാതെ ചില മതപരമായ ആചാരത്തിന്റെ ഭാഗമായും കാൽ മുട്ട് വളരെ അധികം വളയ്ക്കുന്നത് പതിവാണ്. ഇതു കാൽ മുട്ട് തേയ്മാനത്തിന് കാരണമാകാം. മറിച്ച് യൂറോപ്യന്മാർ കൂടുതൽ കസേര മുകളിൽ ഇരിക്കുന്നവർ ആയതുകൊണ്ട് അവരിൽ താരതമ്യേനെ കാൽമുട്ട് തേയ്മാനം കുറവാണ്.

കാൽമുട്ട് തേയ്മാനം മുട്ട് വേദന, ചലനക്ഷമത കുറവ് എന്നിവയ്ക്ക് കാരണമാകുന്നു. രോഗം പുരോഗമിക്കുമ്പോൾ, സാധാരണ പ്രവർത്തനങ്ങൾ പോലും ബുദ്ധിമുട്ടാകാം. എന്നാൽ, ശരിയായ മുൻകരുതലുകൾ സ്വീകരിച്ചാൽ രോഗം നിയന്ത്രിക്കാനും ജീവിത നിലവാരം മെച്ചപ്പെടുത്താനും കഴിയും.

### പ്രതിരോധം 

#### ഭാരം കുറയ്ക്കുക

അമിതഭാരം മുട്ടുതേയ്മാനത്തിന്റെ പ്രധാന കാരണങ്ങളിലൊന്നാണ്. 5% മുതൽ 10% വരെ ഭാരം കുറയ്ക്കുന്നത് മുട്ടിലെ സമ്മർദ്ദം കുറയ്ക്കുകയും അത് വഴി വേദന കുറഞ്ഞ് പ്രവർത്തനക്ഷമത മെച്ചപ്പെടുത്തുകയും ചെയ്യുന്നു. American College of Rheumatology (ACR)യും Arthritis Foundation-ഉം ഭാരം കുറയ്ക്കാൻ ശക്തമായി ശുപാർശ ചെയ്യുന്നു. ഇത് പ്രത്യേകിച്ച് അമിതഭാരമുള്ളവർക്ക് വളരെ അധികം സഹായം ചെയ്യും. [അമിത വണ്ണം എങ്ങിനെ നിയന്ത്രിക്കാം?](https://www.knotes.co.in/patient%20education/കാൽമുട്ട്%20തേയ്മാനം/weight)

#### വ്യായാമം

സ്ഥിരമായ വ്യായാമം (നടത്തം, ബലൻസ് വർധിപ്പിക്കുന്ന വ്യായാമങ്ങൾ (യോഗ, തായ് ചീ) എന്നിവ മുട്ട് വേദന കുറയ്ക്കുകയും പ്രവർത്തനക്ഷമത മെച്ചപ്പെടുത്തുകയും ചെയ്യുന്നു. ഈ വ്യായാമങ്ങൾ രോഗം കൂടുതൽ മോശമാകാൻ കാരണമാകില്ല. ദീർഘസമയം ഇരുന്ന് കഴിച്ചുകൂട്ടുന്നത് ഒഴിവാക്കുക, പ്രവൃത്തികളിൽ വ്യാപരിക്കുക.

#### രോഗത്തെ കുറിച്ച് അറിവ് നേടുക

Knowledge is power എന്ന് ആംഗലേയത്തിൽ ഒരു ചൊല്ലുണ്ട്. അറിവ് ആത്മവിശ്വാസം വർദ്ധിപ്പിക്കുകയും രോഗത്തെ നേരിടാൻ മാനസികമായും ശാരീരികമായും നമ്മെ പ്രാപ്തരാക്കുകയും ചെയ്യുന്നു. രോഗത്തിന്റെ സ്വഭാവം, ലക്ഷണങ്ങൾ, പുരോഗതി, ചികിത്സാ മാർഗങ്ങൾ എന്നിവയെക്കുറിച്ച് വ്യക്തമായ അറിവ് രോഗി നേടാൻ ശ്രമിക്കണം. പോസിറ്റീവ് ചിന്ത, വ്യായാമം, ഭക്ഷണ നിയന്ത്രണം എന്നിവ വേദന കുറയ്ക്കാൻ തീർച്ചയായും സഹായിക്കും.
