---
title: "അമിതവണ്ണം "
format: html
editor: visual
---

## എങ്ങിനെ നിയന്ത്രിക്കാം

മുട്ടുവേദനക്ക് ചികിത്സ തേടി വരുന്ന ഭൂരിപക്ഷം രോഗികളും അമിതവണ്ണം ഉള്ളവർ ആണ്. അവരോട് വണ്ണം കുറക്കേണ്ടതിന്റെ ആവശ്യകതയേ പറ്റി പറഞ്ഞാൽ പൊതുവേ ലഭിക്കുന്ന മറുപടി ഇതെല്ലാമാണ്:

-   ഞാൻ ഭക്ഷണം ഒന്നും കഴിക്കുന്നില്ല. എങ്ങിനെയാണ് തടി വക്കുന്നത് എന്ന് അറിയില്ല. ഗുളികകളുടെ സൈഡ് ഇഫക്ട് ആവുമോ ഡോക്ടറെ?

-   എന്റെ തടി പാരമ്പര്യം ആണ് ഡോക്ടർ. അത് കുറയില്ല.

-   എനിക്ക് തടി കുറക്കാൻ നല്ല ആഗ്രഹം ഉണ്ട്. ഡോക്ടർ ഒന്ന് പറഞ്ഞു താ.

-   ഒരു മുട്ടിനല്ലേ വേദന ഉള്ളൂ. തടികൊണ്ടാണ് എങ്കിൽ രണ്ടിനും വരണ്ടേ?

വളരെ ചുരുക്കം ആളുകൾ തുറന്നു സമ്മതിക്കുന്ന രണ്ട് കാര്യങ്ങൾ ഉണ്ട്.

1.  എനിക്ക് മധുരം ഒരു വീക്നസ് ആണ്.

2.  ഞാൻ ചോറ് അധികം കഴിക്കും.

തടി നിയന്ത്രിക്കാൻ രണ്ടേ രണ്ട് മാർഗ്ഗങ്ങളെ ഉള്ളൂ.

1.  ഭക്ഷണ നിയന്ത്രണം.

2.  വ്യായാമം.

## ഭക്ഷണ നിയന്ത്രണം

{{< video https://youtu.be/BEjD9JBkYAY?si=AYBAHYqd1aNL2B24 >}}

ഒന്ന് രണ്ട് തലമുറ മുമ്പ് വരെ നമ്മുടെ നാട്ടിൽ പട്ടിണി സർവ സാധാരണം ആയിരുന്നു. പഴയ കാല കേരള കാഴ്ചകൾ എന്ന് പറഞ്ഞു യൂട്യൂബിൽ തിരഞ്ഞാൽ ഇതു നമുക്ക് ബോദ്ധ്യപ്പെടും. ആർക്കും കുടവയർ ഇല്ല! ആ പട്ടിണി കാലം ഒക്കെ പോയി. ഇന്ന് കേരളത്തിൽ സ്വബോധം ഉള്ള ആരും പട്ടിണി കിടക്കേണ്ട കാര്യം ഇല്ല. തന്നെയുമല്ല, തുടുത്ത കവിളും ഒരു കുടവയറും ഇല്ല എങ്കിൽ ആളുകൾ വീട്ടിൽ എന്തെങ്കിലും പ്രശ്നം ആണോ എന്ന മട്ടിൽ പെരുമാറും. മലയാളികൾ ദിവസം മുഴുവൻ ഭക്ഷണം കഴിക്കുന്നവർ ആയി മാറി. ആദ്യമേ പറയട്ടെ; ഭക്ഷണം വയറു നിറച്ച് കഴിക്കാനുള്ളതല്ല. തുടർച്ചയായ അമിത അളവിലുള്ള ഭക്ഷണം താങ്ങാനുള്ള ശേഷി മനുഷ്യ ശരീരത്തിനില്ല. കാട്ടിൽ ഭക്ഷണം തേടി അലഞ്ഞ നായാടികളിൽനിന്ന് നമ്മിലേക്ക് ജനിതികമായി അധിക ദൂരം ഇല്ല. അമിത അളവിൽ ലഭിക്കുന്ന ഭക്ഷണം എന്ത് ചെയ്യണം എന്ന് നമ്മുടെ ശരീരം പഠിച്ചു വരുന്നെഉള്ളൂ. ഇത് അമിത വണ്ണത്തിലേക്കും ജീവിത ശൈലി രോഗങ്ങളായ പ്രമേഹം, ഹൈപ്പർടെൻഷൻ, കൊളസ്റ്ററോൾ, ഫാറ്റി ലിവർ, തൈറോയിഡ് രോഗങ്ങൾ, മുട്ടുതേയ്മാനം, നടുവേദന എന്നിവയിലേക്കും നയിക്കും.

## ഞാൻ അമിതമായി ഭക്ഷണം കഴിക്കുന്നുണ്ടെന്ന് എങ്ങിനെ അറിയാം?

നിങ്ങൾക്ക് അമിതവണ്ണം ഉണ്ടെങ്കിൽ നിങ്ങൾ അമിതമായ അളവിൽ ഭക്ഷണം കഴിക്കുന്നുണ്ട്; കേൾക്കാൻ ഇഷ്ടമാവില്ല എങ്കിലും ഇതാണ് സത്യം. സംശയം ഉള്ളവർ ആദ്യം ചെയ്യേണ്ടത് ഒരു നോട്ട് പുസ്തകത്തിൽ **അന്നന്ന് കഴിക്കുന്ന എല്ലാ ഭക്ഷണത്തിന്റെയും പേരും അളവും സമയവും കുറിച്ച് വയ്ക്കുക** എന്നതാണ്. നിങ്ങളോട് ശമ്പളം കിട്ടുന്ന ഒരു വ്യക്തി ഇങ്ങനെ പറഞ്ഞു എന്ന് കരുതുക: “ എനിക്ക് ഒന്നാം തീയതി ശമ്പളം കിട്ടും. ഞാൻ പൈസ ഒന്നും ചിലവാക്കില്ല. പക്ഷേ പതിനഞ്ചാം തിയതി ആവുമ്പോളേക്കും കയ്യിൽ പത്ത് പൈസ കാണില്ല. എന്താണ് കാരണം എന്ന് അറിയില്ല!” നിങ്ങൾ എന്ത് പറയും? കണക്കിൽ എന്തോ തെറ്റുണ്ട്. ഒരു കാര്യം ചെയ്യൂ, വരവ് ചിലവ് കണക്ക് എഴുതി വയ്ക്കു. അല്ലേ? അത്രയെ ഉള്ളൂ. ഒരു നോട്ടു പുസ്തകത്തിൽ എഴുതി വയ്ക്കുമ്പോൾ തന്നെ തടി കുറയാൻ തുടങ്ങും!!

### പിന്നെ എന്തൊക്കെ ചെയ്യണം?

ഈ ചോദ്യത്തിൽ ചെറിയ ഒരു തെറ്റുണ്ട്. നമ്മൾ ചോദിക്കേണ്ടത് എന്തൊക്കെ ചെയ്യണം എന്നല്ല, മറിച്ച് എന്തൊക്കെ ചെയ്യാതിരിക്കണം എന്നാണ്. ഇതിനെ “വയ നെഗറ്റീവ” എന്ന് പറയും.

-   പുകവലി, മദ്യപാനം, മുറുക്കൽ തുടങ്ങിയ ദുശ്ശീലങ്ങൾ നിർത്തുക.

-   വീട്ടിൽ പഞ്ചസാര, ശർക്കര, കൽക്കണ്ടം എന്നിവ വാങ്ങുന്നത് നിർത്തുക.

-   ബേക്കറി ഐറ്റംസ് ഒന്നും വാങ്ങാതിരിക്കുക.

-   എണ്ണയിൽ വറുത്ത ഭക്ഷണങ്ങൾ ഒഴിവാക്കുക.

-   ജങ്ക് ഫുഡ്, പ്രോസസ്ഡ് ഫുഡ് എന്നിവ ഒഴിവാക്കുക.

-   പാക്കേജ് ജ്യൂസ് കുടിക്കുന്നത് ഒഴിവാക്കുക.

-   ഭൂമിയുടെ അടിയിൽ ഉണ്ടാവുന്ന എല്ലാ വസ്തുക്കളും വർജിക്കുക.

-   രാത്രി ഭക്ഷണം കഴിച്ച ശേഷം 12 മണിക്കൂർ ഒന്നും കഴിക്കാതിരിക്കുക ( 12 hr ഫാസ്റ്റിംഗ്). ഇതു പ്രാവർത്തികം ആകണം എങ്കിൽ രാത്രി നേരത്തെ കഴിക്കണം.

-   വീട്ടിലെ കലണ്ടർ നോക്കി ഫാസ്റ്റിംഗ് ചെയ്യേണ്ട വിശേഷപ്പെട്ട ദിവസങ്ങൾ കണ്ടുപിടിച്ച് നോമ്പ് നോക്കുക.

ഇത്രയും ചെയ്താൽ ഒരു നല്ല തുടക്കം ആയി എന്ന് പറയാം. പറയാൻ എളുപ്പം ആണെങ്കിലും ഇവയിൽ ഓരോന്നും നടപ്പാക്കാൻ പലർക്കും അധികഠിനമായ പ്രയത്നം ആവശ്യമായി വന്നേക്കാം.

### പോഷകമുള്ള ഭക്ഷണം തിരഞ്ഞെടുക്കുക

നമ്മുടെ ഭക്ഷണ ശീലത്തിലെ മറ്റൊരു പോരായ്മ പ്രോട്ടീൻ കുറവാണ് എന്നതാണ്. മുട്ട, മത്സ്യം, മാംസം, കടല, പയറ്, മുതിര, സോയാബീൻ തുടങ്ങിയവയിൽ ഏതെങ്കിലും ഒക്കെ ആഴ്ചയിൽ 2-3 ദിവസമെങ്കിലും കഴിക്കുന്നുണ്ട് എന്ന് ഉറപ്പ് വരുത്തുക.

ഗ്ലൈസമിക് ഇൻഡെക്സ് കുറവുള്ള ചുവന്ന തവിട്ടുള്ള അരി, റാഗി, മറ്റു മില്ലറ്റ് വർഗങ്ങൾ ഉപയോഗിക്കുക. പക്ഷേ ഊണ് കഴിച്ചു എന്ന് പറയുന്നതിന് പകരം പച്ചകറിയും ഇലവർഗങ്ങളും പഴങ്ങളും മറ്റും കഴിച്ചെന്നും കൂടെ കുറച്ച് ചോറ് ഉണ്ടു എന്നും പറയത്തക്ക രീതിയിൽ വേണം കഴിക്കാൻ.

നമ്മൾ ഒഴിവാക്കിയ ഭക്ഷണങ്ങളിൽ നിന്നും മിച്ചം വച്ച പണം കൊണ്ട് കഴിയുമെങ്കിൽ വാൾനട്ട്, ബദാം മെയ്ത്തി സിഡ്സ് തുടങ്ങിയവ വാങ്ങി കുറച്ച് എല്ലാ ദിവസവും കഴിക്കുക.

വ്യായാമത്തെ കുറിച്ച് പിന്നീടൊരിക്കൽ പറയാം. എല്ലാം കൂടി ഒന്നിച്ച് തുടങ്ങാൻ പറ്റണമെന്നില്ലാലോ !!
