---
title: "books"
date: 7/19/2019
---

## Book review

### Introduction

::: {.callout-tip}
## Statistics

We have the entire Orthopaedic knowledge available on-line through the wonderful platform of Orthobullets . We have got standard textbooks like Campbell's Operative Orthopaedics, Apley's system of Orthopaedics and Fractures and many more. Our teachers are excellent and they teach their experience in orthopaedics passionately. However, the overall pass percentage(starting from 2009) for Part 1 is around 68% and for the Part 2 it is a little below 60%.
:::

Theoretically, after forking out more than £2ooo, the possibility of yourself passing both parts in a single attempt is around 40%. This is even lower for International examination. 

`Why it is so? There could be many potential reasons.`

Here we will try to stick on to only the critical decision of choosing the study materials in the form of textbooks or on-line resources. The choice of study material is down to individual preference. Some prefer textbooks while others choose to use websites. Two of my friends claim to pass the Part 1 after studying only Orthobullets question. This could be entirely possible, but I cannot understand how. Hence I here-by label them as outliers!

Like anything else in life, choosing the right resource at the right time is critical, if you want to pass an examination like FRCS(Tr&Orth). It is considered a very difficult examination, where the candidates are tested for the **knowledge** and **understanding** of a wide range of orthopaedic problems. Reading "standard" textbooks and journals may not be enough for passing the examination. The most commonly mentioned prerequisites are **higher order thinking** , **communication skill** and **confidence**. Here I would like to review some of the outstanding books and online resources which could be a potential resource(s) for your success.

### Useful websites

#### Part 1

### www.orthobullets.com

Orthobullet's questions are the first possible starting point for anybody who wants to assess oneself. It will also help you to get into the groove. At this point temptation to memorize the entire Orthobullets by heart is a real risk, which I believe, is better to resist. Orthobullets provide explanations at the end of each of the questions, stick on to that. and you can also monitor your progress easily, and that too for free. Though American in origin, most of the topics on which questions are created seem relevant to British exam.

### www.onexamination.com

If you should attempt Orthbullets in the beginning of your preparation, then there is another little secret. Go through the [onexamination](https://www.onexamination.com/products/fcrs-trauma-orthopaedic?_pos=2&_sid=f4ce17103&_ss=r) questions at the end of your preparation. Along with the paid questions of Orthobullets, this little gem will give you some extra edge on that day.

### Part 2

[frcsortho](www.frcsortho.com)

The previous candidate experience given in the website could be a refresher for those who have successfully completed the Part 1 and not yet started serious Part 2 preparation.Whether one should register for the paid questions is doubtful. I coughed up £200 and feel like I have wasted that money, considering the poor quality and seemingly unreliable information given for that hefty sum.Even they have failed to make the website https secured.

**YouTube channels**:I wont be repeating what I have discussed

## Recommended Text books

From a plethora of expensive Orthopaedic textbooks of varying size, shape and quality, it is difficult to select a perfect book or two. **It is better to acknowledge the fact that the nature of the exam is diverse and there is no quick and easy remedy.**

### Miller's Review of Orthopaedics 7^th^ edition.

Coming with a punchy tag line, *go-to certification and recertification review guide for every orthopaedic resident, fellow, and surgeon*, this book divides people in to two-**Those who believe in Miller's review and those who do not!** It's strong point is compactness and intensiveness; same is its weakness. It's basic science, Arthroplasty and Statistics chapters are industry standard. I cleared the Part 1 **studying** mainly(95%) Miller and Orthobullet question bank. If allowed to grade as per FRCS Part 2 marking system, I will give 7/8 for this book when used for **Part 1**. Its usefulness for Part 2 as an exclusive guide is at the best doubtful. I cannot comment on the more recent 8\^th edition.

### Postgraduate Orthopaedics, the candidate's guide and Viva guide

Selection of Part 2 book is relatively simpler. This book series stands apart. I doubt whether you can pass the Part 2 without going through these 2 books. Apart from the top class content, they drill in **higher order thinking** and caters to even more advanced students of orthopaedics. It is impossible to grade this book. **Prof. Paul Banaszkiewicz has done a work of genius.**

### Do you have any proof?

Let's try to learn a topic from these two books: **Funnel plot**

**Miller's Review 7^th^ edition**: The topic is not covered.

#### Postgraduate Orthopaedics:

Both Candidate's guide and the viva guide beautifully discusses the funnel plot. Let me quote a few lines from them.

##### Candidates guide

> "Funnel plots are used to compare outcomes in groups of different sizes. It was seen in the section on SEM that with increasing sample size the SEM approaches zero; where this does not occur it is likely that some effect is being observed. This can be used to detect ‘ outliers ’\*

> In outcome studies, such as when comparing mortality rates for different surgical centres or surgeons **Inverted funnel plots can be used to detect publication bias**; the SEM should be larger for studies with smaller sample sizes – If it is not this may indicate publication bias. ..........; if there is an effect of the intervention there will be a shift of the data points to the left but there should still be a greater scatter of results for the studies with a larger SEM. The plot on the left shows no such increase in scatter with increasing SEM, suggesting publication bias(two funnel plots are shown)"

##### Viva Guide

> "This is called a funnel plot which is a simple scatterplot of the treatment effects (RR) estimated from individual studies (horizontal axis) against the precision of the studies represented by standard error (SE). The vertical dotted line shows the estimated combined RR from the meta-analysis. The diagonal dotted lines show the range in which studies might be distributed by chance given the size (and thus precision) of each study. Thus larger (big sample size), more precise (smaller standard error) studies should be closely distributed either side of the pooled effect and smaller studies should be distributed more widely giving the classic inverted symmetrical funnel. If the studies are not distributed randomly (due to sampling error) around the combined RR estimate then some other influence is suggested. The funnel plot shows trials scattered asymmetrically around the pooled RR with smaller trials reporting a greater effect than larger ones. Two possible explanations are: smaller trials of lower methodological quality tend to overestimate true effect; publication bias has led to the smaller negative trials remaining unpublished." You would appreciate the difference the moment you read a lesser book.

##### Concise Orthopaedic notes

Recently Firas Arnaout of FRCS Mentor group contacted me and suggested me to read his recently revised book, **Concise Orthopaedic Notes** . He kindly gave me free assess to the digital version. I thank him for the gesture, even though, as a kindle unlimited member, I had already rented and read some chapters of his book before. Authors believe that they have covered the depth and width of knowledge and skills required for the exam and challenge anyone to find an FRCS question that has not been included in the book. This book is a welcome edition and with some hard work, it can even compete with Miller's review to some extent, *for **Part 1**.*

Let's see what does the book tell us about funnel plot.

-   "Performance measuring tool used to measure variations in performance between surgeons and/or centres and identify outliers (Above red line)
-   They are scatter plots, with superimposed control limits (typically 2 SD, 3 SD or 4 SD)
-   Shows 90-day mortality following hip surgery
-   Surgeon/hospital highlighted as orange triangle
-   The smaller the size of the sample, the wider the control limits (increased variability).
-   As the sample increases the certainty increases and the ‘funnel’ is formed.
-   Progression along horizontal axis means that surgeon/hospital done more cases
-   Data within the control limits (between the dotted lines) are consistent with common cause variation or natural variation, whereas those outside these limits indicate unexpected good or bad results (outliers)
-   For mortality, it means they done higher risk patients
-   Can’t identify someone doing very few cases (towards left side of graph) as outlier.
-   Progression along vertical axis means surgeon/hospital have had more of the end point (revision or death) deaths.
-   Vertical axis figures presented as standardized ratio.
-   For mortality - data adjusted to take account of surgeons who operate on more higher-risk or lower-risk patients.
-   Surgeons on central (green) horizontal line have had exactly average expected mortality.
-   Surgeons either side of green line but below upper red line have level of mortality that is within expected range.
-   Surgeons that appear above top red line have mortality rate higher than expected. This is followed by a picture of funnel plot."

**After reading this I am more confused than confident**

## Adjutants

1.  **FRCS Tr & Orth Exam- A guide to clinical and viva by Mansoor Kassim**\
    A straightforward, precise and short guide which is a delight to read. Excellent for Part 2.

2.  **Examination technique in Orthopaedics** Harris and Ali's is **the** clinical examination guide for FRCS(Tr&Orth), period

3.  **Practice of Paediatric Orthopaedics by Lynn T. Staheli** This book is a delight to read. After passing the exam, I am still reading it very often. Short, precise and insightful.

4.  **Orthopaedic surgical approaches by Mark D. Miller** While the anatomic approach Hoppenfeld is the standard textbook for studying exposures, this book is refreshingly new.

5.  **Orthopaedic notes by Joideep Phadnis** If you dig enough in the World Wide Web, you will get this book for free. The pictures are first class and the notes are extensive.

6.  **Basic Orthopaedic Sciences by Manoj Ramachandran** No comments.

7.  **Netter's Concise Orthopaedic Anatomy by Jon C Thompson** Small book, concise and useful to some extend

## Conclusions

-   There is no single book/resource that can guarantee a pass for you.
-   Select your 'jab' early and take the full dose.
-   **Revision is the key. Hence, grab the information from reliable resources, understand it and make your own notes , especially after Part 1**
