---
title: "FRCS application"
---

Here I'll share my personal experience and tips for FRCS (Tr & Orth) application and preparation:

## Application

**Evolution of Orthopaedic training examination in UK**

> -   The old-style FRCS: Until late 1970s.
>
> -   MCh(Orth) from the University of Liverpool: Now obsolete
>
> -   OPTIONAL Specialty Fellowship exam in orthopaedics in 1979.
>
> -   A new intercollegiate exam was introduced in 1990, which was accepted by all four Royal Colleges.
>
> -   In 1991 FRCS became a requirement for accreditation.
>
> -   The four Surgical Royal Colleges (Edinburgh, England, Glasgow & Ireland) in 2015 introduced a new suite of Intercollegiate Fellowship Examinations for the international surgical community.
>
> -   The JSCFE has parity of standard with the existing UK/Ireland Intercollegiate Fellowship. Examinations and is recognised by GMC for Speciality registration.

### Examination Pattern

The current International FRCS (Tr & Orth) exam encompasses two sections: Part I is a written exam and Part II the clinical and oral exam. For further information, and to make sure that your information is up to date, I suggest that you carefully review the Intercollegiate Speciality Board website.[This is the link](https://www.jscfe.co.uk/Content/content.aspx).

##### Part I

This section consists of two separate papers ( a Computer Based Testing-CBT); essentially, a multiple-choice question (MCQ) paper (2 Hours) and an extended matching question (EMQ) paper (2 hours 30 minutes). Part I is generally regarded as the easier section of exam to pass. A number of candidates may be OK learning for an MCQ/EMI paper but be a long way off the standard for a clinical and viva exam.

Format of Section 1 examination changes from 2021

The GMC has approved an alteration to the format of the Section 1 examination. The following format is applicable to all Section 1 examinations from January 2021:

Paper 1 – 120 Single Best \[SBA\] (2 hours 15 mins)

Paper 2 – 120 Single Best \[SBA\] (2 hours 15 mins)

### How to apply

<https://www.jscfe.co.uk> is the official website for registering and applying for the examination. It costs £520.00 for Part I application and £1,785.00 for Part II. To apply,

> -   Applicants must be six years medically qualified
>
> -   Applicants would normally have passed the MRCS examination of one ofthe four Surgical Royal Colleges but this is currently not mandatory
>
> -   Applicants must have successfully completed a locally recognised surgical training programme and are required to provide evidence of having achieved the required standard of a recognised specialist (day one NHS UK/Ireland consultant standard) in the generality of Trauma and Orthopaedic Surgery
>
> -   This evidence must consist of three structured references as follows:
>
> -   The principal referee must be the applicant’s current of Head of Department or Head of the Recognised Training Committee/Programme in which the applicant has participated.
>
> -   The second referee must be a senior clinician who has worked with the applicant and has knowledge of the applicant’s work in his/her specialty within the last two years
>
> -   The third referee must be a senior clinician who has worked with the applicant and has knowledge of the applicant’s work in his/her specialty within the last two years
>
> -   The final decision on eligibility for admission to the examination will lie with the Joint Surgical Colleges Fellowship Examination Specialty Board in Trauma and Orthopaedic Surgery
>
> -   Examination Attempts:\
>     Candidates will have up to a maximum of 7 years to complete the examination process as follows:\
>     **Section 1**:Candidates will have a maximum of 4 attempts with no re-entry\
>     **Section 2**:Candidates will have a maximum of 4 attempts with no re-entry
