---
title: "Part 2 FRCS"
---

## Preparing for Part II

### New Changes upto July 2022

Section 2 is the clinical component consisting of a series of carefully designed and structured scenario-based interviews. The Section 2 examinations will be held in pre-selected world-wide host centres.

### Clinical examinations

Clinical Intermediate Case (1 case will be discussed in 20 minutes) Clinical Short Cases (4 cases will be discussed in 20 minutes)

No patients will be present. Clinical Scenarios are used for each Case.

During the 3 weeks waiting period, I made some internet search and made a tentative plan for Part II preparation, in case I could clear the exam. I was equally thinking about mentally preparing myself to resit the Part I ( Though I had no clue about alternative preparation method or my ability to stretch beyond the limits of my initial preparation). It later turned out to be good 1 year gap for the preparation.My plan for Part II can be summarised as below.

1.  Attend preparatory course

2.  Buy clinical and viva study materials

3.  Take classes for residents

4.  Standardise the clinical examination method See as much patients as I can

5.  Make notes for quick revision

6.  Combined study

### Preparatory course(s)

I stumbled upon and intuitively selected two courses, which turned out to be real gems in due course,

##### Postgraduate Orthopaedics Revision course by Postgraduate Orthopaedics

##### The FRCS Mentor Network (Offline youtube videos)

##### Postgraduate Orthopaedics Revision course by Paul Banaszkiewicz

This is an intense 6 day course covering all the A list/core topics for Part II. I attended the course twice. One in the very beginning of the Part II preparation and another at the end of my preparation to “iron out my technique”, just before exam. The course helped in two fronts; first it helped me to develop a systems approach and secondly it grilled in the concept of **“Higher order thinking”**.

##### The FRCS Mentor Network (Offline youtube videos)

Shwan and Firas Arnaout are doing wonderful work in preparing candidates through online group. I regularly listened to their youtube uploads, and believe that this really helped me in developing confidence and foresee the real clinical and viva stations. FRCS mentor group some how introduced me to another gem, videos by Quen Tang.

##### Quen Tang videos

This introduced me to two important concepts

-   Structured answering in viva using A4 sheet of paper and pencil

-   Sleek and crisp presentation

### Clinical and viva study material

I stuck to these

-   Postgraduate Orthopaedics: The Candidate’s Guide to the FRCS (Tr & Orth) Examination

-   Postgraduate Orthopaedics: Viva Guide for the FRCS (Tr & Orth) Examination

-   Examination Techniques in Orthopaedics by Nick Harris, Fazal Ali

-   Pictures from revision notes by Joideep Phadnis

-   Pictures from Atlas of human anatomy

### Combined study

During the last 2-3 mo nths of preparation, I utilised Zoom application for discussions with my friend Praveen C R.

### The Clinical and viva

As usual I reached well in advance before the exam, in fact 2 days earlier. I stayed in the same hotel where viva was supposed to be conducted. Unfortunately, I developed allergic rhinitis and was really worried.

### Clinicals, Day 1

I felt quite distracted by the rhinitis and the fellow candidates, with lot of speculative discussions in the air both in the hotel and in the exam hall. I tried not to get carried away and keep focused. I had the short cases first and had to be really on my toes and time fled like anything. My performance was pretty average or possibly bad in 2 stations. Luckily the rhinitis did not come in the way.I tried to forget those stations and tried to focus myself before the intermediate case, sitting away from fellow noisy candidates. I practiced structured history taking by writing down individual questions for standard patient interrogation. In the intermediate case station (PLIF patient with foot drop), I felt more confident and was able to control the situation to a large extend.

### Viva, Day 2

Viva was in the morning, but I had lot of time with out any distraction before that. I could revise my entire notes before viva. I could remain focused. Only problem was dry cough, which I tried to ignore. All the questions were familiar to me and I controlled the discussion to a great extend except in the basic science station. There I performed rather poorly, but my overall performance was good.

### Dress code

Of course there is no dress code for Part I. For the clinicals, the principle is to be bare below the elbow. Tie is not mandatory. But I preferred to wear one with the end tucked into the Light blue shirt. I wore dark blue trousers and black formal shoes. You are expected to wear a suit for the viva. I wore a dark blue one and a white shirt. The board expects you and only you for the examination. This means no need to carry any examination kit.

### Result

Result came as an email from the CHAIR, JSCFE SPECIALTY BOARD IN TRAUMA & ORTHOPAEDIC SURGERY exactly 10 days after the examination. The email just informed me that I have been successful.
