---
title: "questions"
---
# **FELLOWSHIP QUESTIONS**

## SBA/EMQ

-   Supracondylar fracture 4 seconds cap filling , full stomach.

-   Supracondylar fracture not able to flex index finger.

-   Supracondylar fracture, compartment syndrome , structure involved: brachial artery

-   Lateral condyle pinning open, not able to give bye bye 7 year old

-   Green colour to cement: chlorophyll

-   Prevent cement polymerisation

-   Proximal stimulation motor ganglia: f wave

-   Muscle fibrillation: COMP

-   DELAY across elbow: latency

-   Ultrasound

-   Push-up is what type of exercise

-   Lengthening followed by contraction

-   Muscle fibre in Achilles tendon

-   Irregularly arranged 1 and 2 collagen seen in

-   Multifascicular with vascular supply and type 4 collagen

-   Finger drop with wrist in flexion and radial deviation

-   Structure retracted to see cervical vertebrae anterior

-   Structure torn and retracted inferiority in c spine anterior sx

-   Structure damaged above c3 anterior sx

-   Anterior knee pain TKA normal Xray, Cause

-   Instabily CR TKA, on climbing staircase

-   20 degree extension lag after resurfacing

-   Pelvic metastasis not responding to rt

-   Wide excision and prosthetic replacement done in : thyroid, TX, breast, humerus, trochanter, greater trochanter, lesser trochanter

-   Damage control Orthopaedics, marker: 1l 6

-   Candilever failure cause:

-   Charnley hip failure, M/C in :OA, RA, tip medial or lateral

-   No wear after 10 years THA

-   Not good in females THA

-   Moderate wear with ductility THA

-   DEXA true

-   Differentiate cortical and trabicular osteoporosis

-   Attach with sharpy fibers

-   Resusitated , better then hypotension fluid under diaphragm, pelvic binder: 2 more crystalloid or abdl CT or laparotomy

-   Hammer toe with stiffness

-   Mallet finger

-   Flexible claw toes treatment

-   Abducor hallusis weakness nerve

-   Plane for mid tibia posterior

-   Proximal fibula plane

-   Originate from mid fibula

-   Transverse arch maintained by

-   Structure accompanied by sciatic nerve

-   Variably present in ilioinguinal approach

-   Plane between TFL and gluteal medius

-   Splitting gluteus medius approach

-   ASA 3 70 shopping neck of femur fraCture treatment

-   Gustello periosteal stripping no flap

-   Scaphoid 6 week conservative , ballotment and pain after that what to do

-   Rheumatoid cannot flex thumb

-   Rheumatoid caput ulae

-   Spiral fracture humerus radial nerve palsy treatment

-   Structure damaged in dislocation young

-   Subtalar evasion and tibia IR in

-   Eccentric contraction to prevent lateral lurch

-   Muscle that concentrically contracture to extend hip

-   Eccentrically contracting muscle stance phase

-   X-ray showing navicular osteonecrosis : treatment

-   Photo extensor muscle wasting thumb

-   Photo 30 degree abd muscle testing

-   Radial head dislocated congenital, treatment

-   Picture showing cervical myelopathy with loss of lordosis treatment

-   Buford complex

-   Buford complex ligament

-   Ligament preventing inferior translation neutral addiction

-   TSA anterior dislocation cause

-   Vessel damaged in carpal tunnel release

-   Zone 2 injury little finger fdp lost no tenodesis sign for fds

-   Flexar tenosynovitis

-   Click on getting up from chair rugby player elbow

-   Proximal femur fraCture deformity

-   Most common cause intoeing gait 10 year old

-   Change made in the departmental study: audit

-   Rails in CVA patient house, type of study: cross sectional

-   Reamed vs unreamed: RCT

-   Post op blood transfusion m/c cause

-   2 years after scaphoid no arthritis treatment

-   Trapezectomy in rheumatoid

-   Plexus upper

-   TOS in adult

-   Gamella superior nerve supply

-   Gait muscles

-   Sacroiliac joint nerve involved

-   Dial test

-   High tibia osteotomy in varus knee

-   CP patient with pain no power head out GMFCS CLASS

-   Subtrochanteric fracture failure cause

-   P value

-   Mean and standard deviation

-   Triplane fracture treatment

-   7 year old lamping investigation

-   Double size , torsion strength pin

-   Double size bending strength plate

-   Plane volar Henry

-   Clinicals

-   Short cases

-   High ulnar nerve palsy with elbow FFD

-   Short lady with polyarthritis, neck stiffness and deformities

-   Soft tissue swelling ankle

-   Young OA knee, Opposite side with scar of HTO

-   Intermediate

-   Old gentleman with neurogenic claudication, scar of PLIFF, foot drop

## Viva

### **Basic science**

Infection control in ward

Knee Anatomy (atlas picture)

Chondrosarcoma shoulder

Xxx

Xxx

xxx

### **Trauma**

Lisfranc

Epiphyseal injury Distal Femur

Leg compartment

Facet joint dislocation

Xxx

xxx

### **Adult pathology**

DDH THA

Parsonage Turner Syndrome

Compartment syndrome

Xxx

Xxx

xxx

### **Paeds and Hand**

Supracondylar fracture

LLD

DDH

Boutonniere

Tendon repair

Xxx

