---
title: "PBL methodology"
---

### PBL tutorial process

Step 1—Identify and clarify unfamiliar terms presented in the scenario;
scribe lists those that remain unexplained after discussion

Step 2—Define the problem or problems to be discussed; students may
have different views on the issues, but all should be considered;
scribe records a list of agreed problems

Step 3—“Brainstorming” session to discuss the problem(s), suggesting
possible explanations on basis of prior knowledge; students draw
on each other’s knowledge and identify areas of incomplete
knowledge; scribe records all discussion

Step 4—Review steps 2 and 3 and arrange explanations into tentative
solutions; scribe organises the explanations and restructures if
necessary

Step 5—Formulate learning objectives; group reaches consensus on
the learning objectives; tutor ensures learning objectives are
focused, achievable, comprehensive, and appropriate

Step 6—Private study (all students gather information related to each
learning objective)

Step 7—Group shares results of private study (students identify their
learning resources and share their results); tutor checks learning
and may assess the group
