---
title: "Stoic Gukesh on top of the world"
subtitle: "You create your own luck"
order: 3
date: 12  december 2024
---

The 2024 World Chess Championship, officially titled the **World Chess Championship 2024 presented by Google**, featured an exciting showdown between reigning champion Ding Liren and challenger Gukesh Dommaraju to crown the next World Chess Champion. Held in Singapore from November 25 to December 12, 2024, the match followed a best-of-14-games format, with tiebreakers planned if needed. With an Indian trying to reach top of the world, I was absolutely captivated by the games and couldn’t take my eyes off the screen!

## Who is Gukesh?

Gukesh Dommaraju is a chess prodigy from Chennai, India.

Born to Dr. Rajinikanth Dommaraju, an ENT surgeon, and Padma, a microbiologist, Gukesh grew up in a middle class family that valued hard work and excellence. His parents recognized his talent early and made significant sacrifices to nurture his passion for chess. At one time, as Gukesh told after the press conference today, they even borrowed money to support him. Today, he stands as one of the brightest stars in the chess world. He led India to Olympic gold this year and became the youngest player ever to both challenge for and win the World Chess Championship.

Below is an interview of Gukesh years back when he was a kid. At age 11 this kid wanted to become the youngest world champion ever!!

{{< video https://youtu.be/9wdZScSNNTA?si=bzPKxsV9CYdbN5jp >}}

## Who is Ding?

Growing up in a modest home in Wenzhou, China, Ding Liren’s journey to becoming the World Chess Champion in 2023 was (again) deeply influenced by the unwavering support of his family. Despite their modest means, his parents—his father, who worked in a factory, and his mother, a homemaker—saw something special in their young son’s interest in chess. Recognizing his talent, they made countless sacrifices to provide him with the best possible opportunities.

His historic unbeaten streak of 100 games between 2017 and 2018 took him to above 2800 Elo rating, a milestone reached by only 14 players in the history of chess. In 2023, he became the World Chess Champion.

[Know more about Ding](https://en.chessbase.com/post/who-is-ding-liren)

## Final Game

<iframe width="740" height="471" src="https://lichess.org/study/embed/LF4x850G/HCFmWifD#0" frameborder="0">

</iframe>

Now you can see Gukesh crying out of joy, making every Indian proud 😂

{{< video https://youtu.be/sbPeUgTxRwE?si=gKDQZTq50yOmuh0n >}}

I was particularly impressed by Gukesh's attitude. He almost always appeared calm and composed under high-pressure situations, a demeanor that an alien like Magnus Carlsen might not enjoy. He always wanted to play, trying to create chances even with inferior positions. While pundits were giving him a .27% chance of winning, he played on. In that way, he created his own luck at one point and seized it with all hands. After the shocking win, although he almost completely broke down, he quickly regained his composure, stoically rearranged the chess pieces, thanked the chess set, and put the chair back in its position. This speaks volumes about this young talent. As Hikaru Nakamura said on his stream, Gukesh has just begun—there’s only upside to see in his future.

He didn’t forget to take a light jab at Magnus, the GOAT, during the press conference:

> ::: {style="color: red"}
> The title he took away from Chennai is taken back. Try to get it back!!! Who knows?
> :::
