---
title: "Journal"
draft: true
categories:
  - personal diary
---

### 📘 February 26, 2025

The stock market remains closed today. Since October 2024, the Nifty index has been gradually going down for five consecutive months. It has lost 15 points from the top, and nobody knows the reason. One school of thought is that this is natural profit-booking after a period of excessive upward movement. Others see it as a more structural problem, with growth slowing down and international trade becoming more autistic. From the low point of April 2020 (\~8000), the index had a phenomenal run to 26,300 with a CAGR of 28%.

An astute investor would have felt the alarm bells ringing at least twice: in the middle of 2021 and 2024, with the market entering overbought territory well above 70%. After the 2021 peak, with 72% overbought, it remained flat for the next 1 to 1.5 years. Once the market started touching below neutral, it started moving up until it reached 26300, with 83% oversold.

He would have moved all his accumulated equity to high-grade bonds or G-secs and waited for the exuberance to come down to near 50%, or at the very least, he would have bought some insurance against the downside. For his new savings, he would have continued to accumulate equity systematically, expecting prices to come down or stay flat for an extended period of time, buying all the way down to the bottom.

Now after this 15 point correction the market seems nearing neutral, close to 55%.

### 📘 February 27, 2025

The stock market is dead flat today.

Mr. P neither knew nor thought about any of the things we discussed yesterday. In mid-2021, he happily kept all his accumulated capital in equity and kept on buying new equity. Incidently, he found out that the full broker was charging 1% for all buys and sells. He sold all the holdings to start investing in a discount broker with 0% brokerage. By August 2024, all his capital was still in equity. Out of luck or contingency, he converted everything into G-sec bonds, only to see the market rise by 5 more points before eventually losing 15 points over the next 5-7 months. At the same time, he had purchased insurance against unexpected violent index movements in either direction and lost all the premium till date. He is also buying the index with new income systematically all the way from April 2023 and is still continuing.

When should he convert his bonds to equity? My initial thought is that it should be done when the market has bottomed out! But how can one know the bottom and top? For me, it is impossible to determine. I have a very low threshold for moving capital from equity to bonds—I may do so if exuberance exceeds 80%. The reverse is true when moving capital from bonds to equity. I should do so only after a significant draw-down of, say, 50%, with the market being oversold to 30% or below.

Mr P saw that NASDAQ and GOLD are in over bought territory and immediately sold them and bought LIQUIDBEES.

HANG SANG is around 60% over bought.He also felt that NATCO is trading at 50% and is in oversold territory. Company has got good reserves and he believes it is good time to build a position slowly. NMDC is also in his screen and started to build position slowly.

### 📘 February 28, 2025

\>2 point sell-off in NASDAQ and close to 2 point sell off in NIFTY. All stocks are down in similar proportions or more. It is interesting time. Trump is stirring the economic and geopolitical landscape on a daily basis. His tit for tat tariff plans are particularly interesting. Overall I believe that Trump is generally good for the world. Less people are getting killed at-least. I believe that tariffs breed inefficient industrialists and rob the consumers. This is especially true in case of India. I hope Trump will force us to reduce tariffs with a long term benefit of better industries, better quality products and lower costs.

### 📘 March 5, 2025

Monday and Tuesday the markets went down more than 2 points. Trump tariff of 25% targeting Canada and Mexico came to effect yesterday. China gets an additional 10%. Canada, Mexico and China constitute 50% of US trade. I believe it is an act of war and the ultimate loser will be the common man; Job loss, Inflation and falling value of investments. Plans to continue with NIFTY SIP.

### 📘 March 6, 2025

The market moved up around 1 point both yesterday and today. India is a high-tariff country. Any reciprocal tariffs imposed by Trump could lead to a reduction in Indian tariffs, benefiting consumers and innovators. Mr. P initiated a monthly SIP in NATCO and NMDC today, believing these are cheap and quality stocks. At the macro level, Trump's actions for the USA are akin to what Brexit has done to England. This presents opportunities for the rest of the world, and we know where England stands today economically.

### 📘 March 8, 2025

Yesterday market remained flat. NASDAQ has fallen around 5 points this month. Year till date it is by down around 4 points where as NIFTY is around 5 points down. HANGSENG has moved up 23 points!

### 📘 March 9, 2025

My past mistakes

1.  Took a loan to buy laptop and camera in 2005 while doing masters!! And that laptop was damaged beyond repair 1 year later during a lightning. I stopped repaying; until I got humiliating calls from the people concerned... Did not know anything about finance at that time.

2.  Took car loans (2008,2012) and personal loans (2009) soon after starting to earn. Personal loans were used to refurbish ansisteral house; probably had no other option at that time. 2008 car loan was a desperate decision but probably helped one of my uncles during great financial crisis. At least I should have avoided the second car loan in 2012.

3.  After 2013, Buying and sizing decisions was almost always appropriate for stocks. But, often sell decisions were imprecise and missed out big opportunities (especially with SJVN).

4.  Bought multiple expensive mobile phones every 3-4 years. In between one phone was stolen immediately after I bought it!!

5.  Bought expensive macbooks (3!) over a period of 12 years. Also multiple kindles(5), ipads(2), eink readers(2).

No more personal or car loans, no loans if possible.

No more iPads

No more kindles

No more expensive laptop/e reader unless necessary (broken).

Sizing and selling decisions to be improved

### 📘 March 13, 2025

Started OILIETF sip on Monday. Oil is down for some time now. Market remains uncertain, but despite NASDAQ falls, it remains sideways. What happens between Russians and Americans today and this week will set the future course for Europe and China. I personally believe that US need Russia and the Indo-Pacific by their side more than Europe at this point of time. Their main intend is to contain China than anything else now. I wont be surprised if US completely withdraw from NATO and Europe all together.
