---
title: "Science"
order: 1
---

::: callout-important
## Science

The process or means to change or to understand
:::

## Scientific discovery

The process of 'discoveries' have almost always been serendipitous. A keen observer explores various possibilities. He stumbles up on a solution, probably for an unknown problem. Later on the 'solution' starts attracting Certain 'problems'. eg:- discovery of penicillin.

As of today we have got no evidence to suggest that there is a physical or social truth out there. Discoveries of Science do not seem to take us towards any ultimate truth. The very foundation of science,i.e., **Falsification**, presupposes the absence of any ultimate truth. In that sense, as per science, the world we see today including us, is the by-product of a series of serendipitous shocks without any design or purpose or truth behind it.

## What is scientific understanding?

Scientific understanding can be considered as a systematic `over Simplification` of our beliefs, moving towards more comfortable ones from lesser ones. It is a kind of `platonification` exercise to improve our physical & mental well being .

This makes Science very similar to art & religion.

## Difference between science and religion

Only fundamental difference is the method of Science

i.e., **Falsification based on empirical scepticism.**

Art, religion etc. are totalitarian and dogmatic and requires lot of violence to bring about a change.

In science, when facts changes, Opinion changes. It thrives on the `unknown unknown`, always looking outside the given book.

*This does not mean, science will take me to '**a'** particular '**ultimate**' truth.*

## Limitation of science

A very important limitation of Scientific method is the very fact that it presupposes rationality of human mind & perception. While this could be true, we should be open to the idea that the whole process could be an illusion arising out of a confirmation bias.
