---
title: "Statistics"
order: 2
---

::: callout-note
## Definition

**Statistics** is the discipline that concerns the collection, organization, analysis, interpretation, and presentation of data. It literally mean "describe a state", originating from Latin word "Statistica"
:::

## Why Statistics?

Isn't it enough to to use logic or common sense ? Why should we use statistics at all?

Simplest answer is *we do not believe ourselves* because it is basic human instinct to validate facts which confirm to our believes and to invalidate those facts which contradict our believes- a confirmation bias. It is an essential trait for survival.

Social and cultural evolution is lot more faster in pace and larger in scale when compared to natural evolution. Hence, lot of our instincts are not so developed to process the socio-cultural observations accurately and precisely.

Statistics is the tool we should use when dealing with data. It is no more or no less than a tool. It is not a substitute for logical thinking. In fact it should instigate us to ponder more and understand the meaning of the stuff around us in a new light.

