---
title: "Risk in investment"
---

## Barbell strategy

::: callout-tip
## Remember

`Fundamental principle is never to loose the capital.`

Hence the pay-off is more important than the probability of success.

It is always better to loose small amount of capital regularly for a potential huge pay-off following an extreme rare event than to gain small amount of income from capital regularly with a potential to loose a substantial amount of capital due to an extreme rare event (including run away inflation).

Any given investment has got a speculative component to it and there by returns in future are uncertain
:::

## Capital lose in equity

Assume a game of dice. It has got 6 sides. You are invited to play a game with following rules using a sum of ₹ 100.

| Number on the dice | Reward                |
|--------------------|-----------------------|
| 1                  | You loose 50 %        |
| 2                  | Your ₹ 100 become 105 |
| 3                  | Your ₹ 100 become 115 |
| 4                  | Your ₹ 100 become 120 |
| 5                  | Your ₹ 100 become 130 |
| 6                  | Your ₹ 100 become 95  |

Will you play the game?

If we calculate the probability of success, it is 2/3 or 67 %, if you play the game for 6 times. But it is naive to calculate like this.

### Geometric mean

We should calculate the geometric mean in such situations. It is `₹ 98.16`. If you play this game your capital will erode and if you go on playing, in the long run you will loose your ₹ 100.

Let us play a similar game with following pay-off:

| Number on the dice | Reward                |
|--------------------|-----------------------|
| 1                  | Your ₹ 100 become 120 |
| 2                  | Your ₹ 100 become 97  |
| 3                  | Your ₹ 100 become 97  |
| 4                  | Your ₹ 100 become 97  |
| 5                  | Your ₹ 100 become 97  |
| 6                  | Your ₹ 100 become 97  |

Will you play the game?

If we calculate the the probability of success, it is 1/6 or 17 %, and may assume it is not profitable to play the game. But it is naive to calculate like this.

### Geometric mean

We should calculate the geometric mean in such situations. It is `₹ 100.5`. If you play this game your capital will appreciate and if you go on playing, in the long run you will build wealth with your ₹ 100.

## Opportunity cost of secured debt

A corpus of ₹100 will grow to ₹1147 over 50 years if the interest is 5%. If the average inflation over the period is 6 %, that amount will be equivalent to ₹ 62 in today's money. `Forget about what happens if there is a hyper-inflation like scenario.`

### Equity investment

Pay-off of equity is highly variable and is associated with the risk of more than 15% draw-down at any point in time ( around $1/11$ odds, historically). Previous experience show that the negative draw-downs are larger than the + ones. There is $1/11$ odds of stumbling up on negative shock at any time.

::: callout-warning
## Problem

This means at any point, the accumulated Corpus can go down and the recovery will need huge returns after the event.
:::

### Secured debt investment

Pay-off of secured debt instruments are highly stable and narrowly range bound. They historically fail to beat inflation. They carry a risk of `loss of opportunity for wealth creation` in long run.

## STRATEGY I

Keep almost everything in highly secure debt instruments and buy small amounts of highly speculative assets regularly, to cash in positive asymmetry.

::: callout-warning
## Problem with stand-alone secure debt 

This will insulate the Corpus from all the negative Shock.

The Corpus will insulate itself from the positive shocks as well.

Portfolio will neglect and fail to gain from what-ever upward gains it can obtain from equity investment and the return will be generally low to beat inflation.
:::

## STRATEGY II

Put everything in equity & buy an insurance or store of value speculative assets against negative draw downs.

On problem with Strategy II is how to face Japan's lost decade like situation - a situation where equity is range bound, potentially for decades. But such situations tend to remain more deflationary than inflation prone and one may expect less capital erosion.

::: callout-caution
## Disclaimer

-   Opinions are for informational purposes only and not personalized investment advice.
-   Readers should consult a qualified financial advisor before making any investment decisions.
:::
