---
title: "Part 1 FRCS"
---
## Preparing for Part I

Like any other thing in life, there are multiple paths for Part I preparation. Rather than enumerating, I would describe what worked out for me. I believe that, at least 5 months of intense preparation is necessary before you can confidently appear for Part I. Focused preparation begins after the successful submission of application. So, before paying the exam fees, make sure that at least 5-6 months are left for the preparation. It is a good first to answer all the Orthobullets questions to get an idea of where you stand. My score was 40%. I bought Miller’s Review of Orthopaedics and started learning. I spent nearly 5-6 hours reading Miller/attempting Orthobullets questions. My strategy was to read Miller as much as I can and as quickly as possible so as to revise at-least 3-4 times. My strategy for Orthobullets questions was similar. My target was 150-200 questions per day, with 3-4 revisions before exam. 1 month before the Part I exam, I bought paid questions in the Orthobullets and BMJ OnExamination which I believe, though expensive, gave me an extra edge and confidence.

### My Part I preparation in nutshell was
Miller’s review of orthopaedics latest edition, page-to-page, 4 revisions

Orthobullets free questions, 3 revisions

Orthobullets paid questions

BMJ OnExamination

Total 5-6 months preparation spending 5-6 hours on an average daily.

### Actual Part I exam experience
Just like any other examination in the past, I reached the city 1 day prier to the exam date. I stayed at a decent 4-star hotel which was located at a walkable distance from the Pearson VUE test Centre. My exam was in the afternoon. I woke up at 6 am. My plan was to brush through the entire Miller before noon, which I did. This gave me a fresh confidence. Had a nice meal and I packed some food to the exam hall.

I consciously abstained from reading/talking anything related to exam from there. Luckily I knew no-one in the exam hall, so I could escape to one corner in the waiting area. I read lightly from my Kindle something other than Orthopaedics and relaxed.

An official checked our passport and gave a brief introduction. I kept all my belongings in to a designated locker, including my mobile after switching off. I was escorted to the test area, and after frisking, was given a pen and a paper for rough work and was taken to the CBT console. Total duration of the exam was 5 hours (2 hours SBA, 2 hours 30 minutes EMQ, 30 minutes break in between). During the break, I was allowed to open the locker, take out my packed food and eat from the waiting area. There were no refreshments provided except for drinking water. The topics/questions I could remember are summarised here

### The paper
My plan was to see all the questions as quickly as possible and mark the sure shot answers. Then I came back and spent some time on questions which demanded some pondering. Then I came back again to reconsider and review the already answered questions. The flagged questions, the answers of which were not known to me were then reviewed and made some educated guesses. Luckily, still I felt as if I had lot of time.

### The result

The result came as an email from the CHAIR, JSCFE SPECIALTY BOARD IN TRAUMA & ORTHOPAEDIC SURGERY exactly 20 days after the examination. It also included the breakdown of the result. Mean minimum score required to proceed to Part II was 61.46%. My mean score was 73.39%.
