---
title: "Classifications"
toc: true
---

## Wagner Classification of Diabetic Foot Ulcers

::: callout
+:-------------------------------------------------------+:----------------------------------------------------------+
| [Grade 0]{style="font-weight:bold; font-style:italic"} | No ulcer but foot deformity at risk of causing ulceration |
+--------------------------------------------------------+-----------------------------------------------------------+
| [Grade 1]{style="font-weight:bold; font-style:italic"} | Superficial ulcer                                         |
+--------------------------------------------------------+-----------------------------------------------------------+
| [Grade 2]{style="font-weight:bold; font-style:italic"} | Deep ulcer with visible bone or tendon                    |
+--------------------------------------------------------+-----------------------------------------------------------+
| [Grade 3]{style="font-weight:bold; font-style:italic"} | Deep ulcer with abscess or osteomyelitis                  |
+--------------------------------------------------------+-----------------------------------------------------------+
| [Grade 4]{style="font-weight:bold; font-style:italic"} | Ulcer with gangrene limited to the forefoot               |
+--------------------------------------------------------+-----------------------------------------------------------+
| [Grade 5]{style="font-weight:bold; font-style:italic"} | Ulcer with gangrene of the whole foot                     |
+--------------------------------------------------------+-----------------------------------------------------------+
:::

## Eichenholz Classification of Charcot Foot


+---------------------------------------------------+--------------------------------------------------+------------------------------------------------------+
| [Stage]{style="font-weight: bold; color:#000090"} | [Name]{style="font-weight: bold; color:#000090"} | [Features]{style="font-weight: bold; color:#000090"} |
+---------------------------------------------------+--------------------------------------------------+------------------------------------------------------+
| 0                                                 | Pre-Fragmentation                                | Acutely painful                                      |
|                                                   |                                                  |                                                      |
|                                                   |                                                  | Regional Demineralisation of bone                    |
+---------------------------------------------------+--------------------------------------------------+------------------------------------------------------+
| 1                                                 | Fragmentation                                    | Painful                                              |
|                                                   |                                                  |                                                      |
|                                                   |                                                  | Periarticular fragmentation                          |
|                                                   |                                                  |                                                      |
|                                                   |                                                  | Demineralisation of bone                             |
|                                                   |                                                  |                                                      |
|                                                   |                                                  | Joint Dislocations                                   |
+---------------------------------------------------+--------------------------------------------------+------------------------------------------------------+
| 2                                                 | Coalescence                                      | Less Pain                                            |
|                                                   |                                                  |                                                      |
|                                                   |                                                  | Sclerosis                                            |
|                                                   |                                                  |                                                      |
|                                                   |                                                  | Bone Resorption                                      |
+---------------------------------------------------+--------------------------------------------------+------------------------------------------------------+
| 3                                                 | Remodelling                                      | Pain Free                                            |
|                                                   |                                                  |                                                      |
|                                                   |                                                  | Malunited, Ankylosed joints                          |
+---------------------------------------------------+--------------------------------------------------+------------------------------------------------------+


## Osteochondral Defects of Talus

::: callout
### Berndt & Hardy

Stage 1 Subchondral fracture

Stage 2 Partially detached fragment

Stage 3 Detached but stable fragment

Stage 4 Detached and unstable fragment -- free floating

`Based on XR -- only 50% OCD visible`
:::

MRI classification by Bristol Group

## Occipital Condyle Fractures

::: callout
+:------------------------------------------------+:----------------------------------------------------+
| [Type]{style="font-weight:bold; color:#000090"} | [Features]{style="font-weight:bold; color:#000090"} |
+-------------------------------------------------+-----------------------------------------------------+
| [Type 1]{style="font-weight:bold"}              | Anterior displacement condyles -- most common       |
+-------------------------------------------------+-----------------------------------------------------+
| [Type 2]{style="font-weight:bold"}              | Superior migration of condyles                      |
+-------------------------------------------------+-----------------------------------------------------+
| [Type 3]{style="font-weight:bold"}              | Posterior displacement of condyles -- least common  |
+-------------------------------------------------+-----------------------------------------------------+
:::

`Image`

## Atlas. (C1) Fractures - Levine Classification

::: callout
+-------------------------------+--------------------------------------------------------------------+
| **Type**                      | **Features**                                                       |
+-------------------------------+--------------------------------------------------------------------+
| [A]{style="font-weight:bold"} | Transverse process                                                 |
+-------------------------------+--------------------------------------------------------------------+
| [B]{style="font-weight:bold"} | Posterior Arch                                                     |
+-------------------------------+--------------------------------------------------------------------+
| [C]{style="font-weight:bold"} | Anterior Arch                                                      |
+-------------------------------+--------------------------------------------------------------------+
| [D]{style="font-weight:bold"} | Lateral Mass                                                       |
+-------------------------------+--------------------------------------------------------------------+
| [E]{style="font-weight:bold"} | Burst Transverse ligament intact                                   |
|                               |                                                                    |
|                               | Burst -- Transverse ligament disrupted (\>7.5mm combined widening) |
+-------------------------------+--------------------------------------------------------------------+
:::

## Hangmans Fracture (Traumatic C2 Spondylolisthesis) Classification (Levine & Edwards)

::: callout
+---------------+--------------------------------------------------------+
| Type          | Features                                               |
+---------------+--------------------------------------------------------+
| Type 1        | \<3mm dis placement                                    |
|               |                                                        |
|               | Disc ok                                                |
+---------------+--------------------------------------------------------+
| Type 2        | \>3mm dis placement                                    |
|               |                                                        |
|               | Disc usually ok                                        |
|               |                                                        |
|               | Most common                                            |
+---------------+--------------------------------------------------------+
| Type 2a       | A ngulation rather than dis placement                  |
|               |                                                        |
|               | Disc likely extruded -- care with reduction & traction |
|               |                                                        |
|               | Benign looking but severe injury                       |
+---------------+--------------------------------------------------------+
| Type 3        | Concurrent Facet dislocation                           |
|               |                                                        |
|               | Hyper extension with rebound flexion                   |
|               |                                                        |
|               | Disc extruded                                          |
|               |                                                        |
|               | High incidence of neurologic injury                    |
+---------------+--------------------------------------------------------+
:::

`image`

## PEG Fractures - Classification (Anderson)

::: callout
+:------------------------------------------------+:----------------------------------------------------+
| [Type]{style="font-weight:bold; color:#000090"} | [Features]{style="font-weight:bold; color:#000090"} |
+-------------------------------------------------+-----------------------------------------------------+
| [1]{style="font-weight:bold"}                   | Avulsion from tip (apical or alar ligaments)        |
+-------------------------------------------------+-----------------------------------------------------+
| [2]{style="font-weight:bold"}                   | Waist non-comminuted (most common)                  |
+-------------------------------------------------+-----------------------------------------------------+
| [2a]{style="font-weight:bold"}                  | Waist comminuted (most unstable)                    |
+-------------------------------------------------+-----------------------------------------------------+
| [3]{style="font-weight:bold"}                   | Into cancellous bone of C2 body +/- facets          |
+-------------------------------------------------+-----------------------------------------------------+
:::

## Spinal Muscular Atrophy

::: callout
+----------------------------------+-------------------------------------------+
| Types                            | Features                                  |
+----------------------------------+-------------------------------------------+
| [SMA1]{style="font-weight:bold"} | Onset under 6 months                      |
|                                  |                                           |
|                                  | Death under 2 years (respiratory failure) |
+----------------------------------+-------------------------------------------+
| [SMA2]{style="font-weight:bold"} | Onset by 2 years                          |
|                                  |                                           |
|                                  | Death by 20 years                         |
+----------------------------------+-------------------------------------------+
| [SMA3]{style="font-weight:bold"} | Onset after 2 years                       |
|                                  |                                           |
|                                  | Normal life expectancy                    |
+----------------------------------+-------------------------------------------+
:::

## HSMN Sub-types

::: callout
+---------------+------------------------------------------------------+
| Type          | Features                                             |
+---------------+------------------------------------------------------+
| HSMN1         | Onset in teens                                       |
|               |                                                      |
|               | Demyelination of nerves                              |
|               |                                                      |
|               | Absent reflexes                                      |
|               |                                                      |
|               | NCS abnormal                                         |
+---------------+------------------------------------------------------+
| HSMN2         | Onset \>20 years - Milder                            |
|               |                                                      |
|               | No demyelination but there is wallerian degeneration |
|               |                                                      |
|               | Reflexes present                                     |
|               |                                                      |
|               | NCS almost normal                                    |
+---------------+------------------------------------------------------+
| HSMN3         | Djerne-Stotta Disease; AR                            |
|               |                                                      |
|               | Onset in infancy                                     |
|               |                                                      |
|               | Much more severe                                     |
+---------------+------------------------------------------------------+
:::

## Spina Bifida Types

::: callout
+----------------------------------------------+------------------------------------------------+
| Type                                         | Features                                       |
+----------------------------------------------+------------------------------------------------+
| [Occulta]{style="font-weight:bold"}          | Defect in posterior elements but no extrusion  |
+----------------------------------------------+------------------------------------------------+
| [Meningocele]{style="font-weight:bold"}      | Extrusion of dura only                         |
+----------------------------------------------+------------------------------------------------+
| [Myelomeningocele]{style="font-weight:bold"} | Extrusion of neural elements contained by dura |
|                                              |                                                |
|                                              | Classic spina bifida                           |
+----------------------------------------------+------------------------------------------------+
| [Rachischis]{style="font-weight:bold"}       | Neural elements extruded and fully exposed     |
|                                              |                                                |
|                                              | Very severe                                    |
+----------------------------------------------+------------------------------------------------+
:::

## Capitellar Fractures (Bryan & Morrey)

::: callout
+:------------------------------------------------+:------------------------------------------------------------------+
| [Type]{style="font-weight:bold; color:#000090"} | [Features]{style="font-weight:bold; color:#000090"}               |
+-------------------------------------------------+-------------------------------------------------------------------+
| [1]{style="font-weight:bold"}                   | Complete, minimal extension into trochlea (Hans Steinhal)         |
+-------------------------------------------------+-------------------------------------------------------------------+
| [2]{style="font-weight:bold"}                   | OCD (Kocher Lorenz)                                               |
+-------------------------------------------------+-------------------------------------------------------------------+
| [3]{style="font-weight:bold"}                   | Comminuted compressed fracture                                    |
+-------------------------------------------------+-------------------------------------------------------------------+
| [4]{style="font-weight:bold"}                   | Complete with significant extension into trochlea (double bubble) |
+-------------------------------------------------+-------------------------------------------------------------------+
:::

## Radial Head (Mason)

::: callout
+:------------------------------------------------+:----------------------------------------------------+
| [Type]{style="font-weight:bold; color:#000090"} | [Features]{style="font-weight:bold; color:#000090"} |
+-------------------------------------------------+-----------------------------------------------------+
| [1]{style="font-weight:bold"}                   | Undisplaced                                         |
+-------------------------------------------------+-----------------------------------------------------+
| [2]{style="font-weight:bold"}                   | Marginal fracture displaced                         |
+-------------------------------------------------+-----------------------------------------------------+
| [3]{style="font-weight:bold"}                   | Comminuted displaced fracture                       |
+-------------------------------------------------+-----------------------------------------------------+
| [4]{style="font-weight:bold"}                   | Fracture with Elbow Dislocation                     |
+-------------------------------------------------+-----------------------------------------------------+
:::

## Radial Neck (Mason)

::: callout
+:------------------------------------------------+:----------------------------------------------------+
| [Type]{style="font-weight:bold; color:#000090"} | [Features]{style="font-weight:bold; color:#000090"} |
+-------------------------------------------------+-----------------------------------------------------+
| [1]{style="font-weight:bold"}                   | Undisplaced                                         |
+-------------------------------------------------+-----------------------------------------------------+
| [2]{style="font-weight:bold"}                   | Displaced fracture                                  |
+-------------------------------------------------+-----------------------------------------------------+
| [3]{style="font-weight:bold"}                   | Displaced and comminuted fracture                   |
+-------------------------------------------------+-----------------------------------------------------+
| [4]{style="font-weight:bold"}                   | Fracture with Elbow Dislocation                     |
+-------------------------------------------------+-----------------------------------------------------+
:::

## Coronoid Process (Morrey)

::: callout
+:------------------------------------------------+:----------------------------------------------------+
| [Type]{style="font-weight:bold; color:#000090"} | [Features]{style="font-weight:bold; color:#000090"} |
+-------------------------------------------------+-----------------------------------------------------+
| [1]{style="font-weight:bold"}                   | Tip                                                 |
+-------------------------------------------------+-----------------------------------------------------+
| [2]{style="font-weight:bold"}                   | \<50%                                               |
+-------------------------------------------------+-----------------------------------------------------+
| [3]{style="font-weight:bold"}                   | \>50%                                               |
+-------------------------------------------------+-----------------------------------------------------+
:::

## Coronoid (O'Driscoll)

::: callout
+--------------+--------------+--------------------------------------------+
| Type         | Subtype      | Description                                |
+--------------+--------------+--------------------------------------------+
| Tip          | 1            | \<2mm coronoid height                    |
|              |              |                                            |
|              | 2            | \>2mm coronoid height                    |
+--------------+--------------+--------------------------------------------+
| Anteromedial | 1            | Rim                                        |
|              |              |                                            |
|              | 2            | Rim and Tip                                |
|              |              |                                            |
|              | 3            | Involving sublime tubercle              |
+--------------+--------------+--------------------------------------------+
| Basal        | 1            | Coronoid body and base                    |
|              |              |                                            |
|              | 2            | Transolecranon basal coronoid fracture |
+--------------+--------------+--------------------------------------------+
:::

`image` 

## Tibialis Posterior Insufficiency (Johnson -- Myerson grade 4)

::: callout
+---------------------------------------------------+------------------------------------------------------+
| [Grade]{style="fon t-weight:bold; color:#000090"} | [Features]{style="fon t-weight:bold; color:#000090"} |
+---------------------------------------------------+------------------------------------------------------+
| [0]{style="fon t-weight:bold"}                    | Asymptomatic with MRI changes                        |
+---------------------------------------------------+------------------------------------------------------+
| [1]{style="fon t-weight:bold"}                    | TP painful but competent                             |
+---------------------------------------------------+------------------------------------------------------+
| [2]{style="fon t-weight:bold"}                    | Incompetent TP with flexible planovalgus             |
+---------------------------------------------------+------------------------------------------------------+
| [3]{style="fon t-weight:bold"}                    | Incompetent TP with fixed planovalgus                |
+---------------------------------------------------+------------------------------------------------------+
| [4]{style="fon t-weight:bold"}                    | Fixed planovalgus with talar tilt                    |
+---------------------------------------------------+------------------------------------------------------+
:::

## Hallux Valgus Severity

::: callout
+----------+---------+---------+
| Grade    | HVA     | IMA     |
+----------+---------+---------+
| Normal   | \<15    | \<8     |
+----------+---------+---------+
| Mild     | 15-19   | 8-13    |
+----------+---------+---------+
| Moderate | 20-40   | 13-20   |
+----------+---------+---------+
| Severe   | \>40    | \>20    |
+----------+---------+---------+
:::

## Avascular Necrosis of the Hip (FICAT)

::: callout
+---------------------------------------------------+------------------------------------------------------+
| [Stage]{style="fon t-weight:bold; color:#000090"} | [Features]{style="fon t-weight:bold; color:#000090"} |
+---------------------------------------------------+------------------------------------------------------+
| [1]{style="fon t-weight:bold"}                    | XR normal -- MRI or Bone scan positive               |
+---------------------------------------------------+------------------------------------------------------+
| [2]{style="fon t-weight:bold"}                    | Sclerosis and cyst formation                         |
+---------------------------------------------------+------------------------------------------------------+
| [3]{style="fon t-weight:bold"}                    | Subchonral collapse -- crescent sign                 |
+---------------------------------------------------+------------------------------------------------------+
| [4]{style="fon t-weight:bold"}                    | Significant collapse and arthrosis                   |
+---------------------------------------------------+------------------------------------------------------+
:::

## Avascular Necrosis of the Hip (Steinberg)

::: callout
+---------------+-------------------------------------------+
| Stage         | Features                                  |
+---------------+-------------------------------------------+
| 0             | All imaging normal                        |
+---------------+-------------------------------------------+
| 1             | XR normal, MRI or Bone scan positive      |
+---------------+-------------------------------------------+
| 2             | Sclerosis and cyst formation              |
+---------------+-------------------------------------------+
| 3             | Subchondral collapse -- crescent sign     |
+---------------+-------------------------------------------+
| 4             | Head collapse, deformation and flattening |
+---------------+-------------------------------------------+
| 5             | Joint space narrowing                     |
+---------------+-------------------------------------------+
| 6             | Severe arthrosis                          |
+---------------+-------------------------------------------+
:::

## Femoral Head fracture dislocations (Pipkin)

::: callout
+--------------------------------------------------+--------------------------------------------------------+------------------------------------------------------+
| [Type]{style="font-weight: bold; color:#000090"} | [Features]{style="font-weight: bold; color:#000090"}   | [AVN Rate]{style="font-weight: bold; color:#000090"} |
+--------------------------------------------------+--------------------------------------------------------+------------------------------------------------------+
| Type 1                                           | Dislocation with fracture inferior to fovea (NWB zone) | \<5%                                                 |
+--------------------------------------------------+--------------------------------------------------------+------------------------------------------------------+
| Type 2                                           | Dislocation with fracture superior to fovea in WB zone | \<5%                                                 |
+--------------------------------------------------+--------------------------------------------------------+------------------------------------------------------+
| Type 3                                           | Type 1 or 2 with associated neck fracture (worst)      | 50%                                                  |
+--------------------------------------------------+--------------------------------------------------------+------------------------------------------------------+
| Type 4                                           | Type 1 or 2 with associated acetabular fracture        | 10%                                                  |
+--------------------------------------------------+--------------------------------------------------------+------------------------------------------------------+
:::

## Tibial Plateau (Schatzker)

::: callout
+---------------+-----------------------------------------------+-------------------------+
| Type          | Features                                      | Notes                   |
+---------------+-----------------------------------------------+-------------------------+
| 1             | Split                                         | Young                   |
+---------------+-----------------------------------------------+-------------------------+
| 2             | Split Depression                              | Middle aged             |
+---------------+-----------------------------------------------+-------------------------+
| 3             | Depression                                    | Elderly                 |
+---------------+-----------------------------------------------+-------------------------+
| 4             | Medial plateau only                           | Likely knee dislocation |
+---------------+-----------------------------------------------+-------------------------+
| 5             | Both plateaus with metaphyseal continuity     | Axial compression       |
+---------------+-----------------------------------------------+-------------------------+
| 6             | Both plateaus with metaphyseal di scontinuity | Axial compression       |
+---------------+-----------------------------------------------+-------------------------+
:::

## Stages of Elbow Instability

:::callout

+---------------------------------------------------+-----------------------------------------------------------------------------------------------------+
| [Stage]{style="fon t-weight:bold; color:#000090"} | [Features]{style="fon t-weight:bold; color:#000090"}                                                |
+---------------------------------------------------+-----------------------------------------------------------------------------------------------------+
|                                                   |                                                                                                     |
+---------------------------------------------------+-----------------------------------------------------------------------------------------------------+
| [Stage 1]{style="fon t-weight:bold"}              | Only Ulna lateral collateral ligament disrupted                                                     |
|                                                   |                                                                                                     |
|                                                   | Posterolateral subluxation                                                                          |
+---------------------------------------------------+-----------------------------------------------------------------------------------------------------+
| [Stage 2]{style="fon t-weight:bold"}              | All lateral collateral ligaments disrupted                                                          |
|                                                   |                                                                                                     |
|                                                   | Posterolateral dislocation -- often perched                                                         |
|                                                   |                                                                                                     |
|                                                   | Stable on reduction                                                                                 |
+---------------------------------------------------+-----------------------------------------------------------------------------------------------------+
| [Stage 3A]{style="fon t-weight:bold"}             | Lateral and medial (xpt anterior band) collateral ligaments disrupted Stable when reduced to valgus |
+---------------------------------------------------+-----------------------------------------------------------------------------------------------------+
| [Stage 3B]{style="fon t-weight:bold"}             | Complete disruption of MCL including anterior band                                                  |
|                                                   |                                                                                                     |
|                                                   | Unstable to valgus but stable in plaster at 90 degrees                                              |
+---------------------------------------------------+-----------------------------------------------------------------------------------------------------+
| [Stage 3C]{style="fon t-weight:bold"}             | Avulsion of all soft tissue from distal humerus                                                     |
|                                                   |                                                                                                     |
|                                                   | Unstable in plaster without flexion \>90 degrees                                                    |
+---------------------------------------------------+-----------------------------------------------------------------------------------------------------+

::;

## ASIA Scale of SCI

::: callout
+----------------------------------------------------+-------------------------------------------------------------+
| [Injury]{style="fon t-weight:bold; color:#000090"} | [Features]{style="fon t-weight:bold; color:#000090"}        |
+----------------------------------------------------+-------------------------------------------------------------+
| [A]{style="fon t-weight:bold"}                     | Complete                                                    |
|                                                    |                                                             |
|                                                    | No sensory or motor function below level                    |
+----------------------------------------------------+-------------------------------------------------------------+
| [B]{style="fon t-weight:bold"}                     | Incomplete                                                  |
|                                                    |                                                             |
|                                                    | Sensory function but no motor function below level          |
+----------------------------------------------------+-------------------------------------------------------------+
| [C]{style="fon t-weight:bold"}                     | Incomplete                                                  |
|                                                    |                                                             |
|                                                    | Motor and sensory function below level                      |
|                                                    |                                                             |
|                                                    | At least 50% muscles below level have grade 2 or less power |
+----------------------------------------------------+-------------------------------------------------------------+
| [D]{style="fon t-weight:bold"}                     | Incomplete                                                  |
|                                                    |                                                             |
|                                                    | At least 50% muscles below level have grade 3 or more power |
+----------------------------------------------------+-------------------------------------------------------------+
| [E]{style="fon t-weight:bold"}                     | Normal Motor and Sensory function                           |
+----------------------------------------------------+-------------------------------------------------------------+
:::

## Glenoid Fractures

::: callout
+:------------------------------------------------+:-------------------------------------------------------+
| [Type]{style="font-weight:bold; color:#000090"} | [Description]{style="font-weight:bold; color:#000090"} |
+-------------------------------------------------+--------------------------------------------------------+
| [1A]{style="font-weight:bold"}                  | Anterior rim                                           |
+-------------------------------------------------+--------------------------------------------------------+
| [1B]{style="font-weight:bold"}                  | Posterior rim                                          |
+-------------------------------------------------+--------------------------------------------------------+
| [2]{style="font-weight:bold"}                   | Transverse fracture exiting inferiorly                 |
+-------------------------------------------------+--------------------------------------------------------+
| [3]{style="font-weight:bold"}                   | Transverse fracture exiting medial to coracoid         |
+-------------------------------------------------+--------------------------------------------------------+
| [4]{style="font-weight:bold"}                   | Transverse exiting at medial border scapula            |
+-------------------------------------------------+--------------------------------------------------------+
| [5]{style="font-weight:bold"}                   | Combination of 2 and 4                                 |
+-------------------------------------------------+--------------------------------------------------------+
| [6]{style="font-weight:bold"}                   | Comminuted glenoid                                     |
+-------------------------------------------------+--------------------------------------------------------+
:::

## Calcaneal Fractures -- Sanders 

::: callout
+:-------------------------------------------------+:----------------------------------------------------+
| [Grade]{style="font-weight:bold; color:#000090"} | [Features]{style="font-weight:bold; color:#000090"} |
+--------------------------------------------------+-----------------------------------------------------+
| [1]{style="font-weight:bold"}                    | Undisplaced no matter how many fracture lines       |
+--------------------------------------------------+-----------------------------------------------------+
| [2 (A, B, C)]{style="font-weight:bold"}          | 1 fracture line causing 2 displaced fragments       |
+--------------------------------------------------+-----------------------------------------------------+
| [3 (A, B, C)]{style="font-weight:bold"}          | 2 fracture lines causing 3 displaced fragments      |
+--------------------------------------------------+-----------------------------------------------------+
| [4]{style="font-weight:bold"}                    | 3 or more fracture lines with multiple fragments    |
+--------------------------------------------------+-----------------------------------------------------+
:::

## Soft Tissue Injuries -- Tscherne

::: callout
+-------------------------------+-----------------------------------------------+
| Grade                         | Features                                      |
+-------------------------------+-----------------------------------------------+
| [0]{style="font-weight:bold"} | Indirect force                                |
|                               |                                               |
|                               | Negligable soft tissue damage                 |
|                               |                                               |
|                               | No skeletal injury                            |
+-------------------------------+-----------------------------------------------+
| [1]{style="font-weight:bold"} | Low energy fracture                           |
|                               |                                               |
|                               | Superficial contusion/abrasion                |
+-------------------------------+-----------------------------------------------+
| [2]{style="font-weight:bold"} | High energy skeletal injury                   |
|                               |                                               |
|                               | Degloving or avulsion of soft tissues         |
|                               |                                               |
|                               | High risk of compartment syndrome             |
+-------------------------------+-----------------------------------------------+
| [3]{style="font-weight:bold"} | Extensive crushing mechanism injury           |
|                               |                                               |
|                               | Partial or complete amputation                |
|                               |                                               |
|                               | Impending or established compartment syndrome |
+-------------------------------+-----------------------------------------------+
:::

## Open Fractures -- Gustillo Anderson

::: callout
+--------------------------------+------------------------------------------------------+
| Grade                          | Features                                             |
+--------------------------------+------------------------------------------------------+
| [1]{style="font-weight:bold"}  | Puncture \<1cm                                       |
|                                |                                                      |
|                                | Simple low energy fracture                           |
+--------------------------------+------------------------------------------------------+
| [2]{style="font-weight:bold"}  | Laceration \>1cm                                     |
|                                |                                                      |
|                                | Simple low energy fracture                           |
+--------------------------------+------------------------------------------------------+
| [3a]{style="font-weight:bold"} | Large or contaminated soft tissue injury             |
|                                |                                                      |
|                                | High energy fracture pattern/mechanism               |
|                                |                                                      |
|                                | Primary Soft tissue coverage possible                |
+--------------------------------+------------------------------------------------------+
| [3b]{style="font-weight:bold"} | As 3b but requires plastics for soft tissue coverage |
+--------------------------------+------------------------------------------------------+
| [3c]{style="font-weight:bold"} | Vascular injury                                      |
+--------------------------------+------------------------------------------------------+
:::

## Acetabular Fractures -- Letournel

::: callout
+-------------------------------------------------------+--------------------------------------------------------+
| [Elemental]{style="fon t-weight:bold; color:#000090"} | [Associated]{style="fon t-weight:bold; color:#000090"} |
+-------------------------------------------------------+--------------------------------------------------------+
| Posterior Wall                                        | Posterior wall & Posterior column                      |
+-------------------------------------------------------+--------------------------------------------------------+
| Posterior Column                                      | Transverse and Posterior wall                          |
+-------------------------------------------------------+--------------------------------------------------------+
| Anterior Wall                                         | Anterior column and posterior hemitransverse           |
+-------------------------------------------------------+--------------------------------------------------------+
| Anterior Column                                       | T Type                                                 |
+-------------------------------------------------------+--------------------------------------------------------+
| Transverse                                            | Both Column                                            |
+-------------------------------------------------------+--------------------------------------------------------+
:::

## Pelvic Fractures - Tile

::: callout
+:-----------------------------------------------------+:-----------------------------------------------------------------+
| [**Grade**]{style="font-weight:bold; color:#000090"} | [**Features**]{style="font-weight:bold; color:#000090"}          |
+------------------------------------------------------+------------------------------------------------------------------+
| A                                                    | Stable in all planes                                             |
+------------------------------------------------------+------------------------------------------------------------------+
| B                                                    | Rotationally unstable                                            |
+------------------------------------------------------+------------------------------------------------------------------+
| C                                                    | Rotationally & vertically unstable (posterior SI ligaments gone) |
+------------------------------------------------------+------------------------------------------------------------------+
:::

## Pelvic Fractures -- Young & Burgess

::: callout
+-------------+------------------------------------------------+--------------------------+-----------------------------------------+
|             | Grade 1                                        | Grade 2                  | Grade 3                                 |
+-------------+------------------------------------------------+--------------------------+-----------------------------------------+
| APC         | Symphysis diastasis                            | Ant SIJ ligament torn    | A & P SIJ ligaments torn                |
|             |                                                |                          |                                         |
|             | +/-SI joint widening                           | Post SIJ ligament intact | Vertical dis placement                  |
|             |                                                |                          |                                         |
|             | A&P SIJ ligaments intact                       |                          |                                         |
+-------------+------------------------------------------------+--------------------------+-----------------------------------------+
| LC          | H orizontal pubic ramus Fx                     | Crescent fracture        | APC injury of con traateral h emipelvis |
|             |                                                |                          |                                         |
|             | Sacral co mpression Fx                         |                          |                                         |
+-------------+------------------------------------------------+--------------------------+-----------------------------------------+
| VS          | V ertically displaced h emipelvis              |                          |                                         |
|             |                                                |                          |                                         |
|             | Symphisis and SIJ vertical dis placement or... |                          |                                         |
|             |                                                |                          |                                         |
|             | Vertical ramus and sacral fracture             |                          |                                         |
+-------------+------------------------------------------------+--------------------------+-----------------------------------------+
| Combined    | VS + LC                                        |                          |                                         |
|             |                                                |                          |                                         |
|             | APC + VS                                       |                          |                                         |
|             |                                                |                          |                                         |
|             | APC +LC                                        |                          |                                         |
+-------------+------------------------------------------------+--------------------------+-----------------------------------------+
:::

`image`

## Periprosthetic Hip -- Vancouver

::: callout
+---------------------------------+----------------------------------------+
| Type                            | Features                               |
+---------------------------------+----------------------------------------+
| [AG]{style="font-weight:bold"}  | Greater trochanter                     |
+---------------------------------+----------------------------------------+
| [A L]{style="font-weight:bold"} | Lesser Trochanter                      |
+---------------------------------+----------------------------------------+
| B1                              | At level of stem or just distal to tip |
|                                 |                                        |
|                                 | Well Fixed                             |
|                                 |                                        |
|                                 | Good bone stock                        |
+---------------------------------+----------------------------------------+
| B2                              | At level of stem or just istal to tip  |
|                                 |                                        |
|                                 | Loose                                  |
|                                 |                                        |
|                                 | Good bone stock                        |
+---------------------------------+----------------------------------------+
| B3                              | At level of stem or just distal to tip |
|                                 |                                        |
|                                 | Loose                                  |
|                                 |                                        |
|                                 | Loss of bone stock                     |
+---------------------------------+----------------------------------------+
| [C]{style="font-weight:bold"}   | Distal to Stem                         |
|                                 |                                        |
|                                 | Stem unaffected                        |
+---------------------------------+----------------------------------------+
:::

## Impending Pathologic Fracture -- Mirel's

::: callout
+--------------+--------------+---------------+----------------+
| Score        | 1            | 2             | 3              |
+--------------+--------------+---------------+----------------+
| Location     | Upper Limb   | Lower Limb    | Proximal femur |
+--------------+--------------+---------------+----------------+
| Appearance   | Sclerotic    | Mixed         | Lytic          |
+--------------+--------------+---------------+----------------+
| Size         | \<1/3        | \<2/3         | \>2/3          |
+--------------+--------------+---------------+----------------+
| Pain         | No Pain      | Moderate Pain | Unable to WB   |
+--------------+--------------+---------------+----------------+

[8 or more suggests impending fracture]{style="font-style:italic"}
:::

## Monteggia Fracture -- Bado

::: callout
+---------------+--------------------------------------+---------------+
| Type          | Features                             | Notes         |
+---------------+--------------------------------------+---------------+
| 1             | Anterior dislocation of radial head  | 70%           |
+---------------+--------------------------------------+---------------+
| 2             | Posterior dislocation of radial head | 5%            |
+---------------+--------------------------------------+---------------+
| 3             | Lateral dislocation of radial head   | 25%           |
+---------------+--------------------------------------+---------------+
| 4             | Associated radial shaft fracture     | \<5%          |
+---------------+--------------------------------------+---------------+
:::

## MESS Score

::: callout
+-----------------------------+----------+------------------------+-----------------+-----------+---------------+
| Score                       | 0        | 1                      | 2               | 3         | 4             |
+-----------------------------+----------+------------------------+-----------------+-----------+---------------+
| Age                         | \<30     | 30-50                  | \>50            |           |               |
+-----------------------------+----------+------------------------+-----------------+-----------+---------------+
| Shock                       | Systolic | Transient hy potension | Persistent      |           |               |
|                             |          |                        |                 |           |               |
|                             | \>90     |                        | Hy potension    |           |               |
+-----------------------------+----------+------------------------+-----------------+-----------+---------------+
| Limb ischemia               |          | Reduced                | Pulseless       | Insensate |               |
|                             |          |                        |                 |           |               |
|                             |          | Pulse                  | Parasthesia     | Cold      |               |
|                             |          |                        |                 |           |               |
|                             |          | Perfused limb          | Increased       | Paralysed |               |
|                             |          |                        |                 |           |               |
|                             |          |                        | CR              |           |               |
+-----------------------------+----------+------------------------+-----------------+-----------+---------------+
| Skeletal/Soft tissue injury |          | Low Energy             | Moderate energy | High      | Very High     |
|                             |          |                        |                 |           |               |
|                             |          |                        | (open Fx)       | Energy    | Energy        |
|                             |          |                        |                 |           |               |
|                             |          |                        |                 | (RTA)     | Crush, RTA,   |
|                             |          |                        |                 |           |               |
|                             |          |                        |                 |           | Con taminated |
+-----------------------------+----------+------------------------+-----------------+-----------+---------------+

[Ischaemia score doubled if ischaemia time \>6 hours]{style="font-weight:bold; font-style:italic"}

[Total score of 8 or more suggests limb may not be viable]{style="font-weight:bold; font-style:italic"}
:::

## Classification of Rheumatoid Thumb - Naelbuf

::: callout
+--------------------------------------------------+--------------------------------------------------------+
| [Type]{style="fon t-weight:bold; color:#000090"} | [Deformity]{style="fon t-weight:bold; color:#000090"}  |
+--------------------------------------------------+--------------------------------------------------------+
| [Type 1]{style="fon t-weight:bold"}              | Boutonniere (MCPJ flexion) most common                 |
+--------------------------------------------------+--------------------------------------------------------+
| [Type 2]{style="fon t-weight:bold"}              | Boutonniere with CMCJ dislocation or arthritis (rare)  |
+--------------------------------------------------+--------------------------------------------------------+
| [Type 3]{style="fon t-weight:bold"}              | Swan Neck (CMCJ adduction and flexion, MCPJ extension) |
+--------------------------------------------------+--------------------------------------------------------+
| [Type 4]{style="fon t-weight:bold"}              | Ulna collateral ligamant laxity                        |
+--------------------------------------------------+--------------------------------------------------------+
| [Type 5]{style="fon t-weight:bold"}              | Swan Neck with no adduction of metacarpal (rare)       |
+--------------------------------------------------+--------------------------------------------------------+
| [Type 6]{style="fon t-weight:bold"}              | Mutilating disease -- gross joint destruction          |
+--------------------------------------------------+--------------------------------------------------------+
:::

## TFCC Tears -- Palmer Classification

::: callout
### Type 1 -- Traumatic

+:------------------------------------------------+:----------------------------------------------------+
| [Type]{style="font-weight:bold; color:#000090"} | [Features]{style="font-weight:bold; color:#000090"} |
+-------------------------------------------------+-----------------------------------------------------+
| [1A]{style="font-weight:bold"}                  | Central perforation (debride)                       |
+-------------------------------------------------+-----------------------------------------------------+
| [1B]{style="font-weight:bold"}                  | Ulna styloid avulsion                               |
+-------------------------------------------------+-----------------------------------------------------+
| [1C]{style="font-weight:bold"}                  | Distal avulsion (triquetrum)                        |
+-------------------------------------------------+-----------------------------------------------------+
| [1D]{style="font-weight:bold"}                  | Radial Avulsion                                     |
+-------------------------------------------------+-----------------------------------------------------+
:::

::: callout
### Type 2 - Degenerative

+:------------------------------------------------+:-------------------------------------------------------+
| [Type]{style="font-weight:bold; color:#000090"} | [Features]{style="font-weight:bold; color:#000090"}    |
+-------------------------------------------------+--------------------------------------------------------+
| [2A]{style="font-weight:bold"}                  | Thinning of TFCC but no perforation                    |
+-------------------------------------------------+--------------------------------------------------------+
| [2B-E]{style="font-weight:bold"}                | Progressive arthrosis affecting carpal joints and DRUJ |
+-------------------------------------------------+--------------------------------------------------------+
:::

## Scaphoid Fractures

::: callout
### Russe -- Pattern

Transverse

Horizontal Oblique

Vertical Oblique (most unstable)
:::

::: callout
### Stability - Herbert

**Stable**

\<1mm displacement

**Unstable**

\>1mm displacement or gap

\>60 degrees scapholunate angle

\>15 degrees Radio-lunate angle

Comminution

Proximal Pole

Vertical Oblique fracture pattern
:::

::: callout
**Anatomic Location**

-   Proximal Pole

-   Waist

-   Distal Pole

-   Tuberosity
:::

## Keinbock's Disease -- Lichtman

::: callout
+---------------------------------------------------+------------------------------------------------------+--------------------------------------------------------+
| [Stage]{style="font-weight: bold; color:#000090"} | [Features]{style="font-weight: bold; color:#000090"} | [Management]{style="font-weight: bold; color:#000090"} |
+---------------------------------------------------+------------------------------------------------------+--------------------------------------------------------+
| 1                                                 | XR Normal                                            | Non-operative surveillance                             |
|                                                   |                                                      |                                                        |
|                                                   | MRI low signal                                       |                                                        |
+---------------------------------------------------+------------------------------------------------------+--------------------------------------------------------+
| 2                                                 | Sclerotic Lunate                                     | Joint Levelling                                        |
|                                                   |                                                      |                                                        |
|                                                   | No collapse or fragmentation                         | Core Decompression                                     |
|                                                   |                                                      |                                                        |
|                                                   |                                                      | Vascularised Grafting                                  |
+---------------------------------------------------+------------------------------------------------------+--------------------------------------------------------+
| 3A                                                | Lunate collapse                                      | Joint Levelling                                        |
|                                                   |                                                      |                                                        |
|                                                   | No Instability                                       | Core Decompression                                     |
|                                                   |                                                      |                                                        |
|                                                   | Scaphoid not rotated or fixed                        | Vascularised Grafting                                  |
|                                                   |                                                      |                                                        |
|                                                   |                                                      | (less predictable than stage 2)                        |
|                                                   |                                                      |                                                        |
|                                                   |                                                      | Limited Fusion                                         |
+---------------------------------------------------+------------------------------------------------------+--------------------------------------------------------+
| 3B                                                | Lunate Collapse                                      | Limited Fusion                                         |
|                                                   |                                                      |                                                        |
|                                                   | Reduced Carpal height                                | PRC                                                    |
|                                                   |                                                      |                                                        |
|                                                   | Instability -- scaphoid in fixed rotation            |                                                        |
+---------------------------------------------------+------------------------------------------------------+--------------------------------------------------------+
| 4                                                 | Pancarpal Arthrosis                                  | Wrist Fusion                                           |
|                                                   |                                                      |                                                        |
|                                                   |                                                      | PRC (not if capitate affected)                         |
+---------------------------------------------------+------------------------------------------------------+--------------------------------------------------------+
:::

## Classification of SLAP tears -- Schneider

::: callout
+--------------------------------------------------+----------------------------------------------------------------------------------+--------------------------------------------------------+
| [Type]{style="font-weight: bold; color:#000090"} | [Description]{style="font-weight: bold; color:#000090"}                          | [Management]{style="font-weight: bold; color:#000090"} |
+--------------------------------------------------+----------------------------------------------------------------------------------+--------------------------------------------------------+
| Type 1                                           | Fraying of superior labrum, intact biceps anchor                                 | Debride                                                |
+--------------------------------------------------+----------------------------------------------------------------------------------+--------------------------------------------------------+
| Type 2                                           | Unstable Biceps Anchor                                                           | Re-attach                                              |
+--------------------------------------------------+----------------------------------------------------------------------------------+--------------------------------------------------------+
| Type 3                                           | Bucket handle detachment of superior labrum from intact biceps anchor            | Debride                                                |
+--------------------------------------------------+----------------------------------------------------------------------------------+--------------------------------------------------------+
| Type 4                                           | Bucket handle detachment of whole biceps anchor with propogation into LHB tendon | Re-attach +/- LHB tenotomy                             |
+--------------------------------------------------+----------------------------------------------------------------------------------+--------------------------------------------------------+

[ ]{style="width:43.09pt; display:inline-block"}[Type 5]{style="font-style:italic"}[ ]{style="width:13.95pt; display:inline-block"}[SLAP with Labral tear -- reattach both]{style="font-style:italic"}

[ ]{style="width:43.09pt; display:inline-block"}[Type 6]{style="font-style:italic"}[ ]{style="width:13.96pt; display:inline-block"}[Superior flap tear -- debride]{style="font-style:italic"}

[ ]{style="width:43.09pt; display:inline-block"}[Type 7]{style="font-style:italic"}[ ]{style="width:13.95pt; display:inline-block"}[SLAP with capsular tear -- fix and reattach]{style="font-style:italic"}
:::

## Rheumatoid Arthritis Elbow -- Larsen

:::callout

+:-------------------------------------------------+:------------------------------------------------------+
| [Grade]{style="font-weight:bold; color:#000090"} | [Features]{style="font-weight:bold; color:#000090"}   |
+--------------------------------------------------+-------------------------------------------------------+
| [1]{style="font-weight:bold"}                    | Soft tissue inflammation & periarticular osteoporosis |
+--------------------------------------------------+-------------------------------------------------------+
| [2]{style="font-weight:bold"}                    | Joint space narrowing                                 |
+--------------------------------------------------+-------------------------------------------------------+
| [3]{style="font-weight:bold"}                    | Significant joint space narrowing                     |
+--------------------------------------------------+-------------------------------------------------------+
| [4]{style="font-weight:bold"}                    | Subchondral bony erosion and arthrosis                |
+--------------------------------------------------+-------------------------------------------------------+
| [5]{style="font-weight:bold"}                    | Severe arthritis with deformity                       |
+--------------------------------------------------+-------------------------------------------------------+

::;

## Thumb CMCJ Arthritis -- Eaton

::: callout
+---------------------------------------------------+------------------------------------------------------+
| [Stage]{style="fon t-weight:bold; color:#000090"} | [Features]{style="fon t-weight:bold; color:#000090"} |
+---------------------------------------------------+------------------------------------------------------+
| [Stage 1]{style="fon t-weight:bold"}              | Joint space widened                                  |
|                                                   |                                                      |
|                                                   | \<1/3 subluxation                                    |
+---------------------------------------------------+------------------------------------------------------+
| [Stage 2]{style="fon t-weight:bold"}              | Decreased joint space                                |
|                                                   |                                                      |
|                                                   | Marginal Osteophytes \<2mm in size                   |
|                                                   |                                                      |
|                                                   | 1/3 joint subluxation                                |
+---------------------------------------------------+------------------------------------------------------+
| [Stage 3]{style="fon t-weight:bold"}              | Significant arthrosis                                |
|                                                   |                                                      |
|                                                   | Sclerosis and cysts                                  |
|                                                   |                                                      |
|                                                   | Osteophytes \>2mm in size                            |
|                                                   |                                                      |
|                                                   | \>1/3 subluxation                                    |
+---------------------------------------------------+------------------------------------------------------+
| [Stage 4]{style="fon t-weight:bold"}              | STT arthritis                                        |
+---------------------------------------------------+------------------------------------------------------+
:::

## Hallux Rigidus -- Coughlin

::: callout
+---------------+-------------------------+-------------------+-----------------------+
| Grade         | X-Ray                   | Pain              | MTPJ Motion           |
+---------------+-------------------------+-------------------+-----------------------+
| 0             | Normal                  | None              | Minimal stiffness     |
+---------------+-------------------------+-------------------+-----------------------+
| 1             | Minimal narrowing       | Int ermittent     | Mild re striction     |
+---------------+-------------------------+-------------------+-----------------------+
| 2             | Narrowing & Osteophytes | Almost constant   | Moderate re striction |
+---------------+-------------------------+-------------------+-----------------------+
| 3             | Severe arthrosis        | Constant          | \<20 degrees          |
|               |                         |                   |                       |
|               |                         | None at mid range |                       |
+---------------+-------------------------+-------------------+-----------------------+
| 4             | Severe arthrosis        | Pain at mid range | \<20 degrees          |
+---------------+-------------------------+-------------------+-----------------------+
:::

## AVN Humeral Head -- Creuss

::: callout
+-------------------------------+----------------------------------------------+
| Stage                         | Features                                     |
+-------------------------------+----------------------------------------------+
| [1]{style="font-weight:bold"} | XR Normal                                    |
|                               |                                              |
|                               | MRI abnormal                                 |
+-------------------------------+----------------------------------------------+
| [2]{style="font-weight:bold"} | Sclerosis on XR                              |
+-------------------------------+----------------------------------------------+
| [3]{style="font-weight:bold"} | Subchondral Collapse                         |
|                               |                                              |
|                               | 'Crescent sign'                              |
+-------------------------------+----------------------------------------------+
| [4]{style="font-weight:bold"} | Humeral head collapse                        |
|                               |                                              |
|                               | Glenoid normal                               |
+-------------------------------+----------------------------------------------+
| [5]{style="font-weight:bold"} | Humeral head and Glenoid Arthrosis & Erosion |
+-------------------------------+----------------------------------------------+
:::

## Classification of Cerebral Palsy

::: callout
### Type

+:------------------------------------------------+:----------------------------------------------------+
| [Type]{style="font-weight:bold; color:#000090"} | [Features]{style="font-weight:bold; color:#000090"} |
+-------------------------------------------------+-----------------------------------------------------+
| [Spastic]{style="font-weight:bold"}             | UMN symptoms predominate                            |
+-------------------------------------------------+-----------------------------------------------------+
| [Athetoid]{style="font-weight:bold"}            | Flaccidity -- rare                                  |
+-------------------------------------------------+-----------------------------------------------------+
| [Ataxic]{style="font-weight:bold"}              | Cerebellar symptoms predominate                     |
+-------------------------------------------------+-----------------------------------------------------+

## Geographic

+:-------------------------------------------------+:----------------------------------------------------+
| [Type ]{style="font-weight:bold; color:#000090"} | [Features]{style="font-weight:bold; color:#000090"} |
+--------------------------------------------------+-----------------------------------------------------+
| [Quadriplegic]{style="font-weight:bold"}         | Whole body involvement                              |
+--------------------------------------------------+-----------------------------------------------------+
| [Diplegic]{style="font-weight:bold"}             | Lower limbs only                                    |
+--------------------------------------------------+-----------------------------------------------------+
| [Hemiplegic]{style="font-weight:bold"}           | Unilateral involvement -- rare                      |
+--------------------------------------------------+-----------------------------------------------------+

## Gross Motor Function Classification System (GMFCS)

+:------------------------------------------------+:------------------------------------------------------+
| [Type]{style="font-weight:bold; color:#000090"} | [Features]{style="font-weight:bold; color:#000090"}   |
+-------------------------------------------------+-------------------------------------------------------+
| [GMFCS 1]{style="font-weight:bold"}             | Able to walk independently                            |
+-------------------------------------------------+-------------------------------------------------------+
| [GMFCS 2]{style="font-weight:bold"}             | Occasional difficulty walking on slopes or in crowds  |
+-------------------------------------------------+-------------------------------------------------------+
| [GMFCS 3]{style="font-weight:bold"}             | Requires a walking aid.  Can self propel a wheelchair |
+-------------------------------------------------+-------------------------------------------------------+
| [GMFCS 4]{style="font-weight:bold"}             | Can transfer only.  Supports own head in wheelchair   |
+-------------------------------------------------+-------------------------------------------------------+
| [GMFCS 5]{style="font-weight:bold"}             | Wheelchair bound.  Unable to support head             |
+-------------------------------------------------+-------------------------------------------------------+
:::

## Perthes Disease -- Herring Lateral Pillar Height

::: callout
+:-------------------------------------------------+:-----------------------------------------------------------------+
| [Stage]{style="font-weight:bold; color:#000090"} | [Lateral Pillar Height]{style="font-weight:bold; color:#000090"} |
+--------------------------------------------------+------------------------------------------------------------------+
| [A]{style="font-weight:bold"}                    | Normal                                                           |
+--------------------------------------------------+------------------------------------------------------------------+
| [B]{style="font-weight:bold"}                    | \>50%                                                            |
+--------------------------------------------------+------------------------------------------------------------------+
| [B/C]{style="font-weight:bold"}                  | 50% with narrowing of physis                                     |
+--------------------------------------------------+------------------------------------------------------------------+
| [C]{style="font-weight:bold"}                    | \<50%                                                            |
+--------------------------------------------------+------------------------------------------------------------------+
:::

## Cervical Spine Rheumatoid Arthritis Severity -- Ranawat

::: callout
+:-----------------------------------------------------+:----------------------------------------------------------+
| [**Stage**]{style="font-weight:bold; color:#000090"} | [**Features**]{style="font-weight:bold; color:#000090"}   |
+------------------------------------------------------+-----------------------------------------------------------+
| [1]{style="font-weight:bold"}                        | No neurologic findings -- pain only                       |
+------------------------------------------------------+-----------------------------------------------------------+
| [2]{style="font-weight:bold"}                        | Subjective neurology                                      |
+------------------------------------------------------+-----------------------------------------------------------+
| [3a]{style="font-weight:bold"}                       | Objective neurology & UMN signs -- patient ambulatory     |
+------------------------------------------------------+-----------------------------------------------------------+
| [3b]{style="font-weight:bold"}                       | Objective neurology & UMN signs -- patient not ambulatory |
+------------------------------------------------------+-----------------------------------------------------------+

[3b do poorly with surgery -- identify and operate earlier]{style="font-style:italic"}
:::

## Ferguson Mechanistic Classification of Sub-Axial Fractures

::: callout
+-----------------------+--------------------------------------+-------------------------------------------------------------+
| Type                  | Examples                             | Notes                                                       |
+-----------------------+--------------------------------------+-------------------------------------------------------------+
| Flexion Compression   | Flexion tear drop                    | High rate neuro injury                                      |
|                       |                                      |                                                             |
|                       |                                      | Surgical management                                         |
+-----------------------+--------------------------------------+-------------------------------------------------------------+
| Flexion Distraction   | Facet Dislocation                    | High Rate neuro injury                                      |
|                       |                                      |                                                             |
|                       |                                      | Surgical Management                                         |
+-----------------------+--------------------------------------+-------------------------------------------------------------+
| Axial                 | Burst Fracture                       | Management depends on fea ures of instability and neurology |
+-----------------------+--------------------------------------+-------------------------------------------------------------+
| Extension Compression | Isolated posterior element fractures | Low incidence neuro injury                                  |
|                       |                                      |                                                             |
|                       |                                      | Highly unstable though - surgery                            |
+-----------------------+--------------------------------------+-------------------------------------------------------------+
| Extension             |                                      |                                                             |
+-----------------------+--------------------------------------+-------------------------------------------------------------+
| Lateral               |                                      | Beware: associated plexus injury                            |
|                       |                                      |                                                             |
| \[Compression         |                                      |                                                             |
+-----------------------+--------------------------------------+-------------------------------------------------------------+
:::

## Spondylolisthesis

::: callout
### Myerding -- degree slip

+:-------------------------------------------------+:----------------------------------------------------+
| [Grade]{style="font-weight:bold; color:#000090"} | [Features]{style="font-weight:bold; color:#000090"} |
+--------------------------------------------------+-----------------------------------------------------+
| [Grade 1]{style="font-weight:bold"}              | 0 -25%                                              |
+--------------------------------------------------+-----------------------------------------------------+
| [Grade 2]{style="font-weight:bold"}              | 25-50%                                              |
+--------------------------------------------------+-----------------------------------------------------+
| [Grade 3]{style="font-weight:bold"}              | 50-75%                                              |
+--------------------------------------------------+-----------------------------------------------------+
| [Grade 4]{style="font-weight:bold"}              | 75-100%                                             |
+--------------------------------------------------+-----------------------------------------------------+
| [Grade 5]{style="font-weight:bold"}              | \>100%  (spondylopoptosis)                          |
+--------------------------------------------------+-----------------------------------------------------+

## Wiltse -- Type

+--------------------------------------------------+----------------+------------------------------------------------------+
| [Type]{style="font-weight: bold; color:#000090"} |                | [Features]{style="font-weight: bold; color:#000090"} |
+--------------------------------------------------+----------------+------------------------------------------------------+
| 1                                                | Dysplastic     | L5/S1                                                |
|                                                  |                |                                                      |
|                                                  |                | Intact neural arch -- max 30% slip                   |
|                                                  |                |                                                      |
|                                                  |                | L5 inferior facet poorly formed                      |
|                                                  |                |                                                      |
|                                                  |                | S1 superior facet absent                             |
|                                                  |                |                                                      |
|                                                  |                | Trapezoidal L5                                       |
|                                                  |                |                                                      |
|                                                  |                | Girls & Eskimo's                                     |
+--------------------------------------------------+----------------+------------------------------------------------------+
| 2                                                | Isthmic 2A     | Stress fracture pars                                 |
|                                                  |                |                                                      |
|                                                  | Isthmic 2B     | Elongated Pars                                       |
|                                                  |                |                                                      |
|                                                  | Isthmic 2C     | Acute Fracture Pars                                  |
|                                                  |                |                                                      |
|                                                  |                | Boys & Eskimo's                                      |
|                                                  |                |                                                      |
|                                                  |                | Sagittaly orientated facets -- not dysplastic        |
|                                                  |                |                                                      |
|                                                  |                | \<25% slip usually                                   |
+--------------------------------------------------+----------------+------------------------------------------------------+
| 3                                                | \[Degenerative | Women                                                |
|                                                  |                |                                                      |
|                                                  |                | Diabetic                                             |
|                                                  |                |                                                      |
|                                                  |                | Black                                                |
|                                                  |                |                                                      |
|                                                  |                | \>40 years                                           |
|                                                  |                |                                                      |
|                                                  |                | L4/5                                                 |
+--------------------------------------------------+----------------+------------------------------------------------------+
| 4                                                | Traumatic\]    |                                                      |
+--------------------------------------------------+----------------+------------------------------------------------------+
| 5                                                | Pathologic     |                                                      |
+--------------------------------------------------+----------------+------------------------------------------------------+
| 6                                                | Iatrogenic     |                                                      |
+--------------------------------------------------+----------------+------------------------------------------------------+
:::

## Nerve Injury

::: callout
+----------------------------------------------------+------------------------------------------------------+--------------------------------------------------------+-------------------------------------------------------+
| [Seddon]{style="fon t-weight:bold; color:#000090"} | [Features]{style="fon t-weight:bold; color:#000090"} | [Sunderland]{style="fon t-weight:bold; color:#000090"} | [Prognosis]{style="fon t-weight:bold; color:#000090"} |
+----------------------------------------------------+------------------------------------------------------+--------------------------------------------------------+-------------------------------------------------------+
| [Type]{style="fon t-weight:bold; color:#000090"}   |                                                      |                                                        |                                                       |
+----------------------------------------------------+------------------------------------------------------+--------------------------------------------------------+-------------------------------------------------------+
| [Neuropraxia]{style="fon t-weight:bold"}           | No Wallerian Degeneration                            | Grade 1                                                | Good                                                  |
|                                                    |                                                      |                                                        |                                                       |
|                                                    | Segmental demyelination on histology                 |                                                        |                                                       |
|                                                    |                                                      |                                                        |                                                       |
|                                                    | Nerve in continuity                                  |                                                        |                                                       |
|                                                    |                                                      |                                                        |                                                       |
|                                                    | Conduction block                                     |                                                        |                                                       |
|                                                    |                                                      |                                                        |                                                       |
|                                                    | Epineurial damage only -- perineurium protects axon  |                                                        |                                                       |
+----------------------------------------------------+------------------------------------------------------+--------------------------------------------------------+-------------------------------------------------------+
| [Axonotmesis]{style="fon t-weight:bold"}           | Wallerian degeneration distal to injury              | Grade 2-4                                              | Ok                                                    |
|                                                    |                                                      |                                                        |                                                       |
|                                                    | Axonal damage                                        |                                                        |                                                       |
|                                                    |                                                      |                                                        |                                                       |
|                                                    | Perineurium may or may not be intact                 |                                                        |                                                       |
|                                                    |                                                      |                                                        |                                                       |
|                                                    | Endoneurium is intact                                |                                                        |                                                       |
|                                                    |                                                      |                                                        |                                                       |
|                                                    | Conduit for regeneration still present               |                                                        |                                                       |
+----------------------------------------------------+------------------------------------------------------+--------------------------------------------------------+-------------------------------------------------------+
| [Neurotmesis]{style="fon t-weight:bold"}           | Wallerian degeneration beyond injury                 | Grade 5                                                | Poor                                                  |
|                                                    |                                                      |                                                        |                                                       |
|                                                    | Endoneurium violated                                 |                                                        |                                                       |
|                                                    |                                                      |                                                        |                                                       |
|                                                    | No conduit for regeneration                          |                                                        |                                                       |
|                                                    |                                                      |                                                        |                                                       |
|                                                    | Repair or grafting required                          |                                                        |                                                       |
+----------------------------------------------------+------------------------------------------------------+--------------------------------------------------------+-------------------------------------------------------+
:::

## Sacral Fractures -- Denis

::: callout
+---------------+----------------------+------------------------------------------------+
| Type          | Features             | Notes                                          |
+---------------+----------------------+------------------------------------------------+
| Zone 1        | Lateral to Foramina  | 50% of all frac tures                          |
|               |                      |                                                |
|               |                      | 5% neuro logic i njury                         |
|               |                      |                                                |
|               |                      | Ver tical or ob lique                          |
|               |                      |                                                |
|               |                      | P elvic but no s pinal i nstab ility           |
+---------------+----------------------+------------------------------------------------+
| Zone 2        | Through the Foramina | 30% inci dence                                 |
|               |                      |                                                |
|               |                      | 30% neur logic i njury                         |
|               |                      |                                                |
|               |                      | Ver tical or ob lique                          |
|               |                      |                                                |
|               |                      | P elvic but no s pinal i nstab ility           |
+---------------+----------------------+------------------------------------------------+
| Zone 3        | Medial to Foramina   | 20% inci dence                                 |
|               |                      |                                                |
|               |                      | 60% neuro logic i njury                        |
|               |                      |                                                |
|               |                      | H orizo ntal, ver tical or ob lique            |
|               |                      |                                                |
|               |                      | S pinal and or p elvic i nstab ility           |
|               |                      |                                                |
|               |                      | Ver tical = hi ghest rate neuro logic de ficit |
+---------------+----------------------+------------------------------------------------+
:::

## Femoral head Fracture Dislocation -- Pipkin

::: callout
+------------+--------------------------------------------------------+------------+
| Type       | Features                                               | AVN rate   |
+------------+--------------------------------------------------------+------------+
| Type 1     | Dislocation with fracture inferior to fovea (NWB zone) | \<5%       |
+------------+--------------------------------------------------------+------------+
| Type 2     | Dislocation with fracture superior to fovea in WB zone | \<5%       |
+------------+--------------------------------------------------------+------------+
| Type 3     | Type 1 or 2 with associated neck fracture (worst)      | 50%        |
+------------+--------------------------------------------------------+------------+
| Type 4     | Type 1 or 2 with associated acetabular fracture        | 10%        |
+------------+--------------------------------------------------------+------------+
:::

## Bone Tumours -- Enneking

::: callout
+:------------------------------------------------+:-------------------------------------------------+:-------------------------------------------------------------+:------------------------------------------------------+
| [Type]{style="font-weight:bold; color:#000090"} | [Grade]{style="font-weight:bold; color:#000090"} | [Intra/Extra]{style="font-weight:bold; color:#000090"}       | [Metastases]{style="font-weight:bold; color:#000090"} |
|                                                 |                                                  |                                                              |                                                       |
|                                                 |                                                  | [**Compartmental**]{style="font-weight:bold; color:#000090"} |                                                       |
+-------------------------------------------------+--------------------------------------------------+--------------------------------------------------------------+-------------------------------------------------------+
| [1A]{style="font-weight:bold"}                  | Low                                              | Intra                                                        | None                                                  |
+-------------------------------------------------+--------------------------------------------------+--------------------------------------------------------------+-------------------------------------------------------+
| [1B]{style="font-weight:bold"}                  | Low                                              | Extra                                                        | None                                                  |
+-------------------------------------------------+--------------------------------------------------+--------------------------------------------------------------+-------------------------------------------------------+
| [2A]{style="font-weight:bold"}                  | High                                             | Intra                                                        | None                                                  |
+-------------------------------------------------+--------------------------------------------------+--------------------------------------------------------------+-------------------------------------------------------+
| [2B]{style="font-weight:bold"}                  | High                                             | Extra                                                        | None                                                  |
+-------------------------------------------------+--------------------------------------------------+--------------------------------------------------------------+-------------------------------------------------------+
| [3A]{style="font-weight:bold"}                  | Any                                              | Intra                                                        | Mets                                                  |
+-------------------------------------------------+--------------------------------------------------+--------------------------------------------------------------+-------------------------------------------------------+
| [3B]{style="font-weight:bold"}                  | Any                                              | Extra                                                        | Mets                                                  |
+-------------------------------------------------+--------------------------------------------------+--------------------------------------------------------------+-------------------------------------------------------+
:::

## SUFE Severity -- Southwick Angle

::: callout
+:--------------------------------------------------------+:--------------------------------------------------------+
| [**Severity**]{style="font-weight:bold; color:#000090"} | [**Features**]{style="font-weight:bold; color:#000090"} |
+---------------------------------------------------------+---------------------------------------------------------+
| Mild                                                    | \<30 degrees                                            |
+---------------------------------------------------------+---------------------------------------------------------+
| Moderate                                                | 30-50 degrees                                           |
+---------------------------------------------------------+---------------------------------------------------------+
| Severe                                                  | \>50 degrees                                            |
+---------------------------------------------------------+---------------------------------------------------------+

[Lateral Epiphyseal angle of affected side minus that of unaffected side]{style="font-style:italic"}
:::

`image`

## Talar Neck Fractures -- Hawkins

::: callout
+:------------------------------------------------+:----------------------------------------------------+:------------------------------------------------+:-----------------------------------------------------+:--------------------------------------------------+
| [Type]{style="font-weight:bold; color:#000090"} | [Features]{style="font-weight:bold; color:#000090"} | [AVN ]{style="font-weight:bold; color:#000090"} | [Non]{style="font-weight:bold; color:#000090"}       | [STJ]{style="font-weight:bold; color:#000090"}    |
|                                                 |                                                     |                                                 |                                                      |                                                   |
|                                                 |                                                     |                                                 | [**Union**]{style="font-weight:bold; color:#000090"} | [**OA**]{style="font-weight:bold; color:#000090"} |
+-------------------------------------------------+-----------------------------------------------------+-------------------------------------------------+------------------------------------------------------+---------------------------------------------------+
| [1]{style="font-weight:bold"}                   | Undisplaced                                         | 10%                                             | 2%                                                   | 25%                                               |
+-------------------------------------------------+-----------------------------------------------------+-------------------------------------------------+------------------------------------------------------+---------------------------------------------------+
| [2]{style="font-weight:bold"}                   | Displaced with STJ subluxation                      | 50%                                             | 8%                                                   | 65%                                               |
+-------------------------------------------------+-----------------------------------------------------+-------------------------------------------------+------------------------------------------------------+---------------------------------------------------+
| [3]{style="font-weight:bold"}                   | Displaced with STJ & Ankle subluxation              | 90%                                             | 10%                                                  | 70%                                               |
+-------------------------------------------------+-----------------------------------------------------+-------------------------------------------------+------------------------------------------------------+---------------------------------------------------+
| [4]{style="font-weight:bold"}                   | Displaced with STJ, TTJ & TNJ subluxation           | 100%                                            | 20%                                                  | 90%                                               |
+-------------------------------------------------+-----------------------------------------------------+-------------------------------------------------+------------------------------------------------------+---------------------------------------------------+
:::

## Discoid Meniscus

::: callout
+---------------+---------------------------------------------+
| Type          | Features                                    |
+---------------+---------------------------------------------+
| 1             | I ncomplete                                 |
+---------------+---------------------------------------------+
| 2             | Complete                                    |
+---------------+---------------------------------------------+
| 3             | Wrisberg Variant                            |
|               |                                             |
|               | Only attachment is meniscofemoral ligaments |
|               |                                             |
|               | Ammenable to repair                         |
+---------------+---------------------------------------------+
:::

## Meniscal Tears -- tear pattern

::: callout
+-----------------------------------------------------+------------------------------------------------------+------------------------------------------------------+
| [Pattern]{style="font-weight: bold; color:#000090"} | [Subtypes]{style="font-weight: bold; color:#000090"} | [Features]{style="font-weight: bold; color:#000090"} |
+-----------------------------------------------------+------------------------------------------------------+------------------------------------------------------+
| Vertical                                            | Longitudinal (Bucket Handle)                         | Perpendicular to meniscal fibres                     |
|                                                     |                                                      |                                                      |
|                                                     | Radial                                               | Bucket handles propogate longitudinally              |
|                                                     |                                                      |                                                      |
|                                                     |                                                      | Radial tears are often peripheral                    |
+-----------------------------------------------------+------------------------------------------------------+------------------------------------------------------+
| Horizontal                                          | Full Cleavage                                        | Under surface is torn without                        |
+-----------------------------------------------------+------------------------------------------------------+------------------------------------------------------+
|                                                     | Partial Cleavage                                     | exiting at edge                                      |
|                                                     |                                                      |                                                      |
|                                                     |                                                      | Results in a flap tear (most common)                 |
+-----------------------------------------------------+------------------------------------------------------+------------------------------------------------------+
| Complex                                             | Combinations of the above patterns                   |                                                      |
+-----------------------------------------------------+------------------------------------------------------+------------------------------------------------------+
:::

## Adult Hip Dysplasia -- Crowe

::: callout
-   [Degree of superior lateral femoral head migration]{style="font-family:Arial, sans-serif"}
-   [Based on ratio of:]{style="font-family:Arial, sans-serif"}
-   [Vertical distance from inter-teardrop line to head neck junction : height of opposite femoral head]{style="font-family:Arial, sans-serif"}
-   [If opposite head deformed use 20% of vertical pelvic height]{style="font-family:Arial, sans-serif"}

+:------------------------------------------------+:----------------------------------------------------+
| [Type]{style="font-weight:bold; color:#000090"} | [Features]{style="font-weight:bold; color:#000090"} |
+-------------------------------------------------+-----------------------------------------------------+
| [1]{style="font-weight:bold"}                   | \<50%                                               |
+-------------------------------------------------+-----------------------------------------------------+
| [2]{style="font-weight:bold"}                   | 50-75%                                              |
+-------------------------------------------------+-----------------------------------------------------+
| [3]{style="font-weight:bold"}                   | 75-100%                                             |
+-------------------------------------------------+-----------------------------------------------------+
| [4]{style="font-weight:bold"}                   | \>100% migration                                    |
+-------------------------------------------------+-----------------------------------------------------+
:::

## Classification of Tibial Bone Defects in TKR

::: callout
+--------------+--------------------------------+--------------------------------------------+
| Type         | Features                       | Management                                 |
+--------------+--------------------------------+--------------------------------------------+
| Type 1       | \<1cm focal defect             | Fill with cement                           |
|              |                                |                                            |
|              | Cortical rim intact            | Correct alignment to avoid stress on graft |
+--------------+--------------------------------+--------------------------------------------+
| Type 2       | Bigger metaphyseal defect      | Cancellous Autograft & cement              |
|              |                                |                                            |
|              | Contained defect               | Correct alignment to avoid stress on graft |
|              |                                |                                            |
|              | Cortical rim intact            |                                            |
+--------------+--------------------------------+--------------------------------------------+
| Type 3       | Uncontained metaphyseal defect | Cement around screws                       |
|              |                                |                                            |
|              | No cortical rim intact         | Metallic augments                          |
|              |                                |                                            |
|              |                                | Allograft                                  |
|              |                                |                                            |
|              |                                | Metaphyseal sleeves                        |
|              |                                |                                            |
|              |                                | Revision stems                             |
+--------------+--------------------------------+--------------------------------------------+
:::

## Knee Dislocation - Schenk

::: callout
+---------------------------------------------------+------------------------------------------------------+
| [Stage]{style="fon t-weight:bold; color:#000090"} | [Features]{style="fon t-weight:bold; color:#000090"} |
+---------------------------------------------------+------------------------------------------------------+
| [KD1]{style="fon t-weight:bold"}                  | ACL or PCL (very rare)                               |
+---------------------------------------------------+------------------------------------------------------+
| [KD2]{style="fon t-weight:bold"}                  | ACL & PCL only                                       |
+---------------------------------------------------+------------------------------------------------------+
| [KD3M]{style="fon t-weight:bold"}                 | ACL, PCL & MCL                                       |
+---------------------------------------------------+------------------------------------------------------+
| [KD3L]{style="fon t-weight:bold"}                 | ACL, PCL & LCL                                       |
+---------------------------------------------------+------------------------------------------------------+
| [KD4]{style="fon t-weight:bold"}                  | ACL, PCL, MCL, LCL                                   |
+---------------------------------------------------+------------------------------------------------------+
| [KD5]{style="fon t-weight:bold"}                  | Fracture Dislocation                                 |
+---------------------------------------------------+------------------------------------------------------+
:::

## Clavicle Fractures -- Neer

::: callout
+-------------+------------------------------------------------------------------------+
| Type        | Features                                                               |
+-------------+------------------------------------------------------------------------+
| Type 1      | Middle 1/3                                                             |
+-------------+------------------------------------------------------------------------+
| Type 2      | Distal 1/3                                                             |
+-------------+------------------------------------------------------------------------+
| Type 3      | Proximal 1/3                                                           |
+-------------+------------------------------------------------------------------------+
| 2a          | Minimally displaced                                                    |
+-------------+------------------------------------------------------------------------+
| 2b          | [Displaced -- fracture medial to CC ligaments]{style="colo r:#000090"} |
|             |                                                                        |
|             | [Further subdivided int]{style="colo r:#000090"}o                      |
|             |                                                                        |
|             | [Both CC ligaments intact]{style="colo r:#000090"}                     |
|             |                                                                        |
|             | [Conoid torn, trapezoid intact]{style="colo r:#000090"}                |
+-------------+------------------------------------------------------------------------+
| 2c          | Intra-articular -- both CC ligaments tend to be torn                   |
+-------------+------------------------------------------------------------------------+
| 2d          | Paediatric periosteal sleeve avulsion                                  |
+-------------+------------------------------------------------------------------------+
| 2e          | Comminuted                                                             |
+-------------+------------------------------------------------------------------------+
| 3a-e        | Same system as for type 2 fractures                                    |
+-------------+------------------------------------------------------------------------+
:::

## Graf classification of DDH 

::: callout
Based on Alpha angle and femoral head position

+---------------+----------------------------------+----------------------------+
| Type          | Alpha angle                      | Features                   |
+---------------+----------------------------------+----------------------------+
| 1             | \>60 degrees                     | Normal enlocated hip       |
+---------------+----------------------------------+----------------------------+
| 2             | 43-60 degrees                    | Borderline group           |
|               |                                  |                            |
|               |                                  | May or may not be abnormal |
|               |                                  |                            |
|               |                                  | Needs repeat scan          |
+---------------+----------------------------------+----------------------------+
| 3             | \<43 degrees & labrum everted    | Hip subluxated             |
+---------------+----------------------------------+----------------------------+
| 4             | \<43 degrees & labrum interposed | Hip dislocated             |
+---------------+----------------------------------+----------------------------+
:::

## Denis -- 3 Column Theory of Spinal Stability

::: callout
+-----------------------+-----------------------------------------------+
| Fracture Type         | Columns Affected                              |
+-----------------------+-----------------------------------------------+
| Compression           | Anterior column only                          |
|                       |                                               |
|                       | Co mpression failure                          |
+-----------------------+-----------------------------------------------+
| \[Flexion Distraction | Middle and Posterior tension failure          |
|                       |                                               |
|                       | Anterior column intact as a hinge             |
+-----------------------+-----------------------------------------------+
| Burst                 | Anterior & Middle column co mpression failure |
+-----------------------+-----------------------------------------------+
| Fracture Dislocation  | All three columns disrupted                   |
+-----------------------+-----------------------------------------------+

**Anterior Column**: ALL, Anterior 2/3 vertebral body and disc

[Middle Column:]{style="font-weight:bold"} Posterior 1/3 vertebral body and disc, PLL

[**Posterior Column:**]{style="font-weight:bold"} Neural arches
:::

## Swanson's Classification of Congenital Anomalies

::: callout
+---------------------------------------------------------+------------------------------------------------------+
| [Type]{style="fon t-weight:bold; color:#000090"}        | [Examples]{style="fon t-weight:bold; color:#000090"} |
+---------------------------------------------------------+------------------------------------------------------+
| [Failure of Formation]{style="fon t-weight:bold"}       | Amelia                                               |
|                                                         |                                                      |
| Transverse or longitudinal arrest                       | Radial or Ulna club Hand                             |
|                                                         |                                                      |
| Pre or post axial                                       |                                                      |
+---------------------------------------------------------+------------------------------------------------------+
| [Failure of Differentiation]{style="fon t-weight:bold"} | Syndactyly                                           |
|                                                         |                                                      |
| Bony or Soft tissue                                     | Camptodactyly                                        |
|                                                         |                                                      |
|                                                         | Clinodactyly                                         |
+---------------------------------------------------------+------------------------------------------------------+
| [Duplication]{style="fon t-weight:bold"}                | Polydactyly                                          |
|                                                         |                                                      |
| Pre or post axial                                       | Thumb duplication                                    |
+---------------------------------------------------------+------------------------------------------------------+
| [Overgrowth]{style="fon t-weight:bold"}                 | Hyperplasia                                          |
+---------------------------------------------------------+------------------------------------------------------+
| [Undergrowth]{style="fon t-weight:bold"}                | Hypoplasia                                           |
+---------------------------------------------------------+------------------------------------------------------+
| [Constriction Bands]{style="fon t-weight:bold"}         |                                                      |
+---------------------------------------------------------+------------------------------------------------------+
| [Generalised syndromes]{style="fon t-weight:bold"}      | Madelung's                                           |
+---------------------------------------------------------+------------------------------------------------------+
:::

## Wassel's Classification of Thumb Duplications

::: callout
+--------------------------------------------------+------------------------------------------------------+
| [Type]{style="fon t-weight:bold; color:#000090"} | [Features]{style="fon t-weight:bold; color:#000090"} |
+--------------------------------------------------+------------------------------------------------------+
| [1]{style="fon t-weight:bold"}                   | Bifid P3                                             |
+--------------------------------------------------+------------------------------------------------------+
| [2]{style="fon t-weight:bold"}                   | Duplicated P3                                        |
+--------------------------------------------------+------------------------------------------------------+
| [3]{style="fon t-weight:bold"}                   | Bifid P2                                             |
+--------------------------------------------------+------------------------------------------------------+
| [4]{style="fon t-weight:bold"}                   | Duplicated P2 (most common)                          |
+--------------------------------------------------+------------------------------------------------------+
| [5]{style="fon t-weight:bold"}                   | Bifid P1                                             |
+--------------------------------------------------+------------------------------------------------------+
| [6]{style="fon t-weight:bold"}                   | Duplicated P1                                        |
+--------------------------------------------------+------------------------------------------------------+
| [7]{style="fon t-weight:bold"}                   | Triphalangism                                        |
+--------------------------------------------------+------------------------------------------------------+
:::

## Classification of Articular Cartilage Degeneration (Jackson)

::: callout
+---------------+-----------------------------------------------------+
| Grade         | Features                                            |
+---------------+-----------------------------------------------------+
| 1             | Softening                                           |
+---------------+-----------------------------------------------------+
| 2             | Fibrillation and fissuring                          |
+---------------+-----------------------------------------------------+
| 3             | Partial thickness defects with flaps and clefts     |
+---------------+-----------------------------------------------------+
| 4             | Full Thickness defects with exposed subchodral bone |
+---------------+-----------------------------------------------------+
:::

## Lauge Hansen Classification of Ankle Fractures

::: callout
[Based on Position of foot and rotation of talus at injury]{style="font-style:italic; color:#000090"}

+------------------------------+----------------------------------------------------------------------------------------+
| Mechanism                    | Features                                                                               |
+------------------------------+----------------------------------------------------------------------------------------+
| Supination External Rotation | AITFL or Chaput fragment                                                               |
|                              |                                                                                        |
|                              | Oblique Weber B Fibula Fracture in a posterior superior to anterior inferior direction |
|                              |                                                                                        |
|                              | PITFL or Posterior Malleolus Fracture                                                  |
|                              |                                                                                        |
|                              | Medial Malleolar T ransverse Fracture                                                  |
+------------------------------+----------------------------------------------------------------------------------------+
| Supination Adduction         | T ransverse Weber A fibula fracture                                                    |
|                              |                                                                                        |
|                              | Vertical Medial Malleolar Fracture                                                     |
+------------------------------+----------------------------------------------------------------------------------------+
| Pronation External Rotation  | Medial Malleolus Fracture                                                              |
|                              |                                                                                        |
|                              | AITFL or Chaput                                                                        |
|                              |                                                                                        |
|                              | Oblique/spiral Weber C fracture in anterior superior to posterior inferior direction   |
|                              |                                                                                        |
|                              | PITFL or Posterior Malleolus Fracture                                                  |
+------------------------------+----------------------------------------------------------------------------------------+
| Pronation Abduction\]        | T ransverse Medial Malleolar Fracture                                                  |
|                              |                                                                                        |
|                              | AITFL, PITFL or Chaput                                                                 |
|                              |                                                                                        |
|                              | Simple or Butterfly Weber C (bending injury)                                           |
+------------------------------+----------------------------------------------------------------------------------------+
:::

## Paprosky Classification of Femoral Defects

::: callout
+--------------------------------------------------+-------------------------------------------------------------+
| [Type]{style="fon t-weight:bold; color:#000090"} | [Features]{style="fon t-weight:bold; color:#000090"}        |
+--------------------------------------------------+-------------------------------------------------------------+
| [1]{style="fon t-weight:bold"}                   | Minimal Metaphyseal bone loss                               |
|                                                  |                                                             |
|                                                  | Normal Diaphyseal bone stock                                |
+--------------------------------------------------+-------------------------------------------------------------+
| [2]{style="fon t-weight:bold"}                   | Moderate Metaphyseal bone loss                              |
|                                                  |                                                             |
|                                                  | Normal Diaphyseal bone stock                                |
+--------------------------------------------------+-------------------------------------------------------------+
| [3a]{style="fon t-weight:bold"}                  | Significant metaphyseal bone loss                           |
|                                                  |                                                             |
|                                                  | Diaphyseal bone loss with \>4cm isthmus for fixation        |
+--------------------------------------------------+-------------------------------------------------------------+
| [3b]{style="fon t-weight:bold"}                  | Significant metaphyseal bone loss                           |
|                                                  |                                                             |
|                                                  | Diaphyseal bone loss with \<4cm isthmus for fixation        |
+--------------------------------------------------+-------------------------------------------------------------+
| [4]{style="fon t-weight:bold"}                   | Inadequate diaphyseal bone for long stem fixation           |
|                                                  |                                                             |
|                                                  | Only type where a long uncemented porous stem can't be used |
+--------------------------------------------------+-------------------------------------------------------------+
:::

## Paprosky Classification of Acetabular Defects

::: callout
### Based on migration, bone loss on AP and cup stability intra-operatively

+--------------------------------------------------+-------------------------------------------------------------------+
| [Type]{style="fon t-weight:bold; color:#000090"} | [Features]{style="fon t-weight:bold; color:#000090"}              |
+--------------------------------------------------+-------------------------------------------------------------------+
| [1]{style="fon t-weight:bold"}                   | Minimal Bone loss; Minimal migration; Fully stable cup            |
+--------------------------------------------------+-------------------------------------------------------------------+
| [2a]{style="fon t-weight:bold"}                  | Superior migration                                                |
|                                                  |                                                                   |
|                                                  | Superior Bone loss                                                |
|                                                  |                                                                   |
|                                                  | Stable cup                                                        |
|                                                  |                                                                   |
|                                                  | Rest of Acetabulum ok                                             |
+--------------------------------------------------+-------------------------------------------------------------------+
| [2b]{style="fon t-weight:bold"}                  | Superior migration                                                |
|                                                  |                                                                   |
|                                                  | Uncontained superior bone defect                                  |
|                                                  |                                                                   |
|                                                  | \>50% bone contact                                                |
|                                                  |                                                                   |
|                                                  | Stable cup                                                        |
+--------------------------------------------------+-------------------------------------------------------------------+
| [2c]{style="fon t-weight:bold"}                  | Medial migration past kohlers line                                |
|                                                  |                                                                   |
|                                                  | Uncontained medial defect                                         |
|                                                  |                                                                   |
|                                                  | Stable cup                                                        |
|                                                  |                                                                   |
|                                                  | \>50% contact                                                     |
+--------------------------------------------------+-------------------------------------------------------------------+
| [3a]{style="fon t-weight:bold"}                  | Superior migation                                                 |
|                                                  |                                                                   |
|                                                  | Moderate ischial, teardrop lysis                                  |
|                                                  |                                                                   |
|                                                  | No significant medial migration                                   |
|                                                  |                                                                   |
|                                                  | Partial stability of cup                                          |
|                                                  |                                                                   |
|                                                  | 40% contact                                                       |
+--------------------------------------------------+-------------------------------------------------------------------+
| [3b]{style="fon t-weight:bold"}                  | Large uncontained defects                                         |
|                                                  |                                                                   |
|                                                  | Significantly migrated cup -- superior or medial to kohler's line |
|                                                  |                                                                   |
|                                                  | Bone contact \<40%                                                |
|                                                  |                                                                   |
|                                                  | Risk of pelvic discontinuity                                      |
|                                                  |                                                                   |
|                                                  | Unstable cup                                                      |
+--------------------------------------------------+-------------------------------------------------------------------+
:::

::: column-margin
*this contend is inspired by Revision notes by Phadnis J*
:::
