---
title: "Published articles"
---

1.  Abductor pollicis longus tendon division with swan neck thumb deformity [link](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3535130/pdf/11751_2012_Article_141.pdf)

2.  Gluteal abscess: diagnostic challenges and management [Link](https://jidc.org/index.php/journal/article/view/20539067/395)

3.  Expressing Cobb Angle as Linear Measurement in Scoliosis and Its Significance: A Clinical and Geometrical Analysis of Scoliosis [Link](https://www.e-neurospine.org/journal/view.php?doi=10.14245/kjs.2017.14.4.139)

4.  Is calcar referenced tip-apex distance a better predicting factor for cutting out in biaxial cephalomedullary nails than tip-apex distance? [Link](https://journals.sagepub.com/doi/epub/10.1177/2309499017727920)

5.  Acute Isolated Dorsal Midtarsal (Chopart's) Dislocation: A Case Report [Link](https://www.jfas.org/article/S1067-2516(09)00108-2/abstract)

6.  Gorham's disease of the fibula: a case report [Link](https://www.jfas.org/article/S1067-2516(09)00005-2/abstract)

7.  A New Surgical Technique for Extensive Exposure of the Proximal Humerus and Shoulder [Link](https://onlinelibrary.wiley.com/doi/epdf/10.1111/os.12072)

8.  Management of Giant Cell Tumor of Bone:Computerized Tomography Based Selection Strategy and Approaching the Lesion Through the Site of Cortical Break [Link](https://onlinelibrary.wiley.com/doi/epdf/10.1111/j.1757-7861.2012.00172.x)

9.  Multicentric epithelioid angiosarcoma of the spine: a case report of a rare bone tumor [Link](https://www.thespinejournalonline.com/article/S1529-9430(06)00909-0/abstract)

10. Onsite virtual classroom for undergraduate medical education [Link](https://journals.lww.com/kjor/fulltext/2023/02020/onsite_virtual_classroom_for_undergraduate_medical.4.aspx)
