---
title: "Previous year questions"
format: html
editor: visual
---

# MS ortho

## 2012-15

### **Basic Science**

#### **Essay Questions**

1.  Describe the extensor mechanism of the knee joint. Discuss the aetiology, diagnosis, and management of recurrent dislocation of the patella. (June 2012)
2.  Discuss briefly the blood supply of the talus. Describe in detail the clinical features, classification, and management of talus fracture. (May 2013)

#### **Short Notes**

1.  Growth plate anatomy and its functions (June 2012)
2.  Differentiate between osteopenia and osteoporosis (June 2012)
3.  Glasgow coma scale (June 2012)
4.  Methotrexate (June 2012)
5.  Adult respiratory distress syndrome (June 2012)
6.  Transfusion reactions (June 2012)
7.  Types of biopsy (June 2012)
8.  Vitamin D resistant rickets (May 2013)
9.  Hyaline cartilage (May 2013)
10. Joint lubrication (May 2013)
11. DVT prophylaxis (May 2013)
12. Duchenne muscular dystrophy (May 2013)
13. Discoid meniscus (May 2013)
14. Hamilton Russel traction (May 2013)
15. Myositis ossificans (May 2013)

------------------------------------------------------------------------

### **Orthopaedic Disease**

#### **Essay Questions**

1.  Define osteoporosis, discuss the clinical features, causes, and management of generalized osteoporosis. (June 2012)
2.  Discuss the pathogenesis, clinical features, and management of tuberculosis of the spine with paraplegia. (May 2013)
3.  Describe the etiology, modern diagnostic methods, prevention, and the various management methods for osteoporosis. (May 2013)

#### **Short Notes**

1.  Chordoma (June 2012)
2.  Arthrogryposis multiplex congenita (June 2012)
3.  Congenital pseudoarthrosis of the tibia (June 2012)
4.  Hallux valgus (June 2012)
5.  DOTS regime for tuberculosis (June 2012)
6.  Solid ankle cushion heel foot (June 2012)
7.  Vertebra plana (June 2012)
8.  Ulnar claw hand (June 2012)
9.  Radiological features of Perthes disease (May 2013)
10. Spina ventosa (May 2013)
11. Foot drop (May 2013)
12. Chondrocalcinosis (May 2013)
13. Meniscal cyst (May 2013)
14. Multiple myeloma (May 2013)
15. Sever’s disease (May 2013)
16. Myositis ossificans progressiva (May 2013)
17. Positron emission tomography (May 2013)
18. Methicillin-resistant Staphylococcus aureus (May 2013)
19. Floor reaction orthosis (May 2013)
20. Endoscopic disc surgery (May 2013)
21. Immunomodulators in rheumatoid arthritis (May 2013)
22. Bioabsorbable implants (May 2013)
23. Chemotherapy for osteosarcoma (May 2013)

------------------------------------------------------------------------

### **Trauma**

#### **Essay Questions**

1.  Explain the biomechanics of the thoracolumbar spine. Classify and discuss the management of thoracolumbar spine injuries. (June 2012)
2.  Explain the anatomy of the brachial plexus. Classify and discuss in detail the management of brachial plexus injury. (May 2013)

#### **Short Notes**

1.  Recurrent dislocation of the shoulder (June 2012)
2.  Pubic diastasis (June 2012)
3.  Dunlop traction (June 2012)
4.  McMurray’s osteotomy (June 2012)
5.  Locked compression plate (June 2012)
6.  Neglected tendoachilles injury (June 2012)
7.  Odontoid fracture (June 2012)
8.  Crutch gait (June 2012)
9.  Scapular fracture (May 2013)
10. PCL deficient knee (May 2013)
11. Scaphoid non-union (May 2013)
12. Damage control in orthopaedics (May 2013)
13. Chance’s fracture (May 2013)
14. Automatic bladder (May 2013)
15. Jumper’s knee (May 2013)
16. Malgaigne fracture (May 2013)

------------------------------------------------------------------------

### **Recent Advances**

#### **Essay Questions**

1.  What is osteosynthesis? Describe ways to achieve osteosynthesis in the treatment of fractures with recent advances. (June 2012)
2.  With regard to slipped capital femoral epiphysis, discuss:
    -   Prediction of contralateral slip
    -   Treatment updates
    -   Femoro-acetabular impingement associated with it. (June 2015)

#### **Short Notes**

1.  Bearing surfaces in total hip replacement (June 2012)
2.  Zoledronic acid (June 2012)
3.  Tumour markers (June 2012)
4.  Femoro-acetabular impingement (June 2012)
5.  Bone cement (June 2012)
6.  DEXA scan (June 2012)
7.  Proximal femoral nail (June 2012)
8.  Postoperative DVT - prevention, clinical features, and management (June 2012)
9.  Simple bone cyst (June 2015)
10. Stem cells in orthopaedics (June 2015)
11. Poller screw (June 2015)
12. Recent advances in internal fixation of distal tibial fractures (June 2015)
13. Bearing surface in total hip arthroplasty (June 2015)
14. Fresh frozen allograft (June 2015)
15. Multidirectional instability of the shoulder (June 2015)
16. Advances in anterior cruciate ligament reconstruction (June 2015)

# 2015-18

### **Basic Science**

#### **Essay Questions**

1.  Describe the anatomy of the iliotibial tract. Discuss disorders associated with it. (Nov 2015)
2.  Discuss synovial fluid analysis. Also describe the changes that occur (synovial fluid) in various pathological conditions of the knee. (June 2016)
3.  Discuss the microscopic structure of articular cartilage and the changes seen in osteoarthrosis of a weight-bearing joint. (Nov 2016)
4.  Describe systemic response to trauma. Discuss classification and management of shock due to trauma. (May 2017)
5.  Discuss the pathogenesis of non-traumatic avascular necrosis of the head of the femur in the adult. Discuss the role of non-surgical management in avascular necrosis. (Nov 2017)
6.  Describe the anatomy of the intervertebral disc. Explain the pathogenesis, clinical features, and management of a prolapsed intervertebral disc between L4 and L5 vertebrae in a young adult. (April 2018)

#### **Short Notes**

1.  Mechanism of tumour spread (local and distant) (Nov 2015)
2.  Patho-mechanism of compartment syndrome (Nov 2015)
3.  Anatomical factors contributing to knee stability (Nov 2015)
4.  Pain management in orthopaedics (Nov 2015)
5.  Imaging features of osteo-articular tuberculosis (Nov 2015)
6.  Normal calcium metabolism (Nov 2015)
7.  Safe surgical practice in orthopaedics (Nov 2015)
8.  Hyperparathyroidism (Nov 2015)
9.  Articular cartilage (June 2016)
10. Ortolani test (June 2016)
11. Giant cell variants (June 2016)
12. NCV (nerve conduction velocity) (June 2016)
13. Bracing in Ponseti technique of clubfoot management (June 2016)
14. Madelung deformity (June 2016)
15. Charcot’s joint (June 2016)
16. HIV in orthopaedics (June 2016)
17. CPPD (Calcium pyrophosphate dihydrate) arthropathy (Nov 2016)
18. Anatomy of the brachial plexus (Nov 2016)
19. Congenital radio-ulnar synostosis (Nov 2016)
20. Blood supply of the femoral head (Nov 2016)
21. TENS (Transcutaneous electrical nerve stimulation) (Nov 2016)
22. Floor reaction orthosis (Nov 2016)
23. Myositis ossificans (Nov 2016)
24. Tension band principle (Nov 2016)
25. Histopathology of osteosarcoma (May 2017)
26. Muscle spasticity and its medical management (May 2017)
27. Anatomical factors contributing to shoulder stability (May 2017)
28. Bisphosphonates (May 2017)
29. Informed consent for orthopaedic surgery (May 2017)
30. Bone mineralisation (May 2017)
31. Surgical site infection (May 2017)
32. Renal tubular acidosis (May 2017)
33. Anatomy of the growth plate (Nov 2017)
34. Tumour markers in orthopaedics (Nov 2017)
35. Uric acid metabolism in gout (Nov 2017)
36. Hyponatremia in orthopaedic patients (Nov 2017)
37. Level of evidence in clinical research (Nov 2017)
38. Anatomy of the fibrous flexor sheath of the finger (Nov 2017)
39. Lubrication of synovial joints (Nov 2017)
40. Neurogenic bladder (Nov 2017)
41. Gas gangrene (April 2018)\*
42. Bone remodelling (April 2018)
43. Drugs for gout (April 2018)\*
44. Compartments of the leg (April 2018)
45. Nerve conduction study (April 2018)\*
46. Bisphosphonates (April 2018)\*
47. Auto transfusion (April 2018)
48. Prevention of deep vein thrombosis (April 2018)

------------------------------------------------------------------------

### **Orthopaedic Disease**

#### **Essay Questions**

1.  Discuss the clinical features and management of tuberculosis of the spine at the dorso-lumbar junction with neurological deficit. (Nov 2015)
2.  Discuss in detail the characteristics of synovial fluid and its role in the diagnosis of common joint disorders. (June 2016)
3.  Classify cerebral palsy. Discuss the biomechanics of crouch gait in cerebral palsy. Outline the management of crouch gait. (Nov 2016)
4.  Classify bone tumours based on the cell of origin. Discuss the management of osteosarcoma in a 10-year-old. Add a note on limb salvage surgery. (May 2017)
5.  Discuss the pathophysiology, diagnosis, complications, and management of osteoporosis. (Nov 2017)
6.  Discuss the pathophysiology, clinical features, and diagnostic evaluation of lumbar canal stenosis. Discuss the surgical management of lumbar canal stenosis. (April 2018)

#### **Short Notes**

1.  Factors influencing bone graft incorporation (Nov 2015)
2.  Accessory navicular (Nov 2015)
3.  Knee in cerebral palsy (Nov 2015)
4.  Aneurysmal bone cyst (Nov 2015)
5.  Radial club hand (Nov 2015)
6.  Management of metastatic disease of bone (Nov 2015)
7.  Crystal-induced arthropathy (Nov 2015)
8.  Fungal osteomyelitis (Nov 2015)
9.  Osteogenesis imperfecta (June 2016)
10. Hallux valgus (June 2016)
11. Management of infected total knee replacement (June 2016)
12. Bone grafting (June 2016)
13. Congenital vertical talus (June 2016)
14. Hyperparathyroidism (June 2016)\*
15. Osteochondroma (June 2016)
16. Trendelenburg’s test (June 2016)
17. Cold abscess (Nov 2016)
18. Metatarsus adductus (Nov 2016)
19. Flat foot (Nov 2016)
20. Syndactyly (Nov 2016)
21. Gas gangrene (Nov 2016)\*
22. Radial club hand (Nov 2016)\*
23. Giant cell variants (Nov 2016)\*
24. Fibular hemimelia (Nov 2016)
25. Systemic diseases predisposing to bone infection (May 2017)
26. Skew foot (May 2017)
27. Dysplasia epiphysialis hemimelica (May 2017)
28. Degenerative lumbar intervertebral disc disease (May 2017)
29. Surgical management of chronic osteomyelitis (May 2017)
30. Hemophilic knee (May 2017)
31. Ivory vertebra (May 2017)
32. Sprengel deformity (May 2017)
33. Treatment guidelines for adolescent idiopathic scoliosis (Nov 2017)
34. Fibrous dysplasia (Nov 2017)
35. Spina ventosa (Nov 2017)
36. Management of metastatic bone disease (Nov 2017)\*
37. Jump gait in cerebral palsy (Nov 2017)
38. Tendon transfer in ulnar claw hand (Nov 2017)
39. Coxa saltans (Nov 2017)
40. Management of relapsed CTEV (Nov 2017)
41. Bone biopsy (April 2018)
42. Myositis ossificans (April 2018)\*
43. Proximal focal femoral deficiency (April 2018)
44. Differential diagnosis of heel pain (April 2018)
45. Lambrinudi’s arthrodesis (April 2018)
46. Blount’s disease (April 2018)
47. Neuropathic joint (April 2018)
48. Guided growth (April 2018)

------------------------------------------------------------------------

### **Trauma**

#### **Essay Questions**

1.  Classify the dislocation of the elbow joint. Discuss the management of different types of posterior dislocation of the elbow and enumerate the complications. (Nov 2015)
2.  Classify calcaneal fractures and discuss the management of different types of calcaneal fractures. (June 2016)
3.  Describe carpal instability in detail and discuss the management of a 30-year-old patient with a 2-month-old untreated perilunate dislocation. (Nov 2016)
4.  Describe the aetiopathology and clinical features of traumatic knee dislocation. Discuss its management. (May 2017)
5.  Discuss the role of the anterior cruciate ligament (ACL) in stabilizing the knee. Describe the clinical features of an ACL-deficient knee. Discuss the surgical management of this condition. How does treatment differ in paediatric ACL injuries? (Nov 2017)
6.  Classify tibial plateau fractures and discuss their management. (April 2018)

#### **Short Notes**

1.  Dupuytren’s contracture (Nov 2015)
2.  Bennett’s fracture (Nov 2015)
3.  Crush syndrome (Nov 2015)
4.  Essex-Lopresti fracture (Nov 2015)
5.  Bankart lesion (Nov 2015)
6.  Phantom limb (Nov 2015)
7.  Pedicular screw fixation (Nov 2015)
8.  Stove-in chest (Nov 2015)
9.  Hoffa’s fracture (June 2016)
10. Gamekeeper’s thumb (June 2016)
11. Stress shielding in compression fixation (June 2016)
12. Tillaux fracture (June 2016)
13. Treatment of DVT (June 2016)
14. MIPPO technique (June 2016)
15. Management of infected non-union of the tibia (June 2016)
16. Flail chest (June 2016)
17. Jefferson’s fracture (Nov 2016)
18. Bennett’s fracture (Nov 2016)\*
19. JESS (Nov 2016)
20. Lag screw principle (Nov 2016)
21. Fish tail deformity of the distal humerus (Nov 2016)
22. Crush syndrome (Nov 2016)\*
23. Fracture disease (Nov 2016)
24. Lisfranc fractures (Nov 2016)
25. Comparison of techniques of internal fixation of femoral trochanteric fractures (May 2017)
26. Pre-hospital care in polytrauma (May 2017)
27. Injury severity score (May 2017)
28. Radial neck fractures in children (May 2017)
29. Wound debridement in open fractures (May 2017)
30. Damage control surgery (May 2017)
31. Tillaux fracture (May 2017)\*
32. Skeletal trauma in child abuse (May 2017)
33. Lisfranc injuries (Nov 2017)\*
34. Principles of locking plate (Nov 2017)
35. Carpal instability (Nov 2017)\*
36. Scapulo-thoracic dissociation (Nov 2017)
37. Atlanto-axial rotary subluxation (Nov 2017)
38. Lateral condyle humerus fracture in a child (Nov 2017)
39. Traumatic upper brachial plexus injuries (Nov 2017)
40. Meniscal repair (Nov 2017)
41. Fracture clavicle (April 2018)
42. Classify lateral condyle fracture of the humerus and discuss the management of non-union of the lateral condyle (April 2018)
43. Scaphoid fracture (April 2018)
44. Odontoid fracture (April 2018)
45. Management of transcervical fracture neck of femur in a 45-year-old individual (April 2018)
46. Management of fracture talus (April 2018)
47. Conservative management of fracture midshaft tibia and discuss the management of compartment syndrome (April 2018)
48. Principles of surgical management of recurrent dislocation of the shoulder (April 2018)

------------------------------------------------------------------------

### **Recent Advances**

#### **Essay Questions**

1.  Classify meniscal injuries of the knee. Discuss the aetiology, assessment, and management of this injury in a young sportsman. Enumerate the recent advances in the management. (June 2016)
2.  Discuss the current status of articular cartilage transplantation and autologous chondrocyte implantation. (Nov 2016)
3.  Discuss the radioisotopes and their role in orthopaedics. (May 2017)
4.  Discuss the management of painful total hip replacement. What are the issues involved in revision surgery of total hip arthroplasty? Discuss the management of acetabular bone loss. (Nov 2017)
5.  Describe the recent advances in the diagnosis and management of skeletal tuberculosis. What are the latest guidelines in the medical management of tuberculosis? Discuss newer anti-tuberculosis drugs. (April 2018)
6.  With regard to total hip replacement, discuss:
    -   Classification of periprosthetic fractures and their management
    -   Diagnosis of periprosthetic infection and its management (Nov 2015)

#### **Short Notes**

1.  Stem cell therapy (June 2016)
2.  Vertebroplasty (June 2016)
3.  Drug-resistant tuberculosis (June 2016)
4.  Femoro-acetabular impingement (June 2016)
5.  Role of botulinum toxin in orthopaedics (June 2016)
6.  Computer-aided orthopaedic surgery (June 2016)
7.  Trabecular metal (June 2016)
8.  Locked plates (June 2016)
9.  CPM (continuous passive motion) (Nov 2016)
10. Thrombo-prophylaxis in joint replacement (Nov 2016)
11. Bone cement (Nov 2016)
12. Isotope bone scan (Nov 2016)
13. Telescoping rod (Nov 2016)
14. Microdiscectomy (Nov 2016)
15. Hip arthroscopy (Nov 2016)
16. Porous-coated implants (Nov 2016)
17. Balloon kyphoplasty (May 2017)
18. Chinese flap (May 2017)
19. Newer techniques of nerve repair (May 2017)
20. HKAFO (May 2017)
21. Role of stem cells in orthopaedics (May 2017)\*
22. Neoadjuvant chemotherapy (May 2017)
23. Bone bank (May 2017)
24. Vascularised pedicle bone graft (May 2017)
25. Extra-corporeal irradiation for bone tumors (Nov 2017)
26. Reverse shoulder arthroplasty (Nov 2017)
27. Elastic nailing (Nov 2017)
28. Bone morphogenetic protein (Nov 2017)
29. Platelet-rich plasma in orthopaedics (Nov 2017)
30. Double bundle ACL reconstruction (Nov 2017)
31. Modern cementing technique (Nov 2017)
32. Uni-compartmental knee replacement (Nov 2017)
33. Bearing surfaces in total hip replacement (April 2018)
34. Lumbar disc replacement (April 2018)
35. Bone marrow oedema syndrome of the hip (April 2018)
36. Tertiary survey in trauma (April 2018)
37. Negative pressure wound therapy (April 2018)
38. Dynamic stabilization of the spine (April 2018)
39. Prosthetic management of below-elbow amputee of the dominant side (April 2018)
40. Viscosupplementation (April 2018)
41. Floating shoulder (Nov 2015)
42. Techniques of extension of margin in intralesional curettage (Nov 2015)
43. Tennis elbow (Nov 2015)
44. Advances in the management of large open wounds (Nov 2015)
45. Locking compression plate (Nov 2015)
46. Sleeve fracture of the patella (Nov 2015)
47. Fragment-specific fixation of distal radius fracture (Nov 2015)
48. Spinal stabilization (Nov 2015)

## 2018-21

### Basic Science

#### Essay

1.  Describe the biomechanics of hip joint and discuss about different gait patterns in diseases affecting the hip joint. (October 2018)
2.  Describe the pathogenesis of fat embolism. Discuss the diagnosis and management of a patient with fat embolism. (April 2019)
3.  Vitamin D metabolism. Clinical features and investigations in rickets. (October 2019)
4.  What do you mean by ante-version of the femoral neck. How do you determine clinically and radiologically the degree of ante-version of the femoral neck. Discuss its importance in management of developmental dysplasia of the hip in a child aged 5 years. (December 2020)
5.  Surgical anatomy of a synovial joint. Describe the etiopathology, clinical features and management of osteoarthritis knee. (June 2020)
6.  Discuss the factors that influence bone healing after a fracture. What are the causes of non-union. Describe the radiological features. (May 2021)

#### Short Notes

1.  Carpal tunnel (October 2018)\*
2.  Ilio-tibial tract (October 2018)\*
3.  Fracture healing (October 2018)\*
4.  Nutritional rickets (October 2018)\*
5.  Tissue biopsy (October 2018)\*
6.  Thoracic outlet (October 2018)\*
7.  Teriparatide (October 2018)\*
8.  Thrombo prophylaxis (October 2018)\*
9.  Anterolateral ligament of the knee (April 2019)
10. Bone scan (April 2019)
11. Markers of bone formation (April 2019)
12. Biomechanics of anterior cruciate deficient knee (April 2019)
13. Denosumab (April 2019)\*
14. Local adjuvant therapy for benign aggressive tumors (April 2019)
15. Methicillin resistant staphylococcus aureus (April 2019)
16. Informed consent (April 2019)
17. Bone grafting (October 2019)
18. Prospective versus retrospective cohort studies (October 2019)
19. Pathophysiology and diagnosis of compartment syndrome (October 2019)
20. Ibandronic acid (October 2019)
21. Guidelines for prevention of surgical site infection (October 2019)
22. Rheumatoid factor (October 2019)
23. Illofemoral ligament (October 2019)
24. Nerve conduction study (October 2019)
25. Autonomic bladder (December 2020)
26. Arches of the foot (December 2020)
27. Microscopic structure of articular cartilage (December 2020)
28. Second line drugs used rheumatoid arthritis and their mechanism of action (December 2020)
29. Pathology and differential diagnosis of frozen shoulder (December 2020)
30. Calcium balance in the body (December 2020)
31. Anatomy of the lumbar intervertebral disc (December 2020)
32. Normal gait cycle (December 2020)
33. Electromyography (June 2020)
34. Principles of a Randomised Control Trial (June 2020)
35. Fat embolism (June 2020)\*
36. Rifampicin (June 2020)
37. Pre-operative antibiotic prophylaxis (June 2020)
38. Anti CCP Elisa test (June 2020)
39. Lateral collateral ligament of ankle (June 2020)
40. Allograft in orthopaedics (June 2020)
41. Blood supply of talus (May 2021)
42. Structure of growth plate (May 2021)
43. Anatomy of flexor tendons and their sheaths in the index finger (May 2021)
44. Anatomy of the brachial plexus (May 2021)
45. Role of radiograph in diagnosis of causes of backache (May 2021)
46. Vitamin D metabolism (May 2021)\*
47. Fat embolism syndrome (May 2021)\*
48. Pathophysiology of acute Volkmann’s ischemia of the forearm (May 2021)

### Orthopaedic Disease

#### Essay

1.  Discuss the differential diagnosis for painful limp in an 8 years old child. Describe the management of Perthe’s disease. (October 2018)
2.  Classify spondylolisthesis and discuss its management. (April 2019)
3.  Clinical features, management and complications of chronic osteomyelitis of tibia in a 10-year-old child. (October 2019)
4.  Define cervical rib. What are the different types of cervical ribs. Discuss their pathology in relation to the clinical features. How would you treat a case of symptomatic cervical rib. (December 2020)
5.  What do you mean by ‘gout’ & ‘pseudo gout’. Discuss the clinical features and management of gouty arthritis. (June 2020)
6.  Discuss the static and dynamic stabilisers of shoulder joint. Describe the current concepts in management of recurrent shoulder dislocation with and without glenoid bone loss. (May 2021)

#### Short Notes

1.  Vitamin D resistant rickets (October 2018)
2.  Staging of avascular necrosis of head of femur and outline its management (October 2018)
3.  Management of GCT of distal radius (October 2018)
4.  Diagnosis and management of septic arthritis of knee (October 2018)
5.  Madelung deformity (October 2018)
6.  Aneurysmal bone cyst (October 2018)
7.  Crouch gait (October 2018)
8.  Principles of tendon transfer and describe a method for high ulnar nerve palsy (October 2018)
9.  Radio ulnar synostosis (April 2019)
10. Osteomalacia (April 2019)
11. Osteogenesis imperfecta (April 2019)
12. Congenital postero-medial bowing of tibia (April 2019)
13. Rheumatoid hand (April 2019)\*
14. Diagnosis of developmental dysplasia of hip and discuss the management in less than 1-year-old child (April 2019)
15. Chondrosarcoma (April 2019)
16. Kienbock’s disease (April 2019)
17. Foot drop (October 2019)
18. Morrant Baker’s cyst (October 2019)
19. Chondroblastoma (October 2019)
20. Pseudo gout (October 2019)\*
21. Clinical feature and management of unilateral CTEV in a 10 months old child (October 2019)
22. Maffucci syndrome (October 2019)
23. Subacromial impingement syndrome (October 2019)
24. Charcot joint (October 2019)
25. Investigative modalities to assess the severity of osteoporosis (December 2020)
26. Management of relapsed clubfoot (December 2020)
27. Below knee prosthesis (December 2020)
28. Baker’s cyst (December 2020)\*
29. Deformities due to liiotibial band contracture (December 2020)
30. Carpal tunnel syndrome (December 2020)\*
31. Rheumatoid hand (December 2020)\*
32. Wind-swipe deformity (December 2020)
33. Nutritional rickets (June 2020)\*
34. Milwaukee brace (June 2020)
35. Management of spastic diplegia in cerebral palsy (June 2020)
36. Classification of bone tumours (June 2020)
37. Diagnosis of ankylosing spondylitis (June 2020)
38. Stulberg's classification (June 2020)
39. Ankle foot orthosis (June 2020)
40. Differential diagnosis of painful arc syndrome (June 2020)
41. Tarsal coalition (May 2021)
42. Skew foot (May 2021)
43. Flat foot (May 2021)
44. Painful arc syndrome (May 2021)\*
45. Radial club hand (May 2021)
46. Intrinsic plus hand (May 2021)
47. Metatarsus adductus (May 2021)
48. Meralgia paraesthetica (May 2021)

### Trauma

#### Essay

1.  Classify ankle fractures. Describe the mechanism of injury and discuss about the principles of management. (October 2018)
2.  Classify the fractures of spine based on mechanism of injury. Enumerate complications in a patient with quadriplegia. Discuss the management of pressure sores. (April 2019)
3.  Discuss the mechanism of injury, clinical features, imaging, management and complications of fracture neck of femur in a 75-year-old man. (October 2019)
4.  What are the stabilizers of the acromioclavicular joint. Discuss acute acromioclavicular dislocations. What are the management options in an old neglected acromioclavicular joint dislocation. (December 2020)
5.  Write on the classification, clinical features, management and complications of proximal humerus fracture in a young adult male. (June 2020)
6.  Discuss the classification, mechanism of injury and clinical features of hip dislocations. Write on the management and complications of posterior dislocation of hip joint in a young adult male. (May 2021)

#### Short Notes

1.  Locking compression plate (October 2018)
2.  Bennett's fracture (October 2018)\*
3.  Pulseless limb following supracondylar fracture humerus in a child (October 2018)
4.  Sacral fracture (October 2018)
5.  Terrible triad of Hotchkiss (October 2018)
6.  Lisfranc fracture (October 2018)\*
7.  Management of infected interlocking nail (October 2018)
8.  Management of neglected Monteggia fracture (October 2018)
9.  Complications of supracondylar fracture of the humerus (April 2019)
10. Greenstick fracture (April 2019)
11. Sudeck's osteodystrophy (April 2019)
12. Management of meniscal injuries (April 2019)
13. Fracture of patella (April 2019)
14. Dupuytren's fracture (April 2019)
15. Monteggia variants (April 2019)
16. Principles of management of closed fracture of a long bone (April 2019)
17. Classification of proximal tibial fractures (October 2019)
18. Clinical tests to diagnose cruciate ligament injuries in the knee (October 2019)
19. Types of physeal injuries with examples (October 2019)
20. Care of the paralysed limb in acute spinal cord injury (October 2019)
21. Hoffa’s fracture (October 2019)
22. Principles of management of an open fracture (October 2019)\*
23. Complications of Colle’s fracture (October 2019)
24. Anterior dislocation of shoulder joint (October 2019)
25. Classification systems for open fractures (December 2020)\*
26. Pink pulseless hand (December 2020)
27. Differences between spinal shock and neurogenic shock (December 2020)
28. Far cortical locking (December 2020)
29. Soft tissue injury (December 2020)
30. Atypical femoral fractures (December 2020)
31. Pilon fractures (December 2020)
32. Triangular fibrocartilage injury (December 2020)
33. External fixation (June 2020)
34. Monteggia fracture (June 2020)\*
35. Principles of management of an osteoporotic fracture (June 2020)
36. Hangman's fracture (June 2020)
37. Calcaneal fracture (June 2020)
38. Classification and complications of pelvic fracture (June 2020)
39. Management of post traumatic nerve palsy (June 2020)
40. Zone 2 flexor tendon injury (June 2020)
41. Bennett’s fracture (May 2021)\*
42. Galeazzi’s fracture (May 2021)
43. Principles of management of an intra articular fracture (May 2021)
44. Lisfranc fracture (May 2021)\*
45. Write on the mechanism, clinical features, management and complications of terrible triad injury of elbow in a young adult (May 2021)
46. Classification and complications of an open fracture (May 2021)\*
47. Management of thoracolumbar burst fractures (May 2021)
48. Epiphyseal injury (May 2021)

### Recent Advances

#### Essay

1.  Discuss the uses of isotopes in orthopaedics. Explain the management of multiple bone secondaries including recent advances. (October 2018)
2.  Describe the various types of total hip replacement prostheses based on surfaces. Discuss their limitations. (April 2019)
3.  Describe early onset scoliosis. How do you manage a 5-year-old girl with idiopathic early onset scoliosis. (December 2020)
4.  Discuss the diagnosis, clinical scoring and management of CTEV. (June 2020)
5.  Discuss the bearing surfaces in total hip arthroplasty with notes on the current concepts. (May 2021)

#### Short Notes

1.  Biodegradable implant (October 2018)
2.  Bone substitute (October 2018)
3.  Gamma camera (October 2018)
4.  Bone Morphogenetic Proteins (October 2018)
5.  Autologus blood transfusion (October 2018)
6.  PET scan (October 2018)
7.  Ceramic in orthopaedics (October 2018)\*
8.  Resurfacing arthroplasty of hip (October 2018)
9.  Spontaneous osteonecrosis of knee (April 2019)
10. Rivaroxaban (April 2019)
11. Teriparatide (April 2019)\*
12. 3D printing in orthopaedics (April 2019)
13. Hexapod (April 2019)
14. Endoscopic discectomy (April 2019)
15. Role of denosumab in Orthopaedics (April 2019)\*
16. GenExpert test (April 2019)
17. Open magnetic resonance imaging (December 2020)
18. Teriparatide (December 2020)\*
19. Stem cells in spinal cord injury (December 2020)
20. Autologous chondrocyte transplantation (December 2020)
21. Gene therapy in fracture healing (December 2020)
22. Safe surgical dislocation (December 2020)
23. Reverse shoulder arthroplasty (December 2020)
24. Role of arthroscopy in disorders of wrist (December 2020)
25. Titanium elastic nailing (TENS) (June 2020)
26. Ceramics in orthopaedics (June 2020)\*
27. Navigation in arthroplasty (June 2020)
28. Femoro-acetabular impingement (June 2020)
29. Percutaneous fixation in pelvi-acetabular fractures (June 2020)
30. Bed sore (June 2020)
31. Meniscal repair (June 2020)\*
32. Peri prosthetic fractures (June 2020)
33. Articular cartilage restoration techniques (May 2021)
34. Growing rod (May 2021)
35. Kyphoplasty (May 2021)
36. Platelet rich plasma in orthopaedics (May 2021)
37. Meniscal repair (May 2021)\*
38. Direct anterior approach in total hip replacement arthroplasty (May 2021)
39. Tranexamic acid (May 2021)
40. Recent advances in the treatment of unstable extracapsular fractures of the proximal femur (May 2021)

## 2021-24

### Basic Science

#### Essay

1.  Describe the physiological response after poly trauma and discuss in detail about damage control orthopaedics. (2021)
2.  Describe anatomy and function of articular cartilage. Discuss the management and complications of a 28-year male Football player with Grade III isolated 3 x 3 cm osteochondral lesion of medial femoral condyle. (2022)
3.  Infected nonunion of the distal third of tibia in 45-year-old chronic smoker and diabetic. Discuss the plan, management and its complications. (2022)
4.  Aetiology, pathogenesis, diagnosis and management of myositis ossificans. (2023)
5.  Describe the blood supply to femoral head in all age groups. Discuss the clinical implications in young child. (2024)
6.  Write a note on patho-anatomy of tuberculosis knee joint in adult, clinical features, complications and management. (2024)

#### Short Note

1.  Anatomy of median nerve. (2021)\*
2.  Stabilisers of knee joint. (2021)
3.  Uric acid. (2021)
4.  Physiology of micturition. (2021)
5.  Isolation of organism after an infected arthroplasty. (2021)
6.  Disease Modifying Anti-Rheumatoid Drugs (DMARDS). (2021)
7.  Parathormone. (2021)\*
8.  Anatomy of atlanto-axial joint. (2021)
9.  Vitamin D. (2022)\*
10. Long head of biceps. (2022)
11. Complete claw hand. (2022)
12. Genu valgum. (2022)
13. Bohler Braun frame. (2022)
14. Blood thinners & orthopaedic surgery. (2022)
15. Trendelenberg gait. (2022)
16. Clinical tests for DDH. (2022)
17. Bone transport and regenerate. (2022)\*
18. Lattismus dorsi. (2022)
19. Wrist drop. (2022)
20. Gun stock deformity. (2022)
21. SACH foot. (2022)
22. Indomethacin. (2022)
23. Dial test. (2022)
24. Carpal tunnel syndrome. (2023)
25. Functional cast bracing. (2023)\*
26. Ultrasound in orthopaedics. (2023)
27. Ganz safe surgical dislocation of hip. (2023)
28. Tourniquet. (2023)
29. Synovial fluid analysis. (2023)
30. Tranexamic acid. (2023)
31. Foot drop. (2024)
32. Teriparatide. (2024)
33. Quadriceps. (2024)
34. Anatomy of extensor compartment of wrist. (2024)
35. Masquelet technique. (2024)\*
36. Koch’s postulates. (2024)
37. Cubitus valgus deformity. (2024)
38. Arches of the foot. (2024)
39. Madura foot. (2024)
40. Denosumab. (2024)
41. Gluteus medius. (2024)
42. Anatomy of flexor compartment of wrist. (2024)
43. Papineau technique. (2024)
44. Minimal inhibitory concentration. (2024)
45. Manus valgus deformity. (2024)

### Orthopaedic Disease

#### Essay

1.  50-year-old female with right Genu varum presents with pain & reduced activity of daily living for over 1 year. This has worsened following recent trauma. However, she has good Range of movement of knee. Discuss the management of such a case in detail. (2021)
2.  25-year-old male sustained a twisting injury of his right knee. He could not continue the game as he developed immediate pain & knee swelling. He comes to your Emergency Medicine. Describe how will you proceed to manage such a case. (2022)
3.  Clinical features and management of osteosarcoma of distal femur in a 14-year-old male. (2022)
4.  How will you evaluate 8-year-old boy with painless limp. Enumerate differential diagnosis. Discuss management of developmental Dysplasia of Hip. (2023)
5.  Describe the management of multiple lytic lesion of bone in a 65-year-old male. (2024)
6.  Write on Enneking and Dunham classification and discuss in detail pelvic bone malignant tumours. (2024)

#### Short Note

1.  Rickets. (2021)
2.  Radioulnar synostosis. (2021)
3.  Hallux valgus. (2021)
4.  Pseudoarthrosis of tibia. (2021)
5.  Osteopetrosis. (2021)
6.  Giant Cell Tumor. (2021)
7.  Frozen shoulder. (2021)
8.  Suction socket prosthesis. (2021)
9.  Scurvy. (2022)
10. Sprengel shoulder. (2022)
11. Coxa vara. (2022)
12. Congenital vertical talus. (2022)
13. Haemophilic arthritis. (2022)
14. Ewings sarcoma. (2022)
15. Vertebra plana. (2022)
16. Legg calve perthes disease. (2022)
17. Erb’s palsy. (2022)
18. Ganglion cyst. (2022)
19. PTB (Patellar Tendon Bearing) prosthesis. (2022)
20. Gout. (2022)\*
21. Congenital pseudarthrosis of tibia. (2022)\*
22. Brodie’s abscess. (2022)
23. Femoroacetabular impingement syndrome. (2022)
24. Clinical features, management and complications of L4/L5 Intervertebral disc prolapse. (2022)
25. Limb salvage surgery in malignant tumours around the knee. (2023)
26. Middle path regime in management of Pott’s spine. (2023)
27. Femoro-acetabular impingement. (2023)\*
28. Gouty Arthritis. (2023)\*
29. Halo Vest. (2023)
30. Dupuytren’s contracture. (2023)
31. Mid-flexion instability of knee in Total Knee Replacement. (2023)
32. Cold abscess in spine. (2023)
33. Boutonniere deformity. (2024)
34. Cervical rib. (2024)
35. SCFE. (2024)
36. Kienbock’s disease. (2024)
37. Floor reaction orthosis. (2024)
38. Adolescent idiopathic scoliosis. (2024)
39. Autonomous bladder. (2024)\*
40. Crystal induced arthritis. (2024)
41. HLA antigen. (2024)
42. XDR tuberculosis. (2024)
43. Haemophilic arthropathy. (2024)\*
44. Myoelectric prosthesis. (2024)\*
45. Fibrous dysplasia. (2024)
46. Spondyloptosis. (2024)
47. Management of ulnar claw hand. (2024)
48. Brucellosis. (2024)

### Trauma

#### Essay

1.  Describe the aetiopathology, classification and management of fractures of proximal femur in children. Add a note on its complications. (2021)
2.  Classification, mechanism of injury, clinical features of traumatic elbow dislocation. Describe management and complications of Postero lateral dislocation of elbow. (2022)
3.  Classification, mechanism of injury, clinical features of traumatic knee dislocation. Describe the management & complication of Postero lateral dislocation of knee. (2022)
4.  Rotator cuff tear – Mechanism of injury, Classification, Diagnosis & Treatment. (2023)
5.  Classify thoraco lumbar spine injuries and discuss its management. (2024)
6.  Classify talus fracture and its clinical features, complications and discuss management. (2024)

#### Short Note

1.  Monteggia equivalents. (2021)
2.  Intra-compartment pressure monitoring. (2021)
3.  Pronation-external rotation injury of ankle. (2021)
4.  Triage. (2021)
5.  Osteochondral fractures of talus. (2021)
6.  Radiographic evaluation of upper cervical spine. (2021)
7.  Fat embolism. (2021)
8.  Radiological findings in Perthe’s disease. (2021)
9.  Scaphoid fracture. (2022)
10. Proximal humerus fracture. (2022)
11. Masquelet technique. (2022)\*
12. High ankle sprain. (2022)
13. Schatzker type V and VI fractures. (2022)
14. Flail chest. (2022)
15. Tibial spine avulsions. (2022)
16. Hamstring injury. (2022)
17. Kaplan’s lesion. (2022)
18. Volar Barton’s fracture. (2022)
19. Acromio clavicular joint dislocation Grade III. (2022)
20. Burst fracture L1. (2022)
21. Trimalleolar fracture ankle. (2022)
22. Hoffas fracture. (2022)
23. O’ Donoghue triad. (2022)
24. Neglected Tendoachillis tear. (2022)
25. Holstein Lewis fracture. (2023)
26. Syndesmotic injury. (2023)
27. Autonomous bladder. (2023)\*
28. Monteggia variants. (2023)
29. Flexor tendon injuries. (2023)
30. Vancouver classification of Periprosthetic fractures of hip-Elaborate on management. (2023)
31. Floating Knee. (2023)
32. Perilunar dislocations. (2023)
33. Flexor tendon injury of hand. (2024)
34. Functional cast bracing. (2024)\*
35. Calcaneal fracture. (2024)\*
36. Neglected Monteggia fracture. (2024)
37. AC joint dislocation. (2024)\*
38. MPFL tear. (2024)
39. Non-union fracture scaphoid. (2024)
40. Periprosthetic fracture of THR. (2024)
41. Kaplan lesion. (2024)\*
42. Pink pulseless hand. (2024)
43. Kyphoplasty. (2024)
44. Hangman fracture. (2024)
45. Posterolateral instability of knee joint. (2024)
46. Floating knee injury. (2024)\*
47. Fracture lower end of radius. (2024)

### Recent Advances

#### Essay

1.  What are musculoskeletal symptoms in Covid infection. Describe post Covid consequences in musculoskeletal system and management, with a note on trends and challenges in post Covid orthopaedic trauma management in India. (2021)
2.  Haemophilic arthropathy of knee. Discuss the plan and management strategies for total joint replacement of knee in such a case. (2022)
3.  Navigation assisted orthopaedic surgery. Add note on artificial intelligence and its future in orthopaedic surgery. (2023)
4.  Recent advances in evaluation and management of infection following total knee replacement. (2024)
5.  Discuss the management of painful total knee replacement. What are the issues involved in revision knee. What are the recent developments in total knee replacement. (2021)

#### Short Note

1.  High tibial osteotomy. (2021)
2.  Lumbar and cervical visco elastic disc replacement. (2021)
3.  Floor reaction orthosis. (2021)\*
4.  Mobile bearing knee. (2021)
5.  All suture anchor. (2021)
6.  Antibiotic delivery system in periprosthetic joint infection. (2021)
7.  Scaffold in rotator cuff surgery. (2021)
8.  Fiber tape. (2021)
9.  Blood flow restrictions in post-operative rehabilitation after Anterior cruciate ligament surgery. (2022)
10. 3 D printing. (2022)\*
11. Rheumatoid arthritis: new concepts and medications. (2022)
12. Visco supplementation in Osteoarthritis of knee. (2022)
13. Reverse shoulder arthroplasty. (2022)
14. Bone bank. (2022)\*
15. Advances in management of trochanteric fractures. (2022)
16. Ponseti Techniques. (2022)
17. 3D Printing in orthopaedics. (2023)\*
18. Dual mobility Total Hip Replacement. (2023)
19. Local antibiotic drug delivery systems in chronic osteomyelitis. (2023)
20. Osteogenesis Imperfecta-Recent trends in management. (2023)
21. Autologous chondrocyte transplantation. (2023)
22. Platelet Rich Plasma and its use in orthopaedics. (2023)
23. Anterolateral plating in distal tibia. (2023)
24. Total Ankle Arthroplasty. (2024)
25. Gene therapy in orthopaedics. (2024)
26. Myoelectric prosthesis. (2024)\*
27. Biplane double support screw fixation in management of neck of femur fractures. (2024)
28. Autologous blood transfusion in polytrauma. (2024)
29. Transforminal Endoscopic spine surgery. (2024)
30. Vacuum assisted closure in orthopaedic surgery. (2024)
31. Radio frequency ablation in orthopaedics. (2024)\*
32. Stem cells in orthopaedics. (2021)
33. Safe surgical dislocation of hip. (2021)\*
34. Continuous passive motion (CPM). (2021)
35. Causes for aseptic loosening in arthroplasty and discuss about how to reduce it. (2021)
36. Bone graft substitutes. (2021)
37. Gait lab. (2021)
38. Myo-electric arm. (2021)
39. Radio frequency ablation. (2021)\*
