---
title: "Diabetic foot"
---

## Diabetic foot

Diabetes is a systemic disease which causes - Neuropathy - Vasculopathy - Ulceration - Deformities

Hence it requires a MDT approach for diabetic treatment. This include <font color = "diamond">Hospital based MDT and Community based foot protection service</font>

#### Assessment

1.  How well the diabetes is controlled: **HBA**<sub>1</sub>C

2.  Presence of neuropathy

    -   Motor: **Deformities, intrinsic minus, weak TibAnt, MT head pressure**
    -   Sensory: Loss of protective sensation (10g S-W monofilament, vibration 128hz)
    -   Autonomic: Dry skin, nail changes,increased vascular response to trauma

3.  Presence of Vasculitis

    -   ABPI >0.45 and triphasic flow in dopplar
    -   TrC-O<sub>2</sub> >30
    -   Absolute toe pressure >40 mmHg
    -   Pulse

4.  Presence of Ulceration

    -   Ulceration could be either infected or non infected. In all ulcers, we have to rule out ischemia (vascular ulcer) and Neuropathy.

5.  Deformities

#### Classification

-   SINBAD for ulcer
-   University of texas classificatio for foot

##### SINBAD Classification

-   Site
-   Ischemia
-   Neuropathy
-   Bacterial infection
-   Area
-   Depth

##### University of Texas Classification

| Grade | 0                          | 1                | 2          | 3            |
|-------|----------------------------|------------------|------------|--------------|
| Stage |                            |                  |            |              |
| A     | Foot at risk               | Supeficial Ulcer | Deep Ulcer | Bone exposed |
| B     | Infected                   |                  |            |              |
| C     | Ischemic                   |                  |            |              |
| D     | Both infected and ischemic |                  |            |              |

#### Management

1.  **General**: Prevention, education and accomodative foot wear.
2.  Ulcer management It depends on whether the ulcer is infected or not.

##### Uninfected ulcer manaagement

if the ulcer is uninfected we should be first differentiate wheter it is neuropathic or vascular ulcer.

<font color = "emerald"> Neuropathic ulcers

-   Seen under the metatarsal heads
-   Punched out
-   Painless
-   Healthy granulation
-   Pulse will be present
-   There will be loss of vibration sensation </font>

Treatment is Total Contact Cast followed by accomodative footwear.

<font color="blue"> Vascular ulcers

-   Seen any where
-   Painful
-   Pulse may be absent</font>

Requires vascular team assessment for angioplasty/bipass. This will be followed by TCC and accomodative foot wear

##### Infected ulcer management

If the ulcer is ischemic, it should be managed by vascular team

Otherwise, the local hospital team will be managing and that range from appropriate antibiotics as per culture to Amputation.

#### Deformity management

##### A/C presentations that need surgery

-   Medical dislocation of T-N joint causing plano valgus deformity
-   Dorsal dislocation of T-N joint causing lateral rocker bottom
-   Infection requiring drainage/sepsis
-   Ischemia/gangrene

##### Chronic deformities

###### Principles

-   prolonged non weight bearing (4 months) followed by protected weight bearing
-   TCC/Accomodative foot wear is the main stay treatment
-   prefer arthrodesis over ORIF