---
title: "Fragility prevention"
---

AMP kinase is believed to be the central switch that positively regulate the life span of an individual.

It is upregulated by:

-   Aerobic exercise

-   Starvation

-   Decreased protein intake

mTOR, mammalian target of rapamycin, is central in building muscle mass. Muscle mass is important for healthy aging, ie., health span.

mTOR is upregulated by:

-   Animal protein

-   Strengthening exercises

One important role of mTOR is to inhibit AMP kinase, there by negatively affecting the life span.

This cell level interplay has got important practical implecations.

-   Aerobic exercises go with low protein diet and starvation

-   Strengthening exercises go with high protein intake

-   One should not mix aerobic with strengthening exercises. There should be atleast 12 hrs gap between them.

-   Lot of animal protein and strenghtening exersises will increase muscle mass. But the same has got negative affect on life span.

-   Hence, limit animal protein and strengthening exercises to 2 days per week. Rest of the days, take less protein and do aerobic exercises.

## **Strengthening exercise**

-   Regular repeated weight lifting for a fixed period of time, say, 30 minutes.

## **Aerobic exercise**

-   150 minutes of moderate intensity or 75 minutes of high intensity aerobic exercise are both benefical
